classdef DynamicMRIAcquisition < openminds.abstract.Schema
%DynamicMRIAcquisition - No description available.
%
%   PROPERTIES:
%
%   behavioralProtocol       : (1,:) <a href="matlab:help openminds.core.research.BehavioralProtocol" style="font-weight:bold">BehavioralProtocol</a>
%                              Add the behavioral protocol or protocols applied during this acquisition, including all tasks or observed behavioral conditions (for example, resting state).
%
%   contrastAgent            : (1,:) <a href="matlab:help openminds.chemicals.AmountOfChemical" style="font-weight:bold">AmountOfChemical</a>
%                              Add the contrast agent(s) administered for this acquisition, including for each the agent identity and administered amount; if no contrast agent was used, leave this field null. Include all agents given prior to or during the scan.
%
%   customPropertySet        : (1,:) <a href="matlab:help openminds.core.research.CustomPropertySet" style="font-weight:bold">CustomPropertySet</a>
%                              Add any user-defined parameters grouped in context-specific sets that are not covered in the standardized properties of this activity.
%
%   delayTime                : (1,1) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                              Enter the delay time, defined as the time interval between a protocol-defined reference event (for example, stimulus onset, contrast administration, or physiological trigger) and the start of dynamic image acquisition, expressed in seconds. This value should reflect the actual timing applied during the scan.
%
%   description              : (1,1) string
%                              Enter a description of this activity.
%
%   device                   : (1,1) <a href="matlab:help openminds.neuroimaging.device.MRIScannerUsage" style="font-weight:bold">MRIScannerUsage</a>
%                              Add the magnetic resonance imaging (MRI) scanner used for this acquisition. This reference should identify the specific device configuration under which the scan was performed.
%
%   distortionCorrection     : (1,:) <a href="matlab:help openminds.core.data.File" style="font-weight:bold">File</a>
%                              Add the distortion correction data used for this acquisition, linking to the calibration files applied during image reconstruction or post-processing. If no distortion correction was performed, leave this field null.
%
%   endTime                  : (1,1) datetime
%                              Enter the date and/or time on when this activity ended, formatted as either '2023-02-07T16:00:00+00:00' (date-time) or '16:00:00+00:00' (time).
%
%   input                    : (1,:) <a href="matlab:help openminds.core.research.SubjectState" style="font-weight:bold">SubjectState</a>, <a href="matlab:help openminds.core.research.TissueSampleState" style="font-weight:bold">TissueSampleState</a>
%                              Add the specimen (subject or tissue sample) in the physical and biological state in which it was scanned, referencing the corresponding specimen record at the time of imaging.
%
%   isPartOf                 : (1,1) <a href="matlab:help openminds.core.products.DatasetVersion" style="font-weight:bold">DatasetVersion</a>
%                              Add the dataset version in which this activity was conducted.
%
%   lookupLabel              : (1,1) string
%                              Enter a lookup label for this activity that may help you to find this instance more easily.
%
%   motionCorrection         : (1,:) <a href="matlab:help openminds.core.data.File" style="font-weight:bold">File</a>
%                              Add the motion correction data used for this acquisition, linking to the calibration files or reference images applied during image reconstruction or post-processing. If no motion correction was performed, leave this field null.
%
%   numberOfDiscardedVolumes : (1,1) int64
%                              Enter the number of image volumes discarded by the operator or analyst prior to post-processing, including initial equilibration volumes and any later volumes removed due to artifacts or instability. This value should reflect the total user-defined exclusion applied after acquisition.
%
%   output                   : (1,:) <a href="matlab:help openminds.core.data.File" style="font-weight:bold">File</a>
%                              Add the output data generated by this acquisition by linking to one or more files containing the primary imaging outputs and/or, if applicable, any secondary reconstructed or corrected outputs produced during post-processing.
%
%   performedBy              : (1,:) <a href="matlab:help openminds.computation.SoftwareAgent" style="font-weight:bold">SoftwareAgent</a>, <a href="matlab:help openminds.core.actors.Person" style="font-weight:bold">Person</a>
%                              Add all agents that performed this activity.
%
%   preparationDesign        : (1,1) <a href="matlab:help openminds.controlledterms.PreparationType" style="font-weight:bold">PreparationType</a>
%                              Add the initial preparation type for this activity.
%
%   protocol                 : (1,:) <a href="matlab:help openminds.core.research.Protocol" style="font-weight:bold">Protocol</a>
%                              Add all protocols used during this activity.
%
%   registrationData         : (1,:) <a href="matlab:help openminds.core.data.File" style="font-weight:bold">File</a>
%                              Add the registration data used for this acquisition, linking to the transformation and/or reference files applied during image alignment in post-processing. If no registration was performed, leave this field null.
%
%   specimenOrientation      : (1,1) <a href="matlab:help openminds.controlledterms.AnatomicalAxesOrientation" style="font-weight:bold">AnatomicalAxesOrientation</a>
%                              Add the specimen orientation as the anatomical directions corresponding to the scanner X, Y, and Z axes, describing the alignment of the specimen's anatomy with the scanner coordinate system. Note that this orientation may differ from the prescribed slice orientation, especially in nonstandard specimen positioning.
%
%   startTime                : (1,1) datetime
%                              Enter the date and/or time on when this activity started, formatted as either '2023-02-07T16:00:00+00:00' (date-time) or '16:00:00+00:00' (time).
%
%   studyTarget              : (1,:) <a href="matlab:help openminds.controlledterms.AnatomicalCavity" style="font-weight:bold">AnatomicalCavity</a>, <a href="matlab:help openminds.controlledterms.AuditoryStimulusType" style="font-weight:bold">AuditoryStimulusType</a>, <a href="matlab:help openminds.controlledterms.BiologicalOrder" style="font-weight:bold">BiologicalOrder</a>, <a href="matlab:help openminds.controlledterms.BiologicalSex" style="font-weight:bold">BiologicalSex</a>, <a href="matlab:help openminds.controlledterms.BreedingType" style="font-weight:bold">BreedingType</a>, <a href="matlab:help openminds.controlledterms.CellCultureType" style="font-weight:bold">CellCultureType</a>, <a href="matlab:help openminds.controlledterms.CellType" style="font-weight:bold">CellType</a>, <a href="matlab:help openminds.controlledterms.DeviceType" style="font-weight:bold">DeviceType</a>, <a href="matlab:help openminds.controlledterms.Disease" style="font-weight:bold">Disease</a>, <a href="matlab:help openminds.controlledterms.DiseaseModel" style="font-weight:bold">DiseaseModel</a>, <a href="matlab:help openminds.controlledterms.ElectricalStimulusType" style="font-weight:bold">ElectricalStimulusType</a>, <a href="matlab:help openminds.controlledterms.ExternalBodyRegion" style="font-weight:bold">ExternalBodyRegion</a>, <a href="matlab:help openminds.controlledterms.GeneticStrainType" style="font-weight:bold">GeneticStrainType</a>, <a href="matlab:help openminds.controlledterms.GustatoryStimulusType" style="font-weight:bold">GustatoryStimulusType</a>, <a href="matlab:help openminds.controlledterms.Handedness" style="font-weight:bold">Handedness</a>, <a href="matlab:help openminds.controlledterms.MolecularEntity" style="font-weight:bold">MolecularEntity</a>, <a href="matlab:help openminds.controlledterms.MuscularStructure" style="font-weight:bold">MuscularStructure</a>, <a href="matlab:help openminds.controlledterms.NervousSystemStructure" style="font-weight:bold">NervousSystemStructure</a>, <a href="matlab:help openminds.controlledterms.OlfactoryStimulusType" style="font-weight:bold">OlfactoryStimulusType</a>, <a href="matlab:help openminds.controlledterms.OpticalStimulusType" style="font-weight:bold">OpticalStimulusType</a>, <a href="matlab:help openminds.controlledterms.Organ" style="font-weight:bold">Organ</a>, <a href="matlab:help openminds.controlledterms.OrganSystemStructure" style="font-weight:bold">OrganSystemStructure</a>, <a href="matlab:help openminds.controlledterms.OrganismSubstance" style="font-weight:bold">OrganismSubstance</a>, <a href="matlab:help openminds.controlledterms.OrganismSystem" style="font-weight:bold">OrganismSystem</a>, <a href="matlab:help openminds.controlledterms.SkeletalStructure" style="font-weight:bold">SkeletalStructure</a>, <a href="matlab:help openminds.controlledterms.Species" style="font-weight:bold">Species</a>, <a href="matlab:help openminds.controlledterms.SubcellularEntity" style="font-weight:bold">SubcellularEntity</a>, <a href="matlab:help openminds.controlledterms.TactileStimulusType" style="font-weight:bold">TactileStimulusType</a>, <a href="matlab:help openminds.controlledterms.TermSuggestion" style="font-weight:bold">TermSuggestion</a>, <a href="matlab:help openminds.controlledterms.TissueSampleType" style="font-weight:bold">TissueSampleType</a>, <a href="matlab:help openminds.controlledterms.TissueStructure" style="font-weight:bold">TissueStructure</a>, <a href="matlab:help openminds.controlledterms.VascularStructure" style="font-weight:bold">VascularStructure</a>, <a href="matlab:help openminds.controlledterms.VisualStimulusType" style="font-weight:bold">VisualStimulusType</a>, <a href="matlab:help openminds.sands.atlas.ParcellationEntity" style="font-weight:bold">ParcellationEntity</a>, <a href="matlab:help openminds.sands.atlas.ParcellationEntityVersion" style="font-weight:bold">ParcellationEntityVersion</a>, <a href="matlab:help openminds.sands.nonatlas.CustomAnatomicalEntity" style="font-weight:bold">CustomAnatomicalEntity</a>
%                              Add all study targets of this activity.
%
%   targetAnatomy            : (1,1) <a href="matlab:help openminds.controlledterms.AnatomicalCavity" style="font-weight:bold">AnatomicalCavity</a>, <a href="matlab:help openminds.controlledterms.CellType" style="font-weight:bold">CellType</a>, <a href="matlab:help openminds.controlledterms.ExternalBodyRegion" style="font-weight:bold">ExternalBodyRegion</a>, <a href="matlab:help openminds.controlledterms.MuscularStructure" style="font-weight:bold">MuscularStructure</a>, <a href="matlab:help openminds.controlledterms.NervousSystemStructure" style="font-weight:bold">NervousSystemStructure</a>, <a href="matlab:help openminds.controlledterms.Organ" style="font-weight:bold">Organ</a>, <a href="matlab:help openminds.controlledterms.OrganSystemStructure" style="font-weight:bold">OrganSystemStructure</a>, <a href="matlab:help openminds.controlledterms.OrganismSubstance" style="font-weight:bold">OrganismSubstance</a>, <a href="matlab:help openminds.controlledterms.OrganismSystem" style="font-weight:bold">OrganismSystem</a>, <a href="matlab:help openminds.controlledterms.SkeletalStructure" style="font-weight:bold">SkeletalStructure</a>, <a href="matlab:help openminds.controlledterms.SubcellularEntity" style="font-weight:bold">SubcellularEntity</a>, <a href="matlab:help openminds.controlledterms.TissueStructure" style="font-weight:bold">TissueStructure</a>, <a href="matlab:help openminds.controlledterms.VascularStructure" style="font-weight:bold">VascularStructure</a>, <a href="matlab:help openminds.sands.atlas.ParcellationEntity" style="font-weight:bold">ParcellationEntity</a>, <a href="matlab:help openminds.sands.atlas.ParcellationEntityVersion" style="font-weight:bold">ParcellationEntityVersion</a>, <a href="matlab:help openminds.sands.nonatlas.CustomAnatomicalEntity" style="font-weight:bold">CustomAnatomicalEntity</a>
%                              Add the target anatomy, indicating the primary anatomical structure or region intended to be imaged in this acquisition. This field describes the imaging objective (for example, organ, tissue, or structure) and may be derived from the acquisition protocol description.
%
%   volumeAcquisitionTime    : (1,1) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                              Enter the volume acquisition time, defined as the time required to acquire a single image volume, expressed in seconds. This value is typically equivalent to the repetition time for volume-based acquisitions and can be retrieved from the sequence timing information in the DICOM header.
%
%   volumeTiming             : (1,1) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValueArray" style="font-weight:bold">QuantitativeValueArray</a>
%                              Enter the volume timing as an array specifying the acquisition time of each volume relative to the start of the dynamic scan, expressed in seconds, with one entry per acquired volume. These values may be derived from the repetition time or extracted from the acquisition metadata.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add the behavioral protocol or protocols applied during this acquisition, including all tasks or observed behavioral conditions (for example, resting state).
        behavioralProtocol (1,:) openminds.core.research.BehavioralProtocol ...
            {mustBeListOfUniqueItems(behavioralProtocol)}

        % Add the contrast agent(s) administered for this acquisition, including for each the agent identity and administered amount; if no contrast agent was used, leave this field null. Include all agents given prior to or during the scan.
        contrastAgent (1,:) openminds.chemicals.AmountOfChemical ...
            {mustBeListOfUniqueItems(contrastAgent)}

        % Add any user-defined parameters grouped in context-specific sets that are not covered in the standardized properties of this activity.
        customPropertySet (1,:) openminds.core.research.CustomPropertySet ...
            {mustBeListOfUniqueItems(customPropertySet)}

        % Enter the delay time, defined as the time interval between a protocol-defined reference event (for example, stimulus onset, contrast administration, or physiological trigger) and the start of dynamic image acquisition, expressed in seconds. This value should reflect the actual timing applied during the scan.
        delayTime (1,:) openminds.core.miscellaneous.QuantitativeValue ...
            {mustBeSpecifiedLength(delayTime, 0, 1)}

        % Enter a description of this activity.
        description (1,1) string

        % Add the magnetic resonance imaging (MRI) scanner used for this acquisition. This reference should identify the specific device configuration under which the scan was performed.
        device (1,:) openminds.neuroimaging.device.MRIScannerUsage ...
            {mustBeSpecifiedLength(device, 0, 1)}

        % Add the distortion correction data used for this acquisition, linking to the calibration files applied during image reconstruction or post-processing. If no distortion correction was performed, leave this field null.
        distortionCorrection (1,:) openminds.core.data.File ...
            {mustBeListOfUniqueItems(distortionCorrection)}

        % Enter the date and/or time on when this activity ended, formatted as either '2023-02-07T16:00:00+00:00' (date-time) or '16:00:00+00:00' (time).
        endTime (1,:) datetime ...
            {mustBeSpecifiedLength(endTime, 0, 1)}

        % Add the specimen (subject or tissue sample) in the physical and biological state in which it was scanned, referencing the corresponding specimen record at the time of imaging.
        input (1,:) openminds.internal.mixedtype.dynamicmriacquisition.Input ...
            {mustBeListOfUniqueItems(input)}

        % Add the dataset version in which this activity was conducted.
        isPartOf (1,:) openminds.core.products.DatasetVersion ...
            {mustBeSpecifiedLength(isPartOf, 0, 1)}

        % Enter a lookup label for this activity that may help you to find this instance more easily.
        lookupLabel (1,1) string

        % Add the motion correction data used for this acquisition, linking to the calibration files or reference images applied during image reconstruction or post-processing. If no motion correction was performed, leave this field null.
        motionCorrection (1,:) openminds.core.data.File ...
            {mustBeListOfUniqueItems(motionCorrection)}

        % Enter the number of image volumes discarded by the operator or analyst prior to post-processing, including initial equilibration volumes and any later volumes removed due to artifacts or instability. This value should reflect the total user-defined exclusion applied after acquisition.
        numberOfDiscardedVolumes (1,:) int64 ...
            {mustBeSpecifiedLength(numberOfDiscardedVolumes, 0, 1)}

        % Add the output data generated by this acquisition by linking to one or more files containing the primary imaging outputs and/or, if applicable, any secondary reconstructed or corrected outputs produced during post-processing.
        output (1,:) openminds.core.data.File ...
            {mustBeListOfUniqueItems(output)}

        % Add all agents that performed this activity.
        performedBy (1,:) openminds.internal.mixedtype.dynamicmriacquisition.PerformedBy ...
            {mustBeListOfUniqueItems(performedBy)}

        % Add the initial preparation type for this activity.
        preparationDesign (1,:) openminds.controlledterms.PreparationType ...
            {mustBeSpecifiedLength(preparationDesign, 0, 1)}

        % Add all protocols used during this activity.
        protocol (1,:) openminds.core.research.Protocol ...
            {mustBeListOfUniqueItems(protocol)}

        % Add the registration data used for this acquisition, linking to the transformation and/or reference files applied during image alignment in post-processing. If no registration was performed, leave this field null.
        registrationData (1,:) openminds.core.data.File ...
            {mustBeListOfUniqueItems(registrationData)}

        % Add the specimen orientation as the anatomical directions corresponding to the scanner X, Y, and Z axes, describing the alignment of the specimen's anatomy with the scanner coordinate system. Note that this orientation may differ from the prescribed slice orientation, especially in nonstandard specimen positioning.
        specimenOrientation (1,:) openminds.controlledterms.AnatomicalAxesOrientation ...
            {mustBeSpecifiedLength(specimenOrientation, 0, 1)}

        % Enter the date and/or time on when this activity started, formatted as either '2023-02-07T16:00:00+00:00' (date-time) or '16:00:00+00:00' (time).
        startTime (1,:) datetime ...
            {mustBeSpecifiedLength(startTime, 0, 1)}

        % Add all study targets of this activity.
        studyTarget (1,:) openminds.internal.mixedtype.dynamicmriacquisition.StudyTarget ...
            {mustBeListOfUniqueItems(studyTarget)}

        % Add the target anatomy, indicating the primary anatomical structure or region intended to be imaged in this acquisition. This field describes the imaging objective (for example, organ, tissue, or structure) and may be derived from the acquisition protocol description.
        targetAnatomy (1,:) openminds.internal.mixedtype.dynamicmriacquisition.TargetAnatomy ...
            {mustBeSpecifiedLength(targetAnatomy, 0, 1)}

        % Enter the volume acquisition time, defined as the time required to acquire a single image volume, expressed in seconds. This value is typically equivalent to the repetition time for volume-based acquisitions and can be retrieved from the sequence timing information in the DICOM header.
        volumeAcquisitionTime (1,:) openminds.core.miscellaneous.QuantitativeValue ...
            {mustBeSpecifiedLength(volumeAcquisitionTime, 0, 1)}

        % Enter the volume timing as an array specifying the acquisition time of each volume relative to the start of the dynamic scan, expressed in seconds, with one entry per acquired volume. These values may be derived from the repetition time or extracted from the acquisition metadata.
        volumeTiming (1,:) openminds.core.miscellaneous.QuantitativeValueArray ...
            {mustBeSpecifiedLength(volumeTiming, 0, 1)}
    end

    properties (Access = protected)
        Required = ["behavioralProtocol", "device", "input", "isPartOf", "output", "protocol", "specimenOrientation", "volumeAcquisitionTime"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/DynamicMRIAcquisition"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'behavioralProtocol', "openminds.core.research.BehavioralProtocol", ...
            'device', "openminds.neuroimaging.device.MRIScannerUsage", ...
            'distortionCorrection', "openminds.core.data.File", ...
            'input', ["openminds.core.research.SubjectState", "openminds.core.research.TissueSampleState"], ...
            'isPartOf', "openminds.core.products.DatasetVersion", ...
            'motionCorrection', "openminds.core.data.File", ...
            'output', "openminds.core.data.File", ...
            'performedBy', ["openminds.computation.SoftwareAgent", "openminds.core.actors.Person"], ...
            'preparationDesign', "openminds.controlledterms.PreparationType", ...
            'protocol', "openminds.core.research.Protocol", ...
            'registrationData', "openminds.core.data.File", ...
            'specimenOrientation', "openminds.controlledterms.AnatomicalAxesOrientation", ...
            'studyTarget', ["openminds.controlledterms.AnatomicalCavity", "openminds.controlledterms.AuditoryStimulusType", "openminds.controlledterms.BiologicalOrder", "openminds.controlledterms.BiologicalSex", "openminds.controlledterms.BreedingType", "openminds.controlledterms.CellCultureType", "openminds.controlledterms.CellType", "openminds.controlledterms.DeviceType", "openminds.controlledterms.Disease", "openminds.controlledterms.DiseaseModel", "openminds.controlledterms.ElectricalStimulusType", "openminds.controlledterms.ExternalBodyRegion", "openminds.controlledterms.GeneticStrainType", "openminds.controlledterms.GustatoryStimulusType", "openminds.controlledterms.Handedness", "openminds.controlledterms.MolecularEntity", "openminds.controlledterms.MuscularStructure", "openminds.controlledterms.NervousSystemStructure", "openminds.controlledterms.OlfactoryStimulusType", "openminds.controlledterms.OpticalStimulusType", "openminds.controlledterms.Organ", "openminds.controlledterms.OrganSystemStructure", "openminds.controlledterms.OrganismSubstance", "openminds.controlledterms.OrganismSystem", "openminds.controlledterms.SkeletalStructure", "openminds.controlledterms.Species", "openminds.controlledterms.SubcellularEntity", "openminds.controlledterms.TactileStimulusType", "openminds.controlledterms.TermSuggestion", "openminds.controlledterms.TissueSampleType", "openminds.controlledterms.TissueStructure", "openminds.controlledterms.VascularStructure", "openminds.controlledterms.VisualStimulusType", "openminds.sands.atlas.ParcellationEntity", "openminds.sands.atlas.ParcellationEntityVersion", "openminds.sands.nonatlas.CustomAnatomicalEntity"], ...
            'targetAnatomy', ["openminds.controlledterms.AnatomicalCavity", "openminds.controlledterms.CellType", "openminds.controlledterms.ExternalBodyRegion", "openminds.controlledterms.MuscularStructure", "openminds.controlledterms.NervousSystemStructure", "openminds.controlledterms.Organ", "openminds.controlledterms.OrganSystemStructure", "openminds.controlledterms.OrganismSubstance", "openminds.controlledterms.OrganismSystem", "openminds.controlledterms.SkeletalStructure", "openminds.controlledterms.SubcellularEntity", "openminds.controlledterms.TissueStructure", "openminds.controlledterms.VascularStructure", "openminds.sands.atlas.ParcellationEntity", "openminds.sands.atlas.ParcellationEntityVersion", "openminds.sands.nonatlas.CustomAnatomicalEntity"] ...
        )
        EMBEDDED_PROPERTIES = struct(...
            'contrastAgent', "openminds.chemicals.AmountOfChemical", ...
            'customPropertySet', "openminds.core.research.CustomPropertySet", ...
            'delayTime', "openminds.core.miscellaneous.QuantitativeValue", ...
            'volumeAcquisitionTime', "openminds.core.miscellaneous.QuantitativeValue", ...
            'volumeTiming', "openminds.core.miscellaneous.QuantitativeValueArray" ...
        )
    end

    methods
        function obj = DynamicMRIAcquisition(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.neuroimaging.activity.DynamicMRIAcquisition
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.lookupLabel;
        end
    end
end
