classdef Organization < openminds.abstract.Schema
%Organization - Structured information on an organization.
%
%   PROPERTIES:
%
%   digitalIdentifier : (1,:) <a href="matlab:help openminds.core.DigitalIdentifier" style="font-weight:bold">DigitalIdentifier</a>
%                       Add one or several globally unique and persistent digital identifier for this organization.
%
%   fullName          : (1,1) string
%                       Enter the full name of the organization.
%
%   hasParent         : (1,1) <a href="matlab:help openminds.core.Organization" style="font-weight:bold">Organization</a>
%                       Add a parent organization to this organization.
%
%   homepage          : (1,1) string
%                       Enter a internationalized resource identifier (IRI) to the homepage of this organization.
%
%   shortName         : (1,1) string
%                       Enter the short name of this organization.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add one or several globally unique and persistent digital identifier for this organization.
        digitalIdentifier (1,:) openminds.core.DigitalIdentifier ...
            {mustBeListOfUniqueItems(digitalIdentifier)}

        % Enter the full name of the organization.
        fullName (1,1) string

        % Add a parent organization to this organization.
        hasParent (1,:) openminds.core.Organization ...
            {mustBeSpecifiedLength(hasParent, 0, 1)}

        % Enter a internationalized resource identifier (IRI) to the homepage of this organization.
        homepage (1,1) string

        % Enter the short name of this organization.
        shortName (1,1) string
    end

    properties (Access = protected)
        Required = ["fullName"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.ebrains.eu/core/Organization"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'digitalIdentifier', "openminds.core.DigitalIdentifier", ...
            'hasParent', "openminds.core.Organization" ...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = Organization(varargin)
            obj.assignPVPairs(varargin{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = sprintf('%s', obj.fullName);
        end
    end

end