classdef Environment < openminds.internal.abstract.LinkedCategory
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.computation.Environment", ...
            "openminds.core.products.WebServiceVersion" ...
        ]
        IS_SCALAR = true
    end
end