classdef SpecimenWeight < openminds.abstract.Schema
%SpecimenWeight - No description available.
%
%   PROPERTIES:
%
%   type   : (1,1) <a href="matlab:help openminds.controlledterms.WeightType" style="font-weight:bold">WeightType</a>
%            Enter the weight type for the specified weight value.
%
%   weight : (1,1) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>, <a href="matlab:help openminds.core.miscellaneous.QuantitativeValueRange" style="font-weight:bold">QuantitativeValueRange</a>
%            Enter the weight value.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter the weight type for the specified weight value.
        type (1,:) openminds.controlledterms.WeightType ...
            {mustBeSpecifiedLength(type, 0, 1)}

        % Enter the weight value.
        weight (1,:) openminds.internal.mixedtype.specimenweight.Weight ...
            {mustBeSpecifiedLength(weight, 0, 1)}
    end

    properties (Access = protected)
        Required = ["type", "weight"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/SpecimenWeight"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'type', "openminds.controlledterms.WeightType" ...
        )
        EMBEDDED_PROPERTIES = struct(...
            'weight', ["openminds.core.miscellaneous.QuantitativeValue", "openminds.core.miscellaneous.QuantitativeValueRange"] ...
        )
    end

    methods
        function obj = SpecimenWeight(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.core.research.SpecimenWeight
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.createLabelForMissingLabelDefinition();
        end
    end
end
