classdef StockNumber < openminds.abstract.Schema
%StockNumber - No description available.
%
%   PROPERTIES:
%
%   identifier : (1,1) string
%                Enter the stock number of an item provided by a store or company.
%
%   vendor     : (1,1) <a href="matlab:help openminds.core.Organization" style="font-weight:bold">Organization</a>
%                Add the vendor that has the item with this identifier in stock.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter the stock number of an item provided by a store or company.
        identifier (1,1) string

        % Add the vendor that has the item with this identifier in stock.
        vendor (1,:) openminds.core.Organization ...
            {mustBeSpecifiedLength(vendor, 0, 1)}
    end

    properties (Access = protected)
        Required = ["identifier", "vendor"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.ebrains.eu/core/StockNumber"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'vendor', "openminds.core.Organization" ...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = StockNumber(varargin)
            obj.assignPVPairs(varargin{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = sprintf('%s', obj.identifier);
        end
    end

end