classdef TermSuggestion < openminds.abstract.ControlledTerm
%TermSuggestion - No description available.
%
%   PROPERTIES:
%
%   addExistingTerminology      : (1,1) <a href="matlab:help openminds.controlledterms.Terminology" style="font-weight:bold">Terminology</a>
%                                 Add an existing terminology in which the suggested term should be integrated in.
%
%   definition                  : (1,1) string
%                                 Enter one sentence for defining this term.
%
%   description                 : (1,1) string
%                                 Enter a short text describing this term.
%
%   interlexIdentifier          : (1,1) string
%                                 Enter the internationalized resource identifier (IRI) pointing to the integrated ontology entry in the InterLex project.
%
%   knowledgeSpaceLink          : (1,1) string
%                                 Enter the internationalized resource identifier (IRI) pointing to the wiki page of the corresponding term in the KnowledgeSpace.
%
%   name                        : (1,1) string
%                                 Controlled term originating from a defined terminology.
%
%   preferredOntologyIdentifier : (1,1) string
%                                 Enter the internationalized resource identifier (IRI) pointing to the preferred ontological term.
%
%   suggestNewTerminology       : (1,1) string
%                                 Propose a name for a new terminology in which the suggested term should be integrated in.
%
%   synonym                     : (1,:) string
%                                 Enter one or several synonyms (including abbreviations) for this controlled term.

%   This class was auto-generated by the openMINDS pipeline

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/TermSuggestion"
    end

    properties (Constant, Hidden)
        CONTROLLED_INSTANCES = [ ...
        ]
    end

    methods
        function obj = TermSuggestion(varargin)
            obj@openminds.abstract.ControlledTerm(varargin{:})
        end
    end
end
