classdef RelatedPublication < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.core.miscellaneous.DOI", ...
            "openminds.core.miscellaneous.ISBN" ...
        ]
        IS_SCALAR = false
    end
end