function map = getPluralToSingluarTypeMap()
    map = struct(...
        "brainAtlasVersions", "BrainAtlasVersion", ...
        "brainAtlases", "BrainAtlas", ...
        "commonCoordinateSpaceVersions", "CommonCoordinateSpaceVersion", ...
        "commonCoordinateSpaces", "CommonCoordinateSpace", ...
        "contentTypes", "ContentType", ...
        "licenses", "License", ...
        "parcellationEntities", "parcellationEntity", ...
        "parcellationEntityVersions", "parcellationEntityVersion" ...
        );
    map = containers.Map(fieldnames(map), struct2cell(map));
end
