classdef MetaDataModel < openminds.abstract.Schema
%MetaDataModel - No description available.
%
%   PROPERTIES:
%
%   custodian         : (1,:) <a href="matlab:help openminds.core.Organization" style="font-weight:bold">Organization</a>, <a href="matlab:help openminds.core.Person" style="font-weight:bold">Person</a>
%                       Add one or several custodians (person or organization) that are responsible for this research product. Note that this custodian will be responsible for all attached research product versions.
%
%   description       : (1,1) string
%                       Enter a description (abstract) for this research product (max. 2000 characters, incl. spaces; no references). Note that this description should be fitting for all attached research product versions.
%
%   developer         : (1,:) <a href="matlab:help openminds.core.Organization" style="font-weight:bold">Organization</a>, <a href="matlab:help openminds.core.Person" style="font-weight:bold">Person</a>
%                       Add one or several developers (person or organization) that contributed to the code implementation of this software.
%
%   digitalIdentifier : (1,1) <a href="matlab:help openminds.core.DOI" style="font-weight:bold">DOI</a>, <a href="matlab:help openminds.core.SWHID" style="font-weight:bold">SWHID</a>
%                       Add the globally unique and persistent digital identifier of this research product. Note that this digital identifier will be used to reference all attached research product versions.
%
%   fullName          : (1,1) string
%                       Enter a descriptive full name (title) for this research product.  Note that this full name should be fitting for all attached research product versions.
%
%   hasVersion        : (1,:) <a href="matlab:help openminds.core.MetaDataModelVersion" style="font-weight:bold">MetaDataModelVersion</a>
%                       Add one or several versions of this (meta)data model.
%
%   homepage          : (1,1) <a href="matlab:help openminds.core.URL" style="font-weight:bold">URL</a>
%                       Add the uniform resource locator (URL) to the homepage of this research product.
%
%   howToCite         : (1,1) string
%                       Enter the preferred citation text for this research product. Leave blank if citation text can be extracted from the assigned digital identifier.
%
%   shortName         : (1,1) string
%                       Enter a short name (alias) for this research product (max. 30 characters; no space).

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add one or several custodians (person or organization) that are responsible for this research product. Note that this custodian will be responsible for all attached research product versions.
        custodian (1,:) openminds.internal.mixedtype.metadatamodel.Custodian ...
            {mustBeListOfUniqueItems(custodian)}

        % Enter a description (abstract) for this research product (max. 2000 characters, incl. spaces; no references). Note that this description should be fitting for all attached research product versions.
        description (1,1) string ...
            {mustBeValidStringLength(description, 0, 2000)}

        % Add one or several developers (person or organization) that contributed to the code implementation of this software.
        developer (1,:) openminds.internal.mixedtype.metadatamodel.Developer ...
            {mustBeListOfUniqueItems(developer)}

        % Add the globally unique and persistent digital identifier of this research product. Note that this digital identifier will be used to reference all attached research product versions.
        digitalIdentifier (1,:) openminds.internal.mixedtype.metadatamodel.DigitalIdentifier ...
            {mustBeSpecifiedLength(digitalIdentifier, 0, 1)}

        % Enter a descriptive full name (title) for this research product.  Note that this full name should be fitting for all attached research product versions.
        fullName (1,1) string

        % Add one or several versions of this (meta)data model.
        hasVersion (1,:) openminds.core.MetaDataModelVersion ...
            {mustBeListOfUniqueItems(hasVersion)}

        % Add the uniform resource locator (URL) to the homepage of this research product.
        homepage (1,:) openminds.core.URL ...
            {mustBeSpecifiedLength(homepage, 0, 1)}

        % Enter the preferred citation text for this research product. Leave blank if citation text can be extracted from the assigned digital identifier.
        howToCite (1,1) string

        % Enter a short name (alias) for this research product (max. 30 characters; no space).
        shortName (1,1) string ...
            {mustBeValidStringLength(shortName, 0, 30)}
    end

    properties (Access = protected)
        Required = ["description", "developer", "fullName", "hasVersion", "shortName"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.ebrains.eu/core/MetaDataModel"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'custodian', ["openminds.core.Organization", "openminds.core.Person"], ...
            'developer', ["openminds.core.Organization", "openminds.core.Person"], ...
            'digitalIdentifier', ["openminds.core.DOI", "openminds.core.SWHID"], ...
            'hasVersion', "openminds.core.MetaDataModelVersion", ...
            'homepage', "openminds.core.URL" ...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = MetaDataModel(varargin)
            obj.assignPVPairs(varargin{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = sprintf('%s', obj.fullName);
        end
    end

end