classdef SlicingAngle < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.core.miscellaneous.QuantitativeValue", ...
            "openminds.core.research.NumericalProperty" ...
        ]
        IS_SCALAR = false
    end
end