function folderNames = SandsInstanceFolders()

    folderNames = [...
        "brainAtlases", ...
        "brainAtlasVersions", ...
        "parcellationEntities", ...
        "parcellationEntityVersions", ...
        "commonCoordinateSpaces", ...
        "commonCoordinateSpaceVersions" ...
        ];
end
