coverage:
   range: "75...100"
   status:
     project:
       default:
         target: 30 # Set the desired coverage target as 40%
         threshold: 2 # Allowable drop in coverage
     patch:
       default:
         # 50% of the changed code must be covered by tests
         threshold: 50
         only_pulls: true
