classdef Device < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.ephys.device.ElectrodeArrayUsage", ...
            "openminds.ephys.device.ElectrodeUsage", ...
            "openminds.ephys.device.PipetteUsage" ...
        ]
        IS_SCALAR = false
    end
end