classdef MajorBaseShape < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.sands.mathematicalshape.Circle", ...
            "openminds.sands.mathematicalshape.CircularSector", ...
            "openminds.sands.mathematicalshape.Ellipse", ...
            "openminds.sands.mathematicalshape.EquilateralTriangle", ...
            "openminds.sands.mathematicalshape.IsoscelesTriangle", ...
            "openminds.sands.mathematicalshape.Kite", ...
            "openminds.sands.mathematicalshape.Parallelogram", ...
            "openminds.sands.mathematicalshape.Rectangle", ...
            "openminds.sands.mathematicalshape.RegularPolygon", ...
            "openminds.sands.mathematicalshape.Rhombus", ...
            "openminds.sands.mathematicalshape.RightTriangle", ...
            "openminds.sands.mathematicalshape.Square", ...
            "openminds.sands.mathematicalshape.Trapezoid", ...
            "openminds.sands.mathematicalshape.Triangle" ...
        ]
        IS_SCALAR = true
    end
end
