classdef DigitalIdentifier < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.core.miscellaneous.GRIDID", ...
            "openminds.core.miscellaneous.RORID" ...
        ]
        IS_SCALAR = false
    end
end