classdef Affiliation < openminds.abstract.Schema
%Affiliation - Structured information about a relationship between two entities, such as a person and their employer.
%
%   PROPERTIES:
%
%   organization : (1,:) <a href="matlab:help openminds.core.actors.Organization" style="font-weight:bold">Organization</a>
%                  Add all organizations (in display order) with which the specified individual is affiliated.
%
%   person       : (1,1) <a href="matlab:help openminds.core.actors.Person" style="font-weight:bold">Person</a>
%                  Add the individual to whom this affiliation belongs.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add all organizations (in display order) with which the specified individual is affiliated.
        organization (1,:) openminds.core.actors.Organization ...
            {mustBeMinLength(organization, 1), mustBeListOfUniqueItems(organization)}

        % Add the individual to whom this affiliation belongs.
        person (1,:) openminds.core.actors.Person ...
            {mustBeScalarOrEmpty(person)}
    end

    properties (Access = protected)
        Required = ["organization", "person"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/Affiliation"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'organization', "openminds.core.actors.Organization", ...
            'person', "openminds.core.actors.Person" ...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = Affiliation(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.core.actors.Affiliation
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = sprintf('%s', obj.memberOf);
        end
    end
end
