classdef NumericalParameter < openminds.abstract.Schema
%NumericalParameter - No description available.
%
%   PROPERTIES:
%
%   name  : (1,1) string
%           Enter a descriptive name for this numerical parameter.
%
%   value : (1,:) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>, <a href="matlab:help openminds.core.miscellaneous.QuantitativeValueRange" style="font-weight:bold">QuantitativeValueRange</a>
%           Add at least one quantitative value for this parameter.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter a descriptive name for this numerical parameter.
        name (1,1) string

        % Add at least one quantitative value for this parameter.
        value (1,:) openminds.internal.mixedtype.numericalparameter.Value
    end

    properties (Access = protected)
        Required = ["name", "value"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.ebrains.eu/core/NumericalParameter"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
        )
        EMBEDDED_PROPERTIES = struct(...
            'value', ["openminds.core.miscellaneous.QuantitativeValue", "openminds.core.miscellaneous.QuantitativeValueRange"] ...
        )
    end

    methods
        function obj = NumericalParameter(varargin)
            obj@openminds.abstract.Schema(varargin{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.name;
        end
    end
end