classdef EphysStimulus < openminds.abstract.Schema
%EphysStimulus - No description available.
%
%   PROPERTIES:
%
%   deliveredBy        : (1,1) <a href="matlab:help openminds.ephys.ElectrodeArrayUsage" style="font-weight:bold">ElectrodeArrayUsage</a>, <a href="matlab:help openminds.ephys.ElectrodeUsage" style="font-weight:bold">ElectrodeUsage</a>, <a href="matlab:help openminds.ephys.PipetteUsage" style="font-weight:bold">PipetteUsage</a>, <a href="matlab:help openminds.specimenprep.SlicingDeviceUsage" style="font-weight:bold">SlicingDeviceUsage</a>
%                        Add the device used to deliver this stimulus.
%
%   description        : (1,1) string
%                        Enter a short text describing this stimulus.
%
%   epoch              : (1,1) <a href="matlab:help openminds.core.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                        Enter the total epoch length of this stimulus.
%
%   generatedBy        : (1,1) <a href="matlab:help openminds.ephys.ElectrodeArrayUsage" style="font-weight:bold">ElectrodeArrayUsage</a>, <a href="matlab:help openminds.ephys.ElectrodeUsage" style="font-weight:bold">ElectrodeUsage</a>, <a href="matlab:help openminds.ephys.PipetteUsage" style="font-weight:bold">PipetteUsage</a>, <a href="matlab:help openminds.specimenprep.SlicingDeviceUsage" style="font-weight:bold">SlicingDeviceUsage</a>
%                        Add the device used to generate this stimulus.
%
%   internalIdentifier : (1,1) string
%                        Enter the identifier (or label) of this stimulus that is used within the corresponding data files to identify this stimulus.
%
%   lookupLabel        : (1,1) string
%                        Enter a lookup label for this stimulus that may help you to find this instance more easily.
%
%   specification      : (1,:) <a href="matlab:help openminds.core.Configuration" style="font-weight:bold">Configuration</a>, <a href="matlab:help openminds.core.File" style="font-weight:bold">File</a>, <a href="matlab:help openminds.core.FileBundle" style="font-weight:bold">FileBundle</a>, <a href="matlab:help openminds.core.PropertyValueList" style="font-weight:bold">PropertyValueList</a>
%                        Add the specification information for this stimulus.
%
%   type               : (1,1) <a href="matlab:help openminds.controlledterms.ElectricalStimulusType" style="font-weight:bold">ElectricalStimulusType</a>
%                        Add the type that describe this electrical stimulus.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add the device used to deliver this stimulus.
        deliveredBy (1,:) openminds.internal.mixedtype.ephysstimulus.DeliveredBy ...
            {mustBeSpecifiedLength(deliveredBy, 0, 1)}

        % Enter a short text describing this stimulus.
        description (1,1) string

        % Enter the total epoch length of this stimulus.
        epoch (1,:) openminds.core.QuantitativeValue ...
            {mustBeSpecifiedLength(epoch, 0, 1)}

        % Add the device used to generate this stimulus.
        generatedBy (1,:) openminds.internal.mixedtype.ephysstimulus.GeneratedBy ...
            {mustBeSpecifiedLength(generatedBy, 0, 1)}

        % Enter the identifier (or label) of this stimulus that is used within the corresponding data files to identify this stimulus.
        internalIdentifier (1,1) string

        % Enter a lookup label for this stimulus that may help you to find this instance more easily.
        lookupLabel (1,1) string

        % Add the specification information for this stimulus.
        specification (1,:) openminds.internal.mixedtype.ephysstimulus.Specification ...
            {mustBeListOfUniqueItems(specification)}

        % Add the type that describe this electrical stimulus.
        type (1,:) openminds.controlledterms.ElectricalStimulusType ...
            {mustBeSpecifiedLength(type, 0, 1)}
    end

    properties (Access = protected)
        Required = ["internalIdentifier"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.ebrains.eu/stimulation/EphysStimulus"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'deliveredBy', ["openminds.ephys.ElectrodeArrayUsage", "openminds.ephys.ElectrodeUsage", "openminds.ephys.PipetteUsage", "openminds.specimenprep.SlicingDeviceUsage"], ...
            'generatedBy', ["openminds.ephys.ElectrodeArrayUsage", "openminds.ephys.ElectrodeUsage", "openminds.ephys.PipetteUsage", "openminds.specimenprep.SlicingDeviceUsage"], ...
            'specification', ["openminds.core.Configuration", "openminds.core.File", "openminds.core.FileBundle", "openminds.core.PropertyValueList"], ...
            'type', "openminds.controlledterms.ElectricalStimulusType" ...
        )
        EMBEDDED_PROPERTIES = struct(...
            'epoch', "openminds.core.QuantitativeValue" ...
        )
    end

    methods
        function obj = EphysStimulus(varargin)
            obj@openminds.abstract.Schema(varargin{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.lookupLabel;
        end
    end

end