classdef StudyTarget < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.controlledterms.BiologicalSex", ...
            "openminds.controlledterms.CellType", ...
            "openminds.controlledterms.Disease", ...
            "openminds.controlledterms.DiseaseModel", ...
            "openminds.controlledterms.Handedness", ...
            "openminds.controlledterms.Organ", ...
            "openminds.controlledterms.Phenotype", ...
            "openminds.controlledterms.Species", ...
            "openminds.controlledterms.Strain", ...
            "openminds.controlledterms.TermSuggestion", ...
            "openminds.sands.atlas.ParcellationEntity", ...
            "openminds.sands.nonatlas.CustomAnatomicalEntity" ...
        ]
        IS_SCALAR = false
    end
end