classdef Scope < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.controlledterms.AnalysisTechnique", ...
            "openminds.controlledterms.ContributionType", ...
            "openminds.controlledterms.DataType", ...
            "openminds.controlledterms.ExperimentalApproach", ...
            "openminds.controlledterms.OperationalApproach", ...
            "openminds.controlledterms.SoftwareApplicationCategory", ...
            "openminds.controlledterms.SoftwareFeature", ...
            "openminds.controlledterms.Technique", ...
            "openminds.controlledterms.TermSuggestion" ...
        ]
        IS_SCALAR = false
    end
end
