classdef Ellipsoid < openminds.abstract.Schema
%Ellipsoid - No description available.
%
%   PROPERTIES:
%
%   intermediateDiameter : (1,1) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                          Enter the intermediate diameter of this ellipsoid.
%
%   majorDiameter        : (1,1) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                          Enter the major diameter of this ellipsoid.
%
%   minorDiameter        : (1,1) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                          Enter the minor diameter of this ellipsoid.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter the intermediate diameter of this ellipsoid.
        intermediateDiameter (1,:) openminds.core.miscellaneous.QuantitativeValue ...
            {mustBeScalarOrEmpty(intermediateDiameter)}

        % Enter the major diameter of this ellipsoid.
        majorDiameter (1,:) openminds.core.miscellaneous.QuantitativeValue ...
            {mustBeScalarOrEmpty(majorDiameter)}

        % Enter the minor diameter of this ellipsoid.
        minorDiameter (1,:) openminds.core.miscellaneous.QuantitativeValue ...
            {mustBeScalarOrEmpty(minorDiameter)}
    end

    properties (Access = protected)
        Required = ["intermediateDiameter", "majorDiameter", "minorDiameter"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/Ellipsoid"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
        )
        EMBEDDED_PROPERTIES = struct(...
            'intermediateDiameter', "openminds.core.miscellaneous.QuantitativeValue", ...
            'majorDiameter', "openminds.core.miscellaneous.QuantitativeValue", ...
            'minorDiameter', "openminds.core.miscellaneous.QuantitativeValue" ...
        )
    end

    methods
        function obj = Ellipsoid(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.sands.mathematicalshape.Ellipsoid
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.createLabelForMissingLabelDefinition();
        end
    end
end
