classdef Kite < openminds.abstract.Schema
%Kite - No description available.
%
%   PROPERTIES:
%
%   legLengths             : (1,:) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                            Enter the two common leg lengths (for the shorter and longer leg pairs) of this kite.
%
%   symmetryDiagonalLength : (1,1) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                            Enter the length of the symmetry diagonal of this kite.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter the two common leg lengths (for the shorter and longer leg pairs) of this kite.
        legLengths (1,:) openminds.core.miscellaneous.QuantitativeValue ...
            {mustBeSpecifiedLength(legLengths, 2, 2)}

        % Enter the length of the symmetry diagonal of this kite.
        symmetryDiagonalLength (1,:) openminds.core.miscellaneous.QuantitativeValue ...
            {mustBeSpecifiedLength(symmetryDiagonalLength, 0, 1)}
    end

    properties (Access = protected)
        Required = ["legLengths", "symmetryDiagonalLength"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/Kite"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
        )
        EMBEDDED_PROPERTIES = struct(...
            'legLengths', "openminds.core.miscellaneous.QuantitativeValue", ...
            'symmetryDiagonalLength', "openminds.core.miscellaneous.QuantitativeValue" ...
        )
    end

    methods
        function obj = Kite(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.sands.mathematicalshape.Kite
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.createLabelForMissingLabelDefinition();
        end
    end
end
