classdef RegularPolygon < openminds.abstract.Schema
%RegularPolygon - No description available.
%
%   PROPERTIES:
%
%   circumradius  : (1,1) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                   Enter the common distance from the center to a vertex of this regular polygon.
%
%   numberOfSides : (1,1) int64
%                   Enter the number of sides of this regular polygon.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter the common distance from the center to a vertex of this regular polygon.
        circumradius (1,:) openminds.core.miscellaneous.QuantitativeValue ...
            {mustBeScalarOrEmpty(circumradius)}

        % Enter the number of sides of this regular polygon.
        numberOfSides (1,:) int64 ...
            {mustBeScalarOrEmpty(numberOfSides), mustBeInteger(numberOfSides), mustBeGreaterThanOrEqual(numberOfSides, 3)}
    end

    properties (Access = protected)
        Required = ["circumradius", "numberOfSides"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/RegularPolygon"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
        )
        EMBEDDED_PROPERTIES = struct(...
            'circumradius', "openminds.core.miscellaneous.QuantitativeValue" ...
        )
    end

    methods
        function obj = RegularPolygon(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.sands.mathematicalshape.RegularPolygon
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.createLabelForMissingLabelDefinition();
        end
    end
end
