classdef FulfilledBy < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.core.data.File", ...
            "openminds.core.miscellaneous.WebResource", ...
            "openminds.core.products.InterfaceVersion", ...
            "openminds.core.products.SoftwareVersion", ...
            "openminds.core.research.Configuration" ...
        ]
        IS_SCALAR = true
    end
end
