classdef MRICoil < openminds.abstract.Schema
%MRICoil - No description available.
%
%   PROPERTIES:
%
%   contribution             : (1,:) <a href="matlab:help openminds.core.actors.Organization" style="font-weight:bold">Organization</a>, <a href="matlab:help openminds.core.actors.Person" style="font-weight:bold">Person</a>
%                              Add all relevant contributions (e.g., ownership, maintenance) for this device.
%
%   description              : (1,1) string
%                              Enter a short description of the device. Describe the device itself for a custom-built device or note device-specific peculiarities or deviations from the standard product for a manufacturer-defined device.
%
%   elementCount             : (1,1) int64
%                              Enter the total number of coil elements.
%
%   intendedMountingLocation : (1,1) <a href="matlab:help openminds.controlledterms.ExternalBodyRegion" style="font-weight:bold">ExternalBodyRegion</a>
%                              Add the mounting location intended by the manufacturer (e.g., head, neck, knee).
%
%   internalIdentifier       : (1,1) string
%                              Enter the identifier (or label) of this device that is used by the owner to identify or reference this device.
%
%   mountingType             : (1,1) <a href="matlab:help openminds.controlledterms.DeviceMountingType" style="font-weight:bold">DeviceMountingType</a>
%                              Add the coil mounting type (e.g., built-in, external, interventional, wearable).
%
%   name                     : (1,1) string
%                              Enter a descriptive name for this device, preferably defined by the owner.
%
%   serialNumber             : (1,1) string
%                              Enter the serial number of this device.
%
%   type                     : (1,1) <a href="matlab:help openminds.controlledterms.DeviceType" style="font-weight:bold">DeviceType</a>, <a href="matlab:help openminds.core.products.HardwareProduct" style="font-weight:bold">HardwareProduct</a>
%                              Add the device classification reference. Identify a device type for a custom-built device, or a hardware product for a device corresponding to a manufacturer-defined product model.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add all relevant contributions (e.g., ownership, maintenance) for this device.
        contribution (1,:) openminds.internal.mixedtype.mricoil.Contribution ...
            {mustBeMinLength(contribution, 1), mustBeListOfUniqueItems(contribution)}

        % Enter a short description of the device. Describe the device itself for a custom-built device or note device-specific peculiarities or deviations from the standard product for a manufacturer-defined device.
        description (1,1) string

        % Enter the total number of coil elements.
        elementCount (1,:) int64 ...
            {mustBeScalarOrEmpty(elementCount), mustBeInteger(elementCount), mustBeGreaterThanOrEqual(elementCount, 1)}

        % Add the mounting location intended by the manufacturer (e.g., head, neck, knee).
        intendedMountingLocation (1,:) openminds.controlledterms.ExternalBodyRegion ...
            {mustBeScalarOrEmpty(intendedMountingLocation)}

        % Enter the identifier (or label) of this device that is used by the owner to identify or reference this device.
        internalIdentifier (1,1) string

        % Add the coil mounting type (e.g., built-in, external, interventional, wearable).
        mountingType (1,:) openminds.controlledterms.DeviceMountingType ...
            {mustBeScalarOrEmpty(mountingType)}

        % Enter a descriptive name for this device, preferably defined by the owner.
        name (1,1) string

        % Enter the serial number of this device.
        serialNumber (1,1) string

        % Add the device classification reference. Identify a device type for a custom-built device, or a hardware product for a device corresponding to a manufacturer-defined product model.
        type (1,:) openminds.internal.mixedtype.mricoil.Type ...
            {mustBeScalarOrEmpty(type)}
    end

    properties (Access = protected)
        Required = ["contribution", "elementCount", "mountingType", "name", "type"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/MRICoil"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'contribution', ["openminds.core.actors.Organization", "openminds.core.actors.Person"], ...
            'intendedMountingLocation', "openminds.controlledterms.ExternalBodyRegion", ...
            'mountingType', "openminds.controlledterms.DeviceMountingType", ...
            'type', ["openminds.controlledterms.DeviceType", "openminds.core.products.HardwareProduct"] ...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = MRICoil(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.neuroimaging.device.MRICoil
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.name;
        end
    end
end
