classdef MRICoilUsage < openminds.abstract.Schema
%MRICoilUsage - No description available.
%
%   PROPERTIES:
%
%   activeElement        : (1,:) string
%                          Only applicable to radiofrequency (RF) coils! Enter the active coil element identifier(s) corresponding to the transmitting and/or receiving elements that were electrically active during this acquisition; the number of identifiers typically matches the number of physical elements in the selected RF coil and may be fewer if some elements were disabled.
%
%   device               : (1,1) <a href="matlab:help openminds.neuroimaging.device.MRICoil" style="font-weight:bold">MRICoil</a>
%                          Add the MRI Coil used.
%
%   lookupLabel          : (1,1) string
%                          Enter a lookup label for this device usage that may help you to find this instance more easily.
%
%   metadataLocation     : (1,:) <a href="matlab:help openminds.core.data.File" style="font-weight:bold">File</a>, <a href="matlab:help openminds.core.data.FileBundle" style="font-weight:bold">FileBundle</a>
%                          Add all files or file bundles containing additional information about the usage of this device.
%
%   mountingLocation     : (1,1) <a href="matlab:help openminds.controlledterms.ExternalBodyRegion" style="font-weight:bold">ExternalBodyRegion</a>
%                          Add the anatomical mounting location of the coil, indicating where the coil was positioned on or around the subject (for example, head, neck, knee, or torso). This information is typically applicable to radiofrequency (RF) coils and may be omitted for gradient or shim systems.
%
%   signalDirectionality : (1,1) <a href="matlab:help openminds.controlledterms.SignalDirectionality" style="font-weight:bold">SignalDirectionality</a>
%                          Add the signal directionality of the coil, indicating whether it was used for signal transmission, reception, or both. This information is typically defined in the system configuration and can be retrieved from the DICOM header or scanner hardware metadata.
%
%   usedSpecimen         : (1,1) <a href="matlab:help openminds.core.research.SubjectState" style="font-weight:bold">SubjectState</a>, <a href="matlab:help openminds.core.research.TissueSampleState" style="font-weight:bold">TissueSampleState</a>
%                          Add the state of the tissue sample or subject that this device was used on.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Only applicable to radiofrequency (RF) coils! Enter the active coil element identifier(s) corresponding to the transmitting and/or receiving elements that were electrically active during this acquisition; the number of identifiers typically matches the number of physical elements in the selected RF coil and may be fewer if some elements were disabled.
        activeElement (1,:) string ...
            {mustBeMinLength(activeElement, 1), mustBeListOfUniqueItems(activeElement)}

        % Add the MRI Coil used.
        device (1,:) openminds.neuroimaging.device.MRICoil ...
            {mustBeScalarOrEmpty(device)}

        % Enter a lookup label for this device usage that may help you to find this instance more easily.
        lookupLabel (1,1) string

        % Add all files or file bundles containing additional information about the usage of this device.
        metadataLocation (1,:) openminds.internal.mixedtype.mricoilusage.MetadataLocation ...
            {mustBeMinLength(metadataLocation, 1), mustBeListOfUniqueItems(metadataLocation)}

        % Add the anatomical mounting location of the coil, indicating where the coil was positioned on or around the subject (for example, head, neck, knee, or torso). This information is typically applicable to radiofrequency (RF) coils and may be omitted for gradient or shim systems.
        mountingLocation (1,:) openminds.controlledterms.ExternalBodyRegion ...
            {mustBeScalarOrEmpty(mountingLocation)}

        % Add the signal directionality of the coil, indicating whether it was used for signal transmission, reception, or both. This information is typically defined in the system configuration and can be retrieved from the DICOM header or scanner hardware metadata.
        signalDirectionality (1,:) openminds.controlledterms.SignalDirectionality ...
            {mustBeScalarOrEmpty(signalDirectionality)}

        % Add the state of the tissue sample or subject that this device was used on.
        usedSpecimen (1,:) openminds.internal.mixedtype.mricoilusage.UsedSpecimen ...
            {mustBeScalarOrEmpty(usedSpecimen)}
    end

    properties (Access = protected)
        Required = ["device", "signalDirectionality"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/MRICoilUsage"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'device', "openminds.neuroimaging.device.MRICoil", ...
            'metadataLocation', ["openminds.core.data.File", "openminds.core.data.FileBundle"], ...
            'mountingLocation', "openminds.controlledterms.ExternalBodyRegion", ...
            'signalDirectionality', "openminds.controlledterms.SignalDirectionality", ...
            'usedSpecimen', ["openminds.core.research.SubjectState", "openminds.core.research.TissueSampleState"] ...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = MRICoilUsage(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.neuroimaging.device.MRICoilUsage
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.lookupLabel;
        end
    end
end
