classdef Project < openminds.abstract.Schema
%Project - Structured information on a research project.
%
%   PROPERTIES:
%
%   coordinator         : (1,:) <a href="matlab:help openminds.core.actors.Organization" style="font-weight:bold">Organization</a>, <a href="matlab:help openminds.core.actors.Person" style="font-weight:bold">Person</a>
%                         Add one or several project coordinators (person or organization).
%
%   description         : (1,1) string
%                         Enter a description of this project.
%
%   fullName            : (1,1) string
%                         Enter a descriptive full name (title) for this project.
%
%   hasResearchProducts : (1,:) <a href="matlab:help openminds.core.products.Dataset" style="font-weight:bold">Dataset</a>, <a href="matlab:help openminds.core.products.DatasetVersion" style="font-weight:bold">DatasetVersion</a>, <a href="matlab:help openminds.core.products.MetaDataModel" style="font-weight:bold">MetaDataModel</a>, <a href="matlab:help openminds.core.products.MetaDataModelVersion" style="font-weight:bold">MetaDataModelVersion</a>, <a href="matlab:help openminds.core.products.Model" style="font-weight:bold">Model</a>, <a href="matlab:help openminds.core.products.ModelVersion" style="font-weight:bold">ModelVersion</a>, <a href="matlab:help openminds.core.products.Software" style="font-weight:bold">Software</a>, <a href="matlab:help openminds.core.products.SoftwareVersion" style="font-weight:bold">SoftwareVersion</a>
%                         Add all research products or research product versions that are part of this project.
%
%   homepage            : (1,1) <a href="matlab:help openminds.core.miscellaneous.URL" style="font-weight:bold">URL</a>
%                         Add the uniform resource locator (URL) to the homepage of this project.
%
%   shortName           : (1,1) string
%                         Enter a short name (alias) for this project.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add one or several project coordinators (person or organization).
        coordinator (1,:) openminds.internal.mixedtype.project.Coordinator ...
            {mustBeListOfUniqueItems(coordinator)}

        % Enter a description of this project.
        description (1,1) string

        % Enter a descriptive full name (title) for this project.
        fullName (1,1) string

        % Add all research products or research product versions that are part of this project.
        hasResearchProducts (1,:) openminds.internal.mixedtype.project.HasResearchProducts ...
            {mustBeListOfUniqueItems(hasResearchProducts)}

        % Add the uniform resource locator (URL) to the homepage of this project.
        homepage (1,:) openminds.core.miscellaneous.URL ...
            {mustBeSpecifiedLength(homepage, 0, 1)}

        % Enter a short name (alias) for this project.
        shortName (1,1) string
    end

    properties (Access = protected)
        Required = ["description", "fullName", "hasResearchProducts", "shortName"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.ebrains.eu/core/Project"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'coordinator', ["openminds.core.actors.Organization", "openminds.core.actors.Person"], ...
            'hasResearchProducts', ["openminds.core.products.Dataset", "openminds.core.products.DatasetVersion", "openminds.core.products.MetaDataModel", "openminds.core.products.MetaDataModelVersion", "openminds.core.products.Model", "openminds.core.products.ModelVersion", "openminds.core.products.Software", "openminds.core.products.SoftwareVersion"], ...
            'homepage', "openminds.core.miscellaneous.URL" ...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = Project(structInstance, propValues)
            arguments
                structInstance (1,:) struct = struct.empty
                propValues.?openminds.core.products.Project
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = sprintf('%s', obj.fullName);
        end
    end
end
