"""Tests for the readme and contents files written beside the generated classes.

These describe generated content, so they are generated too. They were kept by
hand before, and were forgotten whenever a model version was added.
"""

import glob
import json
import os
import re
import shutil
import tempfile
import unittest

from pipeline.utils import initialise_jinja_templates, save_overlay_files

VERSION = "v9.0"


class SchemaLoaderStub:
    """Stands in for SchemaLoader, which reads a fixed _sources location."""

    def __init__(self, schemas_sources):
        self.schemas_sources = schemas_sources

    def find_schemas(self, version):
        return glob.glob(
            os.path.join(self.schemas_sources, version, "**", "*.schema.omi.json"),
            recursive=True,
        )


class OverlayFileTestCase(unittest.TestCase):

    def setUp(self):
        self.root = tempfile.mkdtemp()
        self.addCleanup(shutil.rmtree, self.root, ignore_errors=True)

        self.output_directory = tempfile.mkdtemp()
        self.addCleanup(shutil.rmtree, self.output_directory, ignore_errors=True)
        self.addCleanup(os.chdir, os.getcwd())

        self.loader = SchemaLoaderStub(self.root)

    def write_schema(self, module, short_name):
        folder = os.path.join(self.root, VERSION, module)
        os.makedirs(folder, exist_ok=True)
        path = os.path.join(folder, f"{short_name}.schema.omi.json")
        with open(path, "w", encoding="utf-8") as schema_file:
            json.dump({"_type": f"https://openminds.ebrains.eu/{module}/{short_name}",
                       "properties": {}, "required": []}, schema_file)

    def generate(self):
        os.chdir(self.output_directory)
        save_overlay_files(VERSION, self.loader, initialise_jinja_templates())

    def read(self, *path_parts):
        with open(os.path.join(self.output_directory, "target", VERSION, *path_parts),
                  encoding="utf-8") as generated_file:
            return generated_file.read()


class ContentsFileTest(OverlayFileTestCase):

    def test_lists_every_module_the_version_defines(self):
        self.write_schema("core", "person")
        self.write_schema("controlledTerms", "ageCategory")
        self.write_schema("SANDS", "annotation")
        self.generate()

        contents = self.read("types", "+openminds", "Contents.m")
        listed = re.findall(r"^%\s+(\S+) - openminds\.(\S+) is a module\.$",
                            contents, re.M)
        self.assertEqual([name for name, _ in listed],
                         ["controlledterms", "core", "sands"])
        # The name is written the same way on both sides of the dash
        for name, qualified in listed:
            self.assertEqual(name, qualified)

    def test_names_the_model_version(self):
        self.write_schema("core", "person")
        self.generate()
        self.assertIn(f"% openMINDS metadata types - {VERSION}",
                      self.read("types", "+openminds", "Contents.m"))

    def test_module_names_are_right_aligned_on_the_dash(self):
        self.write_schema("core", "person")
        self.write_schema("controlledTerms", "ageCategory")
        self.generate()

        lines = [line for line in self.read("types", "+openminds", "Contents.m").splitlines()
                 if " - openminds." in line]
        self.assertEqual(len({line.index(" - openminds.") for line in lines}), 1)

    def test_a_module_appears_once_however_many_schemas_it_has(self):
        self.write_schema("core", "person")
        self.write_schema("core", "subject")
        self.generate()
        self.assertEqual(
            self.read("types", "+openminds", "Contents.m").count("is a module."), 1)


class ReadmeFileTest(OverlayFileTestCase):

    def setUp(self):
        super().setUp()
        self.write_schema("core", "person")

    def test_every_generated_folder_gets_one(self):
        self.generate()
        for artifact_type in ("types", "mixedtypes", "enumerations"):
            self.assertTrue(
                os.path.isfile(os.path.join(
                    self.output_directory, "target", VERSION, artifact_type, "README.md")),
                f"no readme for {artifact_type}")

    def test_names_its_folder_and_the_model_version(self):
        self.generate()
        self.assertTrue(self.read("types", "README.md").startswith(f"## Types ({VERSION})"))
        self.assertTrue(
            self.read("mixedtypes", "README.md").startswith(f"## Mixed types ({VERSION})"))
        self.assertTrue(
            self.read("enumerations", "README.md").startswith(f"## Enumerations ({VERSION})"))

    def test_says_the_content_is_generated(self):
        self.generate()
        for artifact_type in ("types", "mixedtypes", "enumerations"):
            self.assertIn("autogenerated by the openMINDS MATLAB pipeline",
                          self.read(artifact_type, "README.md"))

    def test_the_types_readme_names_the_version_in_its_description(self):
        # The types readme is the one whose body varies by version.
        self.generate()
        self.assertIn(f"the {VERSION} version", self.read("types", "README.md"))


if __name__ == "__main__":
    unittest.main()
