classdef Protocol < openminds.abstract.Schema
%Protocol - Structured information on a research project.
%
%   PROPERTIES:
%
%   behavioralTask : (1,:) <a href="matlab:help openminds.controlledterms.BehavioralTask" style="font-weight:bold">BehavioralTask</a>
%                    Add all behavioral tasks that were executed as part of this protocol.
%
%   description    : (1,1) string
%                    Enter a description of this protocol.
%
%   name           : (1,1) string
%                    Enter a descriptive name for this protocol.
%
%   studyTarget    : (1,:) <a href="matlab:help openminds.controlledterm.BiologicalSex" style="font-weight:bold">BiologicalSex</a>, <a href="matlab:help openminds.controlledterm.Disease" style="font-weight:bold">Disease</a>, <a href="matlab:help openminds.controlledterm.Genotype" style="font-weight:bold">Genotype</a>, <a href="matlab:help openminds.controlledterm.Phenotype" style="font-weight:bold">Phenotype</a>, <a href="matlab:help openminds.controlledterm.Species" style="font-weight:bold">Species</a>, <a href="matlab:help openminds.controlledterm.TermSuggestion" style="font-weight:bold">TermSuggestion</a>, <a href="matlab:help openminds.sands.AnatomicalEntity" style="font-weight:bold">AnatomicalEntity</a>
%                    Add all study targets of this model version.
%
%   technique      : (1,:) <a href="matlab:help openminds.controlledterms.Technique" style="font-weight:bold">Technique</a>
%                    Add all techniques that were used in this protocol.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add all behavioral tasks that were executed as part of this protocol.
        behavioralTask (1,:) openminds.controlledterms.BehavioralTask ...
            {mustBeListOfUniqueItems(behavioralTask)}

        % Enter a description of this protocol.
        description (1,1) string

        % Enter a descriptive name for this protocol.
        name (1,1) string

        % Add all study targets of this model version.
        studyTarget (1,:) openminds.internal.mixedtype.protocol.StudyTarget ...
            {mustBeListOfUniqueItems(studyTarget)}

        % Add all techniques that were used in this protocol.
        technique (1,:) openminds.controlledterms.Technique ...
            {mustBeListOfUniqueItems(technique)}
    end

    properties (Access = protected)
        Required = ["description", "name", "technique"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.ebrains.eu/core/Protocol"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'behavioralTask', "openminds.controlledterms.BehavioralTask", ...
            'studyTarget', ["openminds.controlledterm.BiologicalSex", "openminds.controlledterm.Disease", "openminds.controlledterm.Genotype", "openminds.controlledterm.Phenotype", "openminds.controlledterm.Species", "openminds.controlledterm.TermSuggestion", "openminds.sands.AnatomicalEntity"], ...
            'technique', "openminds.controlledterms.Technique" ...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = Protocol(varargin)
            obj@openminds.abstract.Schema(varargin{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = sprintf('%s', obj.name);
        end
    end

end