classdef RelatedPublication < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.core.digitalidentifier.DOI", ...
            "openminds.core.digitalidentifier.HANDLE", ...
            "openminds.core.digitalidentifier.ISBN", ...
            "openminds.core.digitalidentifier.ISSN", ...
            "openminds.publications.Book", ...
            "openminds.publications.Chapter", ...
            "openminds.publications.ScholarlyArticle" ...
        ]
        IS_SCALAR = false
    end
end