classdef DeployedInterface < openminds.abstract.Schema
%DeployedInterface - No description available.
%
%   PROPERTIES:
%
%   accessibility : (1,1) <a href="matlab:help openminds.core.miscellaneous.Accessibility" style="font-weight:bold">Accessibility</a>
%                   Add the accessibility of this deployed interface.
%
%   entryPoint    : (1,1) <a href="matlab:help openminds.core.miscellaneous.WebResource" style="font-weight:bold">WebResource</a>
%                   Add the URL that serves as the entry point to this deployed interface.
%
%   interface     : (1,1) <a href="matlab:help openminds.core.products.InterfaceVersion" style="font-weight:bold">InterfaceVersion</a>
%                   Enter the interface version that is deployed.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add the accessibility of this deployed interface.
        accessibility (1,:) openminds.core.miscellaneous.Accessibility ...
            {mustBeSpecifiedLength(accessibility, 0, 1)}

        % Add the URL that serves as the entry point to this deployed interface.
        entryPoint (1,:) openminds.core.miscellaneous.WebResource ...
            {mustBeSpecifiedLength(entryPoint, 0, 1)}

        % Enter the interface version that is deployed.
        interface (1,:) openminds.core.products.InterfaceVersion ...
            {mustBeSpecifiedLength(interface, 0, 1)}
    end

    properties (Access = protected)
        Required = ["accessibility", "entryPoint", "interface"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/DeployedInterface"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'accessibility', "openminds.core.miscellaneous.Accessibility", ...
            'entryPoint', "openminds.core.miscellaneous.WebResource", ...
            'interface', "openminds.core.products.InterfaceVersion" ...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = DeployedInterface(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.computation.DeployedInterface
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.createLabelForMissingLabelDefinition();
        end
    end
end
