classdef Species < openminds.internal.abstract.LinkedCategory
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.controlledterms.Species", ...
            "openminds.core.research.Strain" ...
        ]
        IS_SCALAR = false
    end
end