classdef Technique < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.controlledterms.AnalysisTechnique", ...
            "openminds.controlledterms.MRIPulseSequence", ...
            "openminds.controlledterms.MRIWeighting", ...
            "openminds.controlledterms.StimulationApproach", ...
            "openminds.controlledterms.StimulationTechnique", ...
            "openminds.controlledterms.Technique" ...
        ]
        IS_SCALAR = false
    end
end