classdef DeliveredBy < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.ephys.device.ElectrodeArrayUsage", ...
            "openminds.ephys.device.ElectrodeUsage", ...
            "openminds.ephys.device.PipetteUsage", ...
            "openminds.neuroimaging.device.MRICoilUsage", ...
            "openminds.neuroimaging.device.MRIScannerUsage", ...
            "openminds.specimenprep.device.SlicingDeviceUsage" ...
        ]
        IS_SCALAR = true
    end
end
