classdef GridVolumeSequence < openminds.abstract.Schema
%GridVolumeSequence - No description available.
%
%   PROPERTIES:
%
%   additionalRemarks         : (1,1) string
%                               Enter any additional remarks concerning this grid volume sequence.
%
%   coordinateFramework       : (1,1) <a href="matlab:help openminds.sands.atlas.CommonCoordinateFrameworkVersion" style="font-weight:bold">CommonCoordinateFrameworkVersion</a>, <a href="matlab:help openminds.sands.nonatlas.CustomCoordinateFramework" style="font-weight:bold">CustomCoordinateFramework</a>
%                               Add the coordinate space in which this grid volume sequence exists.
%
%   dataLocation              : (1,1) <a href="matlab:help openminds.core.data.File" style="font-weight:bold">File</a>, <a href="matlab:help openminds.core.data.FileBundle" style="font-weight:bold">FileBundle</a>
%                               Add a reference to the file to which this grid volume sequence information applies. If the information applies uniformly to a grid volume sequence file series, a reference to the corresponding file bundle may be provided instead.
%
%   dimension                 : (1,:) int64
%                               Enter the dimension of grid volumes.
%
%   name                      : (1,1) string
%                               Enter a descriptive name of this grid volume sequence preferably matching the filename.
%
%   numberOfPlanes            : (1,1) int64
%                               Enter the number of planes in this grid volume sequence.
%
%   numberOfVolumes           : (1,1) int64
%                               Enter the total number of grid volumes in this sequence (at least two).
%
%   obtainedWith              : (1,1) <a href="matlab:help openminds.ephys.device.ElectrodeArrayUsage" style="font-weight:bold">ElectrodeArrayUsage</a>, <a href="matlab:help openminds.ephys.device.ElectrodeUsage" style="font-weight:bold">ElectrodeUsage</a>, <a href="matlab:help openminds.ephys.device.PipetteUsage" style="font-weight:bold">PipetteUsage</a>, <a href="matlab:help openminds.neuroimaging.device.MRICoilUsage" style="font-weight:bold">MRICoilUsage</a>, <a href="matlab:help openminds.neuroimaging.device.MRIScannerUsage" style="font-weight:bold">MRIScannerUsage</a>, <a href="matlab:help openminds.specimenprep.device.SlicingDeviceUsage" style="font-weight:bold">SlicingDeviceUsage</a>
%                               Add the used device for obtaining this grid volume sequence.
%
%   temporalSamplingFrequency : (1,1) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                               Enter the rate at which consecutive grid volume are captured in a sequence, preferably measured in Hertz (Hz).
%
%   voxelSize                 : (1,:) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                               Enter the physical voxel size for this grid volume sequence (in x,y,z order).

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter any additional remarks concerning this grid volume sequence.
        additionalRemarks (1,1) string

        % Add the coordinate space in which this grid volume sequence exists.
        coordinateFramework (1,:) openminds.internal.mixedtype.gridvolumesequence.CoordinateFramework ...
            {mustBeSpecifiedLength(coordinateFramework, 0, 1)}

        % Add a reference to the file to which this grid volume sequence information applies. If the information applies uniformly to a grid volume sequence file series, a reference to the corresponding file bundle may be provided instead.
        dataLocation (1,:) openminds.internal.mixedtype.gridvolumesequence.DataLocation ...
            {mustBeSpecifiedLength(dataLocation, 0, 1)}

        % Enter the dimension of grid volumes.
        dimension (1,:) int64 ...
            {mustBeSpecifiedLength(dimension, 3, 3)}

        % Enter a descriptive name of this grid volume sequence preferably matching the filename.
        name (1,1) string

        % Enter the number of planes in this grid volume sequence.
        numberOfPlanes (1,:) int64 ...
            {mustBeSpecifiedLength(numberOfPlanes, 0, 1)}

        % Enter the total number of grid volumes in this sequence (at least two).
        numberOfVolumes (1,:) int64 ...
            {mustBeSpecifiedLength(numberOfVolumes, 0, 1), mustBeInteger(numberOfVolumes), mustBeGreaterThanOrEqual(numberOfVolumes, 2)}

        % Add the used device for obtaining this grid volume sequence.
        obtainedWith (1,:) openminds.internal.mixedtype.gridvolumesequence.ObtainedWith ...
            {mustBeSpecifiedLength(obtainedWith, 0, 1)}

        % Enter the rate at which consecutive grid volume are captured in a sequence, preferably measured in Hertz (Hz).
        temporalSamplingFrequency (1,:) openminds.core.miscellaneous.QuantitativeValue ...
            {mustBeSpecifiedLength(temporalSamplingFrequency, 0, 1)}

        % Enter the physical voxel size for this grid volume sequence (in x,y,z order).
        voxelSize (1,:) openminds.core.miscellaneous.QuantitativeValue ...
            {mustBeSpecifiedLength(voxelSize, 3, 3)}
    end

    properties (Access = protected)
        Required = ["dataLocation", "dimension", "temporalSamplingFrequency", "voxelSize"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/GridVolumeSequence"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'coordinateFramework', ["openminds.sands.atlas.CommonCoordinateFrameworkVersion", "openminds.sands.nonatlas.CustomCoordinateFramework"], ...
            'dataLocation', ["openminds.core.data.File", "openminds.core.data.FileBundle"], ...
            'obtainedWith', ["openminds.ephys.device.ElectrodeArrayUsage", "openminds.ephys.device.ElectrodeUsage", "openminds.ephys.device.PipetteUsage", "openminds.neuroimaging.device.MRICoilUsage", "openminds.neuroimaging.device.MRIScannerUsage", "openminds.specimenprep.device.SlicingDeviceUsage"] ...
        )
        EMBEDDED_PROPERTIES = struct(...
            'temporalSamplingFrequency', "openminds.core.miscellaneous.QuantitativeValue", ...
            'voxelSize', "openminds.core.miscellaneous.QuantitativeValue" ...
        )
    end

    methods
        function obj = GridVolumeSequence(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.core.data.GridVolumeSequence
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.name;
        end
    end
end
