classdef GridVolume < openminds.abstract.Schema
%GridVolume - No description available.
%
%   PROPERTIES:
%
%   additionalRemarks   : (1,1) string
%                         Enter any additional remarks concerning this grid volume.
%
%   coordinateFramework : (1,1) <a href="matlab:help openminds.sands.atlas.CommonCoordinateFrameworkVersion" style="font-weight:bold">CommonCoordinateFrameworkVersion</a>, <a href="matlab:help openminds.sands.nonatlas.CustomCoordinateFramework" style="font-weight:bold">CustomCoordinateFramework</a>
%                         Add the coordinate space in which this grid volume exists.
%
%   dataLocation        : (1,1) <a href="matlab:help openminds.core.data.File" style="font-weight:bold">File</a>, <a href="matlab:help openminds.core.data.FileBundle" style="font-weight:bold">FileBundle</a>
%                         Add a reference to the file to which this grid volume information applies. If the information applies uniformly to a grid volume file series, a reference to the corresponding file bundle may be provided instead.
%
%   dimension           : (1,:) int64
%                         Enter the dimension of this grid volume.
%
%   name                : (1,1) string
%                         Enter a descriptive name of this grid volume preferably matching the filename.
%
%   numberOfPlanes      : (1,1) int64
%                         Enter number of planes in this grid volume.
%
%   obtainedWith        : (1,1) <a href="matlab:help openminds.ephys.device.ElectrodeArrayUsage" style="font-weight:bold">ElectrodeArrayUsage</a>, <a href="matlab:help openminds.ephys.device.ElectrodeUsage" style="font-weight:bold">ElectrodeUsage</a>, <a href="matlab:help openminds.ephys.device.PipetteUsage" style="font-weight:bold">PipetteUsage</a>, <a href="matlab:help openminds.neuroimaging.device.MRICoilUsage" style="font-weight:bold">MRICoilUsage</a>, <a href="matlab:help openminds.neuroimaging.device.MRIScannerUsage" style="font-weight:bold">MRIScannerUsage</a>, <a href="matlab:help openminds.specimenprep.device.SlicingDeviceUsage" style="font-weight:bold">SlicingDeviceUsage</a>
%                         Add the used device for obtaining this grid volume.
%
%   voxelSize           : (1,:) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                         Enter the physical voxel size for this grid volume (in x,y,z order).

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter any additional remarks concerning this grid volume.
        additionalRemarks (1,1) string

        % Add the coordinate space in which this grid volume exists.
        coordinateFramework (1,:) openminds.internal.mixedtype.gridvolume.CoordinateFramework ...
            {mustBeScalarOrEmpty(coordinateFramework)}

        % Add a reference to the file to which this grid volume information applies. If the information applies uniformly to a grid volume file series, a reference to the corresponding file bundle may be provided instead.
        dataLocation (1,:) openminds.internal.mixedtype.gridvolume.DataLocation ...
            {mustBeScalarOrEmpty(dataLocation)}

        % Enter the dimension of this grid volume.
        dimension (1,:) int64 ...
            {mustBeMinLength(dimension, 3), mustBeMaxLength(dimension, 3)}

        % Enter a descriptive name of this grid volume preferably matching the filename.
        name (1,1) string

        % Enter number of planes in this grid volume.
        numberOfPlanes (1,:) int64 ...
            {mustBeScalarOrEmpty(numberOfPlanes)}

        % Add the used device for obtaining this grid volume.
        obtainedWith (1,:) openminds.internal.mixedtype.gridvolume.ObtainedWith ...
            {mustBeScalarOrEmpty(obtainedWith)}

        % Enter the physical voxel size for this grid volume (in x,y,z order).
        voxelSize (1,:) openminds.core.miscellaneous.QuantitativeValue ...
            {mustBeMinLength(voxelSize, 3), mustBeMaxLength(voxelSize, 3)}
    end

    properties (Access = protected)
        Required = ["dataLocation", "dimension", "voxelSize"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/GridVolume"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'coordinateFramework', ["openminds.sands.atlas.CommonCoordinateFrameworkVersion", "openminds.sands.nonatlas.CustomCoordinateFramework"], ...
            'dataLocation', ["openminds.core.data.File", "openminds.core.data.FileBundle"], ...
            'obtainedWith', ["openminds.ephys.device.ElectrodeArrayUsage", "openminds.ephys.device.ElectrodeUsage", "openminds.ephys.device.PipetteUsage", "openminds.neuroimaging.device.MRICoilUsage", "openminds.neuroimaging.device.MRIScannerUsage", "openminds.specimenprep.device.SlicingDeviceUsage"] ...
        )
        EMBEDDED_PROPERTIES = struct(...
            'voxelSize', "openminds.core.miscellaneous.QuantitativeValue" ...
        )
    end

    methods
        function obj = GridVolume(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.core.data.GridVolume
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.name;
        end
    end
end
