classdef UsageAgreement < openminds.abstract.Schema
%UsageAgreement - No description available.
%
%   PROPERTIES:
%
%   authoringParty      : (1,:) <a href="matlab:help openminds.core.actors.Organization" style="font-weight:bold">Organization</a>, <a href="matlab:help openminds.core.actors.Person" style="font-weight:bold">Person</a>
%                         Add all natural persons and legal entities (in display order) responsible for creating and establishing this usage agreement.
%
%   fullName            : (1,1) string
%                         Enter the full name of this usage agreement.
%
%   jurisdiction        : (1,1) <a href="matlab:help openminds.controlledterms.SovereignState" style="font-weight:bold">SovereignState</a>, <a href="matlab:help openminds.controlledterms.SupranationalBody" style="font-weight:bold">SupranationalBody</a>
%                         Enter the jurisdiction in which this usage agreement was issued.
%
%   modificationProfile : (1,:) <a href="matlab:help openminds.controlledterms.ModificationConsentRequirement" style="font-weight:bold">ModificationConsentRequirement</a>, <a href="matlab:help openminds.controlledterms.ModificationConstraint" style="font-weight:bold">ModificationConstraint</a>, <a href="matlab:help openminds.controlledterms.ModificationForm" style="font-weight:bold">ModificationForm</a>, <a href="matlab:help openminds.controlledterms.ModificationScope" style="font-weight:bold">ModificationScope</a>
%                         Add all the types of modifications that are allowed under this usage agreement.
%
%   shortName           : (1,1) string
%                         Enter a short name (or alias) for this usage agreement that could be used as a shortened display title (e.g., for web services with too little space to display the full name).
%
%   source              : (1,:) <a href="matlab:help openminds.core.data.License" style="font-weight:bold">License</a>, <a href="matlab:help openminds.core.data.UsageAgreement" style="font-weight:bold">UsageAgreement</a>
%                         Add all licenses or usage agreements that served as references in the creation of this usage agreement.
%
%   supportChannel      : (1,:) string
%                         Enter all channels through which users can obtain support and initiate negotiations regarding this usage agreement with the authoring party.
%
%   template            : (1,1) <a href="matlab:help openminds.core.miscellaneous.WebResource" style="font-weight:bold">WebResource</a>
%                         Add the web resource that supplies the template for this usage agreement.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add all natural persons and legal entities (in display order) responsible for creating and establishing this usage agreement.
        authoringParty (1,:) openminds.internal.mixedtype.usageagreement.AuthoringParty ...
            {mustBeMinLength(authoringParty, 1), mustBeListOfUniqueItems(authoringParty)}

        % Enter the full name of this usage agreement.
        fullName (1,1) string

        % Enter the jurisdiction in which this usage agreement was issued.
        jurisdiction (1,:) openminds.internal.mixedtype.usageagreement.Jurisdiction ...
            {mustBeScalarOrEmpty(jurisdiction)}

        % Add all the types of modifications that are allowed under this usage agreement.
        modificationProfile (1,:) openminds.internal.mixedtype.usageagreement.ModificationProfile ...
            {mustBeMinLength(modificationProfile, 1), mustBeListOfUniqueItems(modificationProfile)}

        % Enter a short name (or alias) for this usage agreement that could be used as a shortened display title (e.g., for web services with too little space to display the full name).
        shortName (1,1) string

        % Add all licenses or usage agreements that served as references in the creation of this usage agreement.
        source (1,:) openminds.internal.mixedtype.usageagreement.Source ...
            {mustBeMinLength(source, 1), mustBeListOfUniqueItems(source)}

        % Enter all channels through which users can obtain support and initiate negotiations regarding this usage agreement with the authoring party.
        supportChannel (1,:) string ...
            {mustBeMinLength(supportChannel, 1), mustBeListOfUniqueItems(supportChannel)}

        % Add the web resource that supplies the template for this usage agreement.
        template (1,:) openminds.core.miscellaneous.WebResource ...
            {mustBeScalarOrEmpty(template)}
    end

    properties (Access = protected)
        Required = ["authoringParty", "fullName", "jurisdiction", "modificationProfile", "shortName", "template"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/UsageAgreement"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'authoringParty', ["openminds.core.actors.Organization", "openminds.core.actors.Person"], ...
            'jurisdiction', ["openminds.controlledterms.SovereignState", "openminds.controlledterms.SupranationalBody"], ...
            'modificationProfile', ["openminds.controlledterms.ModificationConsentRequirement", "openminds.controlledterms.ModificationConstraint", "openminds.controlledterms.ModificationForm", "openminds.controlledterms.ModificationScope"], ...
            'source', ["openminds.core.data.License", "openminds.core.data.UsageAgreement"], ...
            'template', "openminds.core.miscellaneous.WebResource" ...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = UsageAgreement(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.core.data.UsageAgreement
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.fullName;
        end
    end
end
