classdef Device < openminds.internal.abstract.LinkedCategory
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.ephys.device.ElectrodeArrayUsage", ...
            "openminds.ephys.device.ElectrodeUsage", ...
            "openminds.ephys.device.PipetteUsage", ...
            "openminds.specimenprep.device.SlicingDeviceUsage" ...
        ]
        IS_SCALAR = false
    end
end