classdef DigitalIdentifier < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.core.digitalidentifier.GRIDID", ...
            "openminds.core.digitalidentifier.RORID", ...
            "openminds.core.digitalidentifier.RRID" ...
        ]
        IS_SCALAR = false
    end
end