classdef ModificationProfile < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.controlledterms.ModificationConsentRequirement", ...
            "openminds.controlledterms.ModificationConstraint", ...
            "openminds.controlledterms.ModificationForm", ...
            "openminds.controlledterms.ModificationScope" ...
        ]
        IS_SCALAR = false
    end
end
