classdef Dimension < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.sands.mathematicalshape.Circle", ...
            "openminds.sands.mathematicalshape.Ellipse", ...
            "openminds.sands.mathematicalshape.Rectangle" ...
        ]
        IS_SCALAR = true
    end
end