classdef UsedSpecimen < openminds.internal.abstract.LinkedCategory
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.core.research.Subject", ...
            "openminds.core.research.SubjectGroup", ...
            "openminds.core.research.TissueSample", ...
            "openminds.core.research.TissueSampleCollection" ...
        ]
        IS_SCALAR = false
    end
end