classdef FullDocumentation < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.core.data.File", ...
            "openminds.core.miscellaneous.DOI", ...
            "openminds.core.miscellaneous.URL" ...
        ]
        IS_SCALAR = true
    end
end