classdef CustomPropertySet < openminds.abstract.Schema
%CustomPropertySet - Structured information about properties of an entity that are not represented in an openMINDS schema.
%
%   PROPERTIES:
%
%   context      : (1,1) string
%                  Enter the common context for this custom property set.
%
%   dataLocation : (1,1) <a href="matlab:help openminds.core.data.File" style="font-weight:bold">File</a>, <a href="matlab:help openminds.core.research.Configuration" style="font-weight:bold">Configuration</a>, <a href="matlab:help openminds.core.research.PropertyValueList" style="font-weight:bold">PropertyValueList</a>
%                  Add the location of the data that define the custom property set for the given context (e.g., stored as file or other entities such as property-value lists).
%
%   relevantFor  : (1,1) <a href="matlab:help openminds.controlledterms.AnalysisTechnique" style="font-weight:bold">AnalysisTechnique</a>, <a href="matlab:help openminds.controlledterms.MRIPulseSequence" style="font-weight:bold">MRIPulseSequence</a>, <a href="matlab:help openminds.controlledterms.MRIWeighting" style="font-weight:bold">MRIWeighting</a>, <a href="matlab:help openminds.controlledterms.StimulationApproach" style="font-weight:bold">StimulationApproach</a>, <a href="matlab:help openminds.controlledterms.StimulationTechnique" style="font-weight:bold">StimulationTechnique</a>, <a href="matlab:help openminds.controlledterms.Technique" style="font-weight:bold">Technique</a>
%                  Add the technique for which this custom property set is relevant.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter the common context for this custom property set.
        context (1,1) string

        % Add the location of the data that define the custom property set for the given context (e.g., stored as file or other entities such as property-value lists).
        dataLocation (1,:) openminds.internal.mixedtype.custompropertyset.DataLocation ...
            {mustBeSpecifiedLength(dataLocation, 0, 1)}

        % Add the technique for which this custom property set is relevant.
        relevantFor (1,:) openminds.internal.mixedtype.custompropertyset.RelevantFor ...
            {mustBeSpecifiedLength(relevantFor, 0, 1)}
    end

    properties (Access = protected)
        Required = ["context", "dataLocation", "relevantFor"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/CustomPropertySet"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'dataLocation', ["openminds.core.data.File", "openminds.core.research.Configuration", "openminds.core.research.PropertyValueList"], ...
            'relevantFor', ["openminds.controlledterms.AnalysisTechnique", "openminds.controlledterms.MRIPulseSequence", "openminds.controlledterms.MRIWeighting", "openminds.controlledterms.StimulationApproach", "openminds.controlledterms.StimulationTechnique", "openminds.controlledterms.Technique"] ...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = CustomPropertySet(varargin)
            obj@openminds.abstract.Schema(varargin{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.createLabelForMissingLabelDefinition();
        end
    end
end
