classdef Environment < openminds.base.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.computation.Environment", ...
            "openminds.core.products.Service" ...
        ]
        IS_SCALAR = true
    end
end
