classdef DataLocation < openminds.internal.abstract.LinkedCategory
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.core.data.File", ...
            "openminds.core.data.FileArchive", ...
            "openminds.core.data.FileBundle", ...
            "openminds.core.products.ModelVersion", ...
            "openminds.publications.LivePaperResourceItem", ...
            "openminds.sands.atlas.ParcellationEntityVersion" ...
        ]
        IS_SCALAR = true
    end
end