classdef GridImage < openminds.abstract.Schema
%GridImage - No description available.
%
%   PROPERTIES:
%
%   additionalRemarks   : (1,1) string
%                         Enter any additional remarks concerning this grid image.
%
%   coordinateFramework : (1,1) <a href="matlab:help openminds.sands.atlas.CommonCoordinateFrameworkVersion" style="font-weight:bold">CommonCoordinateFrameworkVersion</a>, <a href="matlab:help openminds.sands.nonatlas.CustomCoordinateFramework" style="font-weight:bold">CustomCoordinateFramework</a>
%                         Add the coordinate space in which this grid image exists.
%
%   dataLocation        : (1,1) <a href="matlab:help openminds.core.data.File" style="font-weight:bold">File</a>, <a href="matlab:help openminds.core.data.FileBundle" style="font-weight:bold">FileBundle</a>
%                         Add a reference to the file to which this grid image information applies. If the information applies uniformly to a grid image file series, a reference to the corresponding file bundle may be provided instead.
%
%   dimension           : (1,:) int64
%                         Enter the dimension of this grid image in pixels.
%
%   name                : (1,1) string
%                         Enter a descriptive name of this grid image preferably matching the filename.
%
%   obtainedWith        : (1,1) <a href="matlab:help openminds.ephys.device.ElectrodeArrayUsage" style="font-weight:bold">ElectrodeArrayUsage</a>, <a href="matlab:help openminds.ephys.device.ElectrodeUsage" style="font-weight:bold">ElectrodeUsage</a>, <a href="matlab:help openminds.ephys.device.PipetteUsage" style="font-weight:bold">PipetteUsage</a>, <a href="matlab:help openminds.neuroimaging.device.MRICoilUsage" style="font-weight:bold">MRICoilUsage</a>, <a href="matlab:help openminds.neuroimaging.device.MRIScannerUsage" style="font-weight:bold">MRIScannerUsage</a>, <a href="matlab:help openminds.specimenprep.device.SlicingDeviceUsage" style="font-weight:bold">SlicingDeviceUsage</a>
%                         Add the used device for obtaining this grid image.
%
%   pixelSize           : (1,:) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                         Enter the physical pixel size for this grid image (in x,y order).

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter any additional remarks concerning this grid image.
        additionalRemarks (1,1) string

        % Add the coordinate space in which this grid image exists.
        coordinateFramework (1,:) openminds.internal.mixedtype.gridimage.CoordinateFramework ...
            {mustBeScalarOrEmpty(coordinateFramework)}

        % Add a reference to the file to which this grid image information applies. If the information applies uniformly to a grid image file series, a reference to the corresponding file bundle may be provided instead.
        dataLocation (1,:) openminds.internal.mixedtype.gridimage.DataLocation ...
            {mustBeScalarOrEmpty(dataLocation)}

        % Enter the dimension of this grid image in pixels.
        dimension (1,:) int64 ...
            {mustBeMinLength(dimension, 2), mustBeMaxLength(dimension, 2)}

        % Enter a descriptive name of this grid image preferably matching the filename.
        name (1,1) string

        % Add the used device for obtaining this grid image.
        obtainedWith (1,:) openminds.internal.mixedtype.gridimage.ObtainedWith ...
            {mustBeScalarOrEmpty(obtainedWith)}

        % Enter the physical pixel size for this grid image (in x,y order).
        pixelSize (1,:) openminds.core.miscellaneous.QuantitativeValue ...
            {mustBeMinLength(pixelSize, 2), mustBeMaxLength(pixelSize, 2)}
    end

    properties (Access = protected)
        Required = ["dataLocation", "dimension", "pixelSize"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/GridImage"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'coordinateFramework', ["openminds.sands.atlas.CommonCoordinateFrameworkVersion", "openminds.sands.nonatlas.CustomCoordinateFramework"], ...
            'dataLocation', ["openminds.core.data.File", "openminds.core.data.FileBundle"], ...
            'obtainedWith', ["openminds.ephys.device.ElectrodeArrayUsage", "openminds.ephys.device.ElectrodeUsage", "openminds.ephys.device.PipetteUsage", "openminds.neuroimaging.device.MRICoilUsage", "openminds.neuroimaging.device.MRIScannerUsage", "openminds.specimenprep.device.SlicingDeviceUsage"] ...
        )
        EMBEDDED_PROPERTIES = struct(...
            'pixelSize', "openminds.core.miscellaneous.QuantitativeValue" ...
        )
    end

    methods
        function obj = GridImage(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.core.data.GridImage
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.name;
        end
    end
end
