classdef GridImageStack < openminds.abstract.Schema
%GridImageStack - No description available.
%
%   PROPERTIES:
%
%   additionalRemarks   : (1,1) string
%                         Enter any additional remarks concerning this grid image stack.
%
%   coordinateFramework : (1,1) <a href="matlab:help openminds.sands.atlas.CommonCoordinateFrameworkVersion" style="font-weight:bold">CommonCoordinateFrameworkVersion</a>, <a href="matlab:help openminds.sands.nonatlas.CustomCoordinateFramework" style="font-weight:bold">CustomCoordinateFramework</a>
%                         Add the coordinate space in which this grid image stack exists.
%
%   dataLocation        : (1,1) <a href="matlab:help openminds.core.data.File" style="font-weight:bold">File</a>, <a href="matlab:help openminds.core.data.FileBundle" style="font-weight:bold">FileBundle</a>
%                         Add a reference to the file to which this grid image stack information applies. If the information applies uniformly to a grid image stack file series, a reference to the corresponding file bundle may be provided instead.
%
%   dimension           : (1,:) int64
%                         Enter the common dimension of the consecutive grid image planes (optical sections) in pixels.
%
%   name                : (1,1) string
%                         Enter a descriptive name of this grid image stack preferably matching the filename.
%
%   numberOfImages      : (1,1) int64
%                         Enter the total number of consecutive grid image planes (optical sections) in this stack (at least two).
%
%   obtainedWith        : (1,1) <a href="matlab:help openminds.ephys.device.ElectrodeArrayUsage" style="font-weight:bold">ElectrodeArrayUsage</a>, <a href="matlab:help openminds.ephys.device.ElectrodeUsage" style="font-weight:bold">ElectrodeUsage</a>, <a href="matlab:help openminds.ephys.device.PipetteUsage" style="font-weight:bold">PipetteUsage</a>, <a href="matlab:help openminds.neuroimaging.device.MRICoilUsage" style="font-weight:bold">MRICoilUsage</a>, <a href="matlab:help openminds.neuroimaging.device.MRIScannerUsage" style="font-weight:bold">MRIScannerUsage</a>, <a href="matlab:help openminds.specimenprep.device.SlicingDeviceUsage" style="font-weight:bold">SlicingDeviceUsage</a>
%                         Add the used device for obtaining this grid image stack.
%
%   pixelSize           : (1,:) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                         Enter the common physical pixel size for the consecutive grid image planes (optical sections) (in x,y order).
%
%   zStepSize           : (1,1) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                         Enter the physical axial distance between consecutive image planes (optical sections) within this grid image stack.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter any additional remarks concerning this grid image stack.
        additionalRemarks (1,1) string

        % Add the coordinate space in which this grid image stack exists.
        coordinateFramework (1,:) openminds.internal.mixedtype.gridimagestack.CoordinateFramework ...
            {mustBeSpecifiedLength(coordinateFramework, 0, 1)}

        % Add a reference to the file to which this grid image stack information applies. If the information applies uniformly to a grid image stack file series, a reference to the corresponding file bundle may be provided instead.
        dataLocation (1,:) openminds.internal.mixedtype.gridimagestack.DataLocation ...
            {mustBeSpecifiedLength(dataLocation, 0, 1)}

        % Enter the common dimension of the consecutive grid image planes (optical sections) in pixels.
        dimension (1,:) int64 ...
            {mustBeSpecifiedLength(dimension, 2, 2)}

        % Enter a descriptive name of this grid image stack preferably matching the filename.
        name (1,1) string

        % Enter the total number of consecutive grid image planes (optical sections) in this stack (at least two).
        numberOfImages (1,:) int64 ...
            {mustBeSpecifiedLength(numberOfImages, 0, 1), mustBeInteger(numberOfImages), mustBeGreaterThanOrEqual(numberOfImages, 2)}

        % Add the used device for obtaining this grid image stack.
        obtainedWith (1,:) openminds.internal.mixedtype.gridimagestack.ObtainedWith ...
            {mustBeSpecifiedLength(obtainedWith, 0, 1)}

        % Enter the common physical pixel size for the consecutive grid image planes (optical sections) (in x,y order).
        pixelSize (1,:) openminds.core.miscellaneous.QuantitativeValue ...
            {mustBeSpecifiedLength(pixelSize, 2, 2)}

        % Enter the physical axial distance between consecutive image planes (optical sections) within this grid image stack.
        zStepSize (1,:) openminds.core.miscellaneous.QuantitativeValue ...
            {mustBeSpecifiedLength(zStepSize, 0, 1)}
    end

    properties (Access = protected)
        Required = ["dataLocation", "dimension", "pixelSize", "zStepSize"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/GridImageStack"
    end

    properties (Constant, Hidden)
        PROPERTY_NAME_MAP = struct(...
            'zStepSize', 'z-stepSize' ...
        )
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'coordinateFramework', ["openminds.sands.atlas.CommonCoordinateFrameworkVersion", "openminds.sands.nonatlas.CustomCoordinateFramework"], ...
            'dataLocation', ["openminds.core.data.File", "openminds.core.data.FileBundle"], ...
            'obtainedWith', ["openminds.ephys.device.ElectrodeArrayUsage", "openminds.ephys.device.ElectrodeUsage", "openminds.ephys.device.PipetteUsage", "openminds.neuroimaging.device.MRICoilUsage", "openminds.neuroimaging.device.MRIScannerUsage", "openminds.specimenprep.device.SlicingDeviceUsage"] ...
        )
        EMBEDDED_PROPERTIES = struct(...
            'pixelSize', "openminds.core.miscellaneous.QuantitativeValue", ...
            'zStepSize', "openminds.core.miscellaneous.QuantitativeValue" ...
        )
    end

    methods
        function obj = GridImageStack(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.core.data.GridImageStack
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.name;
        end
    end
end
