classdef CustomAnnotation < openminds.abstract.Schema
%CustomAnnotation - No description available.
%
%   PROPERTIES:
%
%   coordinateFramework    : (1,1) <a href="matlab:help openminds.sands.atlas.CommonCoordinateFrameworkVersion" style="font-weight:bold">CommonCoordinateFrameworkVersion</a>, <a href="matlab:help openminds.sands.nonatlas.CustomCoordinateFramework" style="font-weight:bold">CustomCoordinateFramework</a>
%                            Add the coordinate framework for this custom annotation.
%
%   criteria               : (1,1) <a href="matlab:help openminds.core.research.ProtocolExecution" style="font-weight:bold">ProtocolExecution</a>
%                            Add the protocol execution defining the criteria that were applied to produce this annotation.
%
%   criteriaQualityType    : (1,1) <a href="matlab:help openminds.controlledterms.CriteriaQualityType" style="font-weight:bold">CriteriaQualityType</a>
%                            Add the quality type of the stated criteria used to define this annotation.
%
%   criteriaType           : (1,1) <a href="matlab:help openminds.controlledterms.AnnotationCriteriaType" style="font-weight:bold">AnnotationCriteriaType</a>
%                            Add the criteria type for this annotation.
%
%   inspiredBy             : (1,:) <a href="matlab:help openminds.core.data.File" style="font-weight:bold">File</a>
%                            Add all (source) files that inspired the definition of this annotation.
%
%   internalIdentifier     : (1,1) string
%                            Enter the identifier (or label) of this annotation that is used within the corresponding data files to identify this annotation.
%
%   laterality             : (1,:) <a href="matlab:help openminds.controlledterms.Laterality" style="font-weight:bold">Laterality</a>
%                            Add one or both sides of the body, bilateral organ or bilateral organ part that this annotation is defined in.
%
%   preferredVisualization : (1,1) <a href="matlab:help openminds.sands.miscellaneous.ViewerSpecification" style="font-weight:bold">ViewerSpecification</a>
%                            Add the preferred viewer specification to visualize this annotation.
%
%   specification          : (1,1) <a href="matlab:help openminds.core.data.File" style="font-weight:bold">File</a>, <a href="matlab:help openminds.core.research.PropertyValueList" style="font-weight:bold">PropertyValueList</a>
%                            Add the non-parametric or parametric specification of this annotation.
%
%   type                   : (1,1) <a href="matlab:help openminds.controlledterms.AnnotationType" style="font-weight:bold">AnnotationType</a>
%                            Add the geometry type of this annotation.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add the coordinate framework for this custom annotation.
        coordinateFramework (1,:) openminds.internal.mixedtype.customannotation.CoordinateFramework ...
            {mustBeScalarOrEmpty(coordinateFramework)}

        % Add the protocol execution defining the criteria that were applied to produce this annotation.
        criteria (1,:) openminds.core.research.ProtocolExecution ...
            {mustBeScalarOrEmpty(criteria)}

        % Add the quality type of the stated criteria used to define this annotation.
        criteriaQualityType (1,:) openminds.controlledterms.CriteriaQualityType ...
            {mustBeScalarOrEmpty(criteriaQualityType)}

        % Add the criteria type for this annotation.
        criteriaType (1,:) openminds.controlledterms.AnnotationCriteriaType ...
            {mustBeScalarOrEmpty(criteriaType)}

        % Add all (source) files that inspired the definition of this annotation.
        inspiredBy (1,:) openminds.core.data.File ...
            {mustBeMinLength(inspiredBy, 1), mustBeListOfUniqueItems(inspiredBy)}

        % Enter the identifier (or label) of this annotation that is used within the corresponding data files to identify this annotation.
        internalIdentifier (1,1) string

        % Add one or both sides of the body, bilateral organ or bilateral organ part that this annotation is defined in.
        laterality (1,:) openminds.controlledterms.Laterality ...
            {mustBeMinLength(laterality, 1), mustBeMaxLength(laterality, 2), mustBeListOfUniqueItems(laterality)}

        % Add the preferred viewer specification to visualize this annotation.
        preferredVisualization (1,:) openminds.sands.miscellaneous.ViewerSpecification ...
            {mustBeScalarOrEmpty(preferredVisualization)}

        % Add the non-parametric or parametric specification of this annotation.
        specification (1,:) openminds.internal.mixedtype.customannotation.Specification ...
            {mustBeScalarOrEmpty(specification)}

        % Add the geometry type of this annotation.
        type (1,:) openminds.controlledterms.AnnotationType ...
            {mustBeScalarOrEmpty(type)}
    end

    properties (Access = protected)
        Required = ["coordinateFramework", "criteriaQualityType", "criteriaType", "type"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/CustomAnnotation"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'coordinateFramework', ["openminds.sands.atlas.CommonCoordinateFrameworkVersion", "openminds.sands.nonatlas.CustomCoordinateFramework"], ...
            'criteria', "openminds.core.research.ProtocolExecution", ...
            'criteriaQualityType', "openminds.controlledterms.CriteriaQualityType", ...
            'criteriaType', "openminds.controlledterms.AnnotationCriteriaType", ...
            'inspiredBy', "openminds.core.data.File", ...
            'laterality', "openminds.controlledterms.Laterality", ...
            'specification', ["openminds.core.data.File", "openminds.core.research.PropertyValueList"], ...
            'type', "openminds.controlledterms.AnnotationType" ...
        )
        EMBEDDED_PROPERTIES = struct(...
            'preferredVisualization', "openminds.sands.miscellaneous.ViewerSpecification" ...
        )
    end

    methods
        function obj = CustomAnnotation(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.sands.nonatlas.CustomAnnotation
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.createLabelForMissingLabelDefinition();
        end
    end
end
