classdef CustomCoordinateFramework < openminds.abstract.Schema
%CustomCoordinateFramework - No description available.
%
%   PROPERTIES:
%
%   anatomicalAxesOrientation : (1,1) <a href="matlab:help openminds.controlledterms.AnatomicalAxesOrientation" style="font-weight:bold">AnatomicalAxesOrientation</a>
%                               Add the axes orientation denoted in standard anatomical terms of direction (stated as XYZ) for the anatomical space of this custom coordinate framework.
%
%   axesOrigin                : (1,:) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                               Enter the coordinate point in the native anatomical space of the template as [x, y] or [x, y, z] for two- or three-dimensional spaces, respectively, that has been defined as the origin of the anatomical space of this custom coordinate framework (i.e., as the central point where all axes intersect).
%
%   defaultImage              : (1,:) <a href="matlab:help openminds.core.data.File" style="font-weight:bold">File</a>
%                               Add all image files used as visual representation of this custom coordinate framework.
%
%   name                      : (1,1) string
%                               Enter a descriptive name for this custom coordinate framework.
%
%   nativeUnit                : (1,1) <a href="matlab:help openminds.controlledterms.UnitOfMeasurement" style="font-weight:bold">UnitOfMeasurement</a>
%                               Add the native unit that is used for this custom coordinate framework.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add the axes orientation denoted in standard anatomical terms of direction (stated as XYZ) for the anatomical space of this custom coordinate framework.
        anatomicalAxesOrientation (1,:) openminds.controlledterms.AnatomicalAxesOrientation ...
            {mustBeSpecifiedLength(anatomicalAxesOrientation, 0, 1)}

        % Enter the coordinate point in the native anatomical space of the template as [x, y] or [x, y, z] for two- or three-dimensional spaces, respectively, that has been defined as the origin of the anatomical space of this custom coordinate framework (i.e., as the central point where all axes intersect).
        axesOrigin (1,:) openminds.core.miscellaneous.QuantitativeValue ...
            {mustBeSpecifiedLength(axesOrigin, 2, 3)}

        % Add all image files used as visual representation of this custom coordinate framework.
        defaultImage (1,:) openminds.core.data.File ...
            {mustBeListOfUniqueItems(defaultImage)}

        % Enter a descriptive name for this custom coordinate framework.
        name (1,1) string

        % Add the native unit that is used for this custom coordinate framework.
        nativeUnit (1,:) openminds.controlledterms.UnitOfMeasurement ...
            {mustBeSpecifiedLength(nativeUnit, 0, 1)}
    end

    properties (Access = protected)
        Required = ["anatomicalAxesOrientation", "axesOrigin", "name", "nativeUnit"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/CustomCoordinateFramework"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'anatomicalAxesOrientation', "openminds.controlledterms.AnatomicalAxesOrientation", ...
            'defaultImage', "openminds.core.data.File", ...
            'nativeUnit', "openminds.controlledterms.UnitOfMeasurement" ...
        )
        EMBEDDED_PROPERTIES = struct(...
            'axesOrigin', "openminds.core.miscellaneous.QuantitativeValue" ...
        )
    end

    methods
        function obj = CustomCoordinateFramework(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.sands.nonatlas.CustomCoordinateFramework
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.name;
        end
    end
end
