classdef RelevantFor < openminds.internal.abstract.LinkedCategory
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.controlledterms.Technique", ...
            "openminds.core.research.BehavioralTask" ...
        ]
        IS_SCALAR = true
    end
end