classdef PerformedBy < openminds.base.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.computation.SoftwareAgent", ...
            "openminds.core.actors.Person" ...
        ]
        IS_SCALAR = false
    end
end
