classdef Electrode < openminds.abstract.Schema
%Electrode - Structured information on an electrode.
%
%   PROPERTIES:
%
%   conductorMaterial   : (1,1) <a href="matlab:help openminds.chemicals.ChemicalMixture" style="font-weight:bold">ChemicalMixture</a>, <a href="matlab:help openminds.chemicals.ChemicalSubstance" style="font-weight:bold">ChemicalSubstance</a>, <a href="matlab:help openminds.controlledterms.MolecularEntity" style="font-weight:bold">MolecularEntity</a>
%                         Add the conductor material of this electrode.
%
%   contribution        : (1,:) <a href="matlab:help openminds.core.actors.Organization" style="font-weight:bold">Organization</a>, <a href="matlab:help openminds.core.actors.Person" style="font-weight:bold">Person</a>
%                         Add all relevant contributions (e.g., ownership, maintenance) for this device.
%
%   description         : (1,1) string
%                         Enter a short description of the device. Describe the device itself for a custom-built device or note device-specific peculiarities or deviations from the standard product for a manufacturer-defined device.
%
%   insulatorMaterial   : (1,1) <a href="matlab:help openminds.chemicals.ChemicalMixture" style="font-weight:bold">ChemicalMixture</a>, <a href="matlab:help openminds.chemicals.ChemicalSubstance" style="font-weight:bold">ChemicalSubstance</a>, <a href="matlab:help openminds.controlledterms.MolecularEntity" style="font-weight:bold">MolecularEntity</a>
%                         Add the insulator material of this electrode.
%
%   internalIdentifier  : (1,1) string
%                         Enter the identifier (or label) of this electrode that is used within the corresponding data files to identify this electrode.
%
%   intrinsicResistance : (1,1) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>, <a href="matlab:help openminds.core.miscellaneous.QuantitativeValueRange" style="font-weight:bold">QuantitativeValueRange</a>
%                         Enter the intrinsic resistance of this electrode.
%
%   name                : (1,1) string
%                         Enter a descriptive name for this device, preferably defined by the owner.
%
%   serialNumber        : (1,1) string
%                         Enter the serial number of this device.
%
%   type                : (1,1) <a href="matlab:help openminds.controlledterms.DeviceType" style="font-weight:bold">DeviceType</a>, <a href="matlab:help openminds.core.products.HardwareProduct" style="font-weight:bold">HardwareProduct</a>
%                         Add the device classification reference. Identify a device type for a custom-built device, or a hardware product for a device corresponding to a manufacturer-defined product model.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add the conductor material of this electrode.
        conductorMaterial (1,:) openminds.internal.mixedtype.electrode.ConductorMaterial ...
            {mustBeSpecifiedLength(conductorMaterial, 0, 1)}

        % Add all relevant contributions (e.g., ownership, maintenance) for this device.
        contribution (1,:) openminds.internal.mixedtype.electrode.Contribution ...
            {mustBeListOfUniqueItems(contribution)}

        % Enter a short description of the device. Describe the device itself for a custom-built device or note device-specific peculiarities or deviations from the standard product for a manufacturer-defined device.
        description (1,1) string

        % Add the insulator material of this electrode.
        insulatorMaterial (1,:) openminds.internal.mixedtype.electrode.InsulatorMaterial ...
            {mustBeSpecifiedLength(insulatorMaterial, 0, 1)}

        % Enter the identifier (or label) of this electrode that is used within the corresponding data files to identify this electrode.
        internalIdentifier (1,1) string

        % Enter the intrinsic resistance of this electrode.
        intrinsicResistance (1,:) openminds.internal.mixedtype.electrode.IntrinsicResistance ...
            {mustBeSpecifiedLength(intrinsicResistance, 0, 1)}

        % Enter a descriptive name for this device, preferably defined by the owner.
        name (1,1) string

        % Enter the serial number of this device.
        serialNumber (1,1) string

        % Add the device classification reference. Identify a device type for a custom-built device, or a hardware product for a device corresponding to a manufacturer-defined product model.
        type (1,:) openminds.internal.mixedtype.electrode.Type ...
            {mustBeSpecifiedLength(type, 0, 1)}
    end

    properties (Access = protected)
        Required = ["contribution", "name", "type"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/Electrode"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'conductorMaterial', ["openminds.chemicals.ChemicalMixture", "openminds.chemicals.ChemicalSubstance", "openminds.controlledterms.MolecularEntity"], ...
            'contribution', ["openminds.core.actors.Organization", "openminds.core.actors.Person"], ...
            'insulatorMaterial', ["openminds.chemicals.ChemicalMixture", "openminds.chemicals.ChemicalSubstance", "openminds.controlledterms.MolecularEntity"], ...
            'type', ["openminds.controlledterms.DeviceType", "openminds.core.products.HardwareProduct"] ...
        )
        EMBEDDED_PROPERTIES = struct(...
            'intrinsicResistance', ["openminds.core.miscellaneous.QuantitativeValue", "openminds.core.miscellaneous.QuantitativeValueRange"] ...
        )
    end

    methods
        function obj = Electrode(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.ephys.device.Electrode
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.name;
        end
    end
end
