classdef BreedingType < openminds.abstract.ControlledTerm
%BreedingType - No description available.
%
%   PROPERTIES:
%
%   definition                  : (1,1) string
%                                 Enter one sentence for defining this term.
%
%   description                 : (1,1) string
%                                 Enter a short text describing this term.
%
%   name                        : (1,1) string
%                                 Controlled term originating from a defined terminology.
%
%   otherCrossReference         : (1,:) string
%                                 Enter all internationalized resource identifiers (IRIs) pointing to cross-references to external databases or registries that are equivalent to this term (e.g., Wikidata). Do not repeat the preferred cross-reference.
%
%   otherOntologyIdentifier     : (1,:) string
%                                 Enter all internationalized resource identifiers (IRIs) pointing to ontology entries that are equivalent to this term (e.g., UBERON). Do not repeat the preferred ontology identifier.
%
%   preferredCrossReference     : (1,1) string
%                                 Enter the internationalized resource identifier (IRI) pointing to the preferred cross-reference to an external database or registry (e.g., KnowledgeSpace).
%
%   preferredOntologyIdentifier : (1,1) string
%                                 Enter the internationalized resource identifier (IRI) pointing to the preferred ontological term (e.g., InterLex).
%
%   synonym                     : (1,:) string
%                                 Enter one or several synonyms (including abbreviations) for this controlled term.

%   This class was auto-generated by the openMINDS pipeline

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/BreedingType"
    end

    properties (Constant, Hidden)
        CONTROLLED_INSTANCES = [ ...
            "coisogenic", ...
            "congenic", ...
            "hybrid", ...
            "inbred", ...
            "outbred", ...
            "selectiveInbred" ...
        ]
    end

    methods
        function obj = BreedingType(instanceSpec, propValues)
            arguments
                instanceSpec = []
                propValues.?openminds.controlledterms.BreedingType
                propValues.id (1,1) string
            end

            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.ControlledTerm(instanceSpec, propValues{:})
        end
    end

    methods (Static)
        function instances = listInstances()
            instances = openminds.controlledterms.BreedingType.CONTROLLED_INSTANCES';
        end
    end
end
