classdef DescendedFrom < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.core.research.SubjectGroupState", ...
            "openminds.core.research.SubjectState", ...
            "openminds.core.research.TissueSampleCollectionState", ...
            "openminds.core.research.TissueSampleState" ...
        ]
        IS_SCALAR = false
    end
end