classdef SpecimenAge < openminds.abstract.Schema
%SpecimenAge - No description available.
%
%   PROPERTIES:
%
%   age       : (1,1) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>, <a href="matlab:help openminds.core.miscellaneous.QuantitativeValueRange" style="font-weight:bold">QuantitativeValueRange</a>
%               Enter the age value.
%
%   reference : (1,1) <a href="matlab:help openminds.controlledterms.AgeReference" style="font-weight:bold">AgeReference</a>
%               Enter the age reference for the specified age value.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter the age value.
        age (1,:) openminds.internal.mixedtype.specimenage.Age ...
            {mustBeScalarOrEmpty(age)}

        % Enter the age reference for the specified age value.
        reference (1,:) openminds.controlledterms.AgeReference ...
            {mustBeScalarOrEmpty(reference)}
    end

    properties (Access = protected)
        Required = ["age", "reference"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/SpecimenAge"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'reference', "openminds.controlledterms.AgeReference" ...
        )
        EMBEDDED_PROPERTIES = struct(...
            'age', ["openminds.core.miscellaneous.QuantitativeValue", "openminds.core.miscellaneous.QuantitativeValueRange"] ...
        )
    end

    methods
        function obj = SpecimenAge(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.core.research.SpecimenAge
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.createLabelForMissingLabelDefinition();
        end
    end
end
