classdef UsedSpecimen < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.core.research.SubjectState", ...
            "openminds.core.research.TissueSampleState" ...
        ]
        IS_SCALAR = true
    end
end