classdef PreferredDisplayColor < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.controlledterms.Colormap", ...
            "openminds.sands.miscellaneous.SingleColor" ...
        ]
        IS_SCALAR = true
    end
end