classdef Input < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.core.data.File", ...
            "openminds.core.data.FileBundle", ...
            "openminds.core.data.LocalFile", ...
            "openminds.core.products.SoftwareVersion", ...
            "openminds.sands.atlas.AnatomicalAtlasVersion", ...
            "openminds.sands.atlas.CommonCoordinateFrameworkVersion" ...
        ]
        IS_SCALAR = false
    end
end
