classdef PublicationIssue < openminds.abstract.Schema
%PublicationIssue - No description available.
%
%   PROPERTIES:
%
%   isPartOf    : (1,1) <a href="matlab:help openminds.publications.PublicationVolume" style="font-weight:bold">PublicationVolume</a>
%                 Add the publication volume this publication issue is part of.
%
%   issueNumber : (1,1) string
%                 Enter the issue number of this publication issue.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add the publication volume this publication issue is part of.
        isPartOf (1,:) openminds.publications.PublicationVolume ...
            {mustBeSpecifiedLength(isPartOf, 0, 1)}

        % Enter the issue number of this publication issue.
        issueNumber (1,1) string
    end

    properties (Access = protected)
        Required = ["isPartOf", "issueNumber"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/PublicationIssue"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'isPartOf', "openminds.publications.PublicationVolume" ...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = PublicationIssue(varargin)
            obj@openminds.abstract.Schema(varargin{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = sprintf('%s: %s', obj.isPartOf, obj.issueNumber);
        end
    end
end