classdef RORID < openminds.abstract.Schema
%RORID - A persistent identifier for a research organization, provided by the Research Organization Registry.
%
%   PROPERTIES:
%
%   identifier : (1,1) string
%                Enter the resolvable identifier (IRI) of the Research Organization Registry.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter the resolvable identifier (IRI) of the Research Organization Registry.
        identifier (1,1) string ...
            {mustMatchPattern(identifier, '^https://ror.org/0([0-9]|[^ILO]|[a-z]){6}[0-9]{2}$')}
    end

    properties (Access = protected)
        Required = []
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.ebrains.eu/core/RORID"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = RORID(varargin)
            obj@openminds.abstract.Schema(varargin{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = sprintf('%s', obj.identifier);
        end
    end

end