classdef URL < openminds.abstract.Schema
%URL - No description available.
%
%   PROPERTIES:
%
%   URL : (1,1) string
%         Enter a uniform resource locator (URL).

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter a uniform resource locator (URL).
        URL (1,1) string
    end

    properties (Access = protected)
        Required = []
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.ebrains.eu/core/URL"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = URL(varargin)
            obj@openminds.abstract.Schema(varargin{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = sprintf('%s', obj.URL);
        end
    end
end