classdef Protocol < openminds.abstract.Schema
%Protocol - Structured information on a research project.
%
%   PROPERTIES:
%
%   describedIn  : (1,1) <a href="matlab:help openminds.core.data.File" style="font-weight:bold">File</a>, <a href="matlab:help openminds.core.digitalidentifier.DOI" style="font-weight:bold">DOI</a>, <a href="matlab:help openminds.core.miscellaneous.WebResource" style="font-weight:bold">WebResource</a>
%                  Add a publication or file in which this behavioral protocol is (originally) described in detail.
%
%   description  : (1,1) string
%                  Enter a description of this protocol.
%
%   name         : (1,1) string
%                  Enter a descriptive name for this protocol.
%
%   stimulusType : (1,:) <a href="matlab:help openminds.controlledterms.AuditoryStimulusType" style="font-weight:bold">AuditoryStimulusType</a>, <a href="matlab:help openminds.controlledterms.ElectricalStimulusType" style="font-weight:bold">ElectricalStimulusType</a>, <a href="matlab:help openminds.controlledterms.GustatoryStimulusType" style="font-weight:bold">GustatoryStimulusType</a>, <a href="matlab:help openminds.controlledterms.OlfactoryStimulusType" style="font-weight:bold">OlfactoryStimulusType</a>, <a href="matlab:help openminds.controlledterms.OpticalStimulusType" style="font-weight:bold">OpticalStimulusType</a>, <a href="matlab:help openminds.controlledterms.TactileStimulusType" style="font-weight:bold">TactileStimulusType</a>, <a href="matlab:help openminds.controlledterms.VisualStimulusType" style="font-weight:bold">VisualStimulusType</a>
%                  Add all stimulus types used with this protocol.
%
%   technique    : (1,:) <a href="matlab:help openminds.controlledterms.AnalysisTechnique" style="font-weight:bold">AnalysisTechnique</a>, <a href="matlab:help openminds.controlledterms.StimulationApproach" style="font-weight:bold">StimulationApproach</a>, <a href="matlab:help openminds.controlledterms.StimulationTechnique" style="font-weight:bold">StimulationTechnique</a>, <a href="matlab:help openminds.controlledterms.Technique" style="font-weight:bold">Technique</a>
%                  Add all techniques (including stimulation approaches and/or techniques) that were used in this protocol.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add a publication or file in which this behavioral protocol is (originally) described in detail.
        describedIn (1,:) openminds.internal.mixedtype.protocol.DescribedIn ...
            {mustBeSpecifiedLength(describedIn, 0, 1)}

        % Enter a description of this protocol.
        description (1,1) string

        % Enter a descriptive name for this protocol.
        name (1,1) string

        % Add all stimulus types used with this protocol.
        stimulusType (1,:) openminds.internal.mixedtype.protocol.StimulusType ...
            {mustBeListOfUniqueItems(stimulusType)}

        % Add all techniques (including stimulation approaches and/or techniques) that were used in this protocol.
        technique (1,:) openminds.internal.mixedtype.protocol.Technique ...
            {mustBeListOfUniqueItems(technique)}
    end

    properties (Access = protected)
        Required = ["description", "name", "technique"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.ebrains.eu/core/Protocol"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'describedIn', ["openminds.core.data.File", "openminds.core.digitalidentifier.DOI", "openminds.core.miscellaneous.WebResource"], ...
            'stimulusType', ["openminds.controlledterms.AuditoryStimulusType", "openminds.controlledterms.ElectricalStimulusType", "openminds.controlledterms.GustatoryStimulusType", "openminds.controlledterms.OlfactoryStimulusType", "openminds.controlledterms.OpticalStimulusType", "openminds.controlledterms.TactileStimulusType", "openminds.controlledterms.VisualStimulusType"], ...
            'technique', ["openminds.controlledterms.AnalysisTechnique", "openminds.controlledterms.StimulationApproach", "openminds.controlledterms.StimulationTechnique", "openminds.controlledterms.Technique"] ...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = Protocol(varargin)
            obj@openminds.abstract.Schema(varargin{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = sprintf('%s', obj.name);
        end
    end
end
