classdef SubjectGroup < openminds.abstract.Schema
%SubjectGroup - No description available.
%
%   PROPERTIES:
%
%   additionalRemarks  : (1,1) string
%                        Enter any additional remarks concering this specimen set.
%
%   biologicalSex      : (1,:) <a href="matlab:help openminds.controlledterms.BiologicalSex" style="font-weight:bold">BiologicalSex</a>
%                        Add the biological sex of all specimen in this set.
%
%   internalIdentifier : (1,1) string
%                        Enter the identifier (or label) of this specimen set that is used within the corresponding data files to identify this specimen set.
%
%   lookupLabel        : (1,1) string
%                        Enter a lookup label for this specimen set that may help you to find this instance more easily.
%
%   numberOfSubjects   : (1,1) int64
%                        Enter the number of subjects that belong to this subject group.
%
%   species            : (1,:) <a href="matlab:help openminds.controlledterms.Species" style="font-weight:bold">Species</a>, <a href="matlab:help openminds.core.research.Strain" style="font-weight:bold">Strain</a>
%                        Add the species and/or strain (a sub-type of a genetic variant of species) of all specimen in this set.
%
%   studiedState       : (1,:) <a href="matlab:help openminds.core.research.SubjectGroupState" style="font-weight:bold">SubjectGroupState</a>
%                        Add all states in which this subject group was studied.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter any additional remarks concering this specimen set.
        additionalRemarks (1,1) string

        % Add the biological sex of all specimen in this set.
        biologicalSex (1,:) openminds.controlledterms.BiologicalSex ...
            {mustBeListOfUniqueItems(biologicalSex)}

        % Enter the identifier (or label) of this specimen set that is used within the corresponding data files to identify this specimen set.
        internalIdentifier (1,1) string

        % Enter a lookup label for this specimen set that may help you to find this instance more easily.
        lookupLabel (1,1) string

        % Enter the number of subjects that belong to this subject group.
        numberOfSubjects (1,:) int64 ...
            {mustBeSpecifiedLength(numberOfSubjects, 0, 1), mustBeInteger(numberOfSubjects), mustBeGreaterThanOrEqual(numberOfSubjects, 2)}

        % Add the species and/or strain (a sub-type of a genetic variant of species) of all specimen in this set.
        species (1,:) openminds.internal.mixedtype.subjectgroup.Species ...
            {mustBeListOfUniqueItems(species)}

        % Add all states in which this subject group was studied.
        studiedState (1,:) openminds.core.research.SubjectGroupState ...
            {mustBeListOfUniqueItems(studiedState)}
    end

    properties (Access = protected)
        Required = ["species", "studiedState"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.ebrains.eu/core/SubjectGroup"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'biologicalSex', "openminds.controlledterms.BiologicalSex", ...
            'species', ["openminds.controlledterms.Species", "openminds.core.research.Strain"], ...
            'studiedState', "openminds.core.research.SubjectGroupState" ...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = SubjectGroup(varargin)
            obj@openminds.abstract.Schema(varargin{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = sprintf('%s', obj.lookupLabel);
        end
    end
end
