classdef CoordinatePoint < openminds.abstract.Schema
%CoordinatePoint - No description available.
%
%   PROPERTIES:
%
%   coordinateFramework : (1,1) <a href="matlab:help openminds.sands.atlas.CommonCoordinateFrameworkVersion" style="font-weight:bold">CommonCoordinateFrameworkVersion</a>, <a href="matlab:help openminds.sands.nonatlas.CustomCoordinateFramework" style="font-weight:bold">CustomCoordinateFramework</a>
%                         Add the coordinate framework in which this coordinate point exists in.
%
%   coordinates         : (1,:) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                         Enter the coordinates of this point within the stated coordinate space for two-dimensonal spaces as [x, y] or for three-dimensional space as [x, y, z].

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add the coordinate framework in which this coordinate point exists in.
        coordinateFramework (1,:) openminds.internal.mixedtype.coordinatepoint.CoordinateFramework ...
            {mustBeSpecifiedLength(coordinateFramework, 0, 1)}

        % Enter the coordinates of this point within the stated coordinate space for two-dimensonal spaces as [x, y] or for three-dimensional space as [x, y, z].
        coordinates (1,:) openminds.core.miscellaneous.QuantitativeValue ...
            {mustBeSpecifiedLength(coordinates, 2, 3)}
    end

    properties (Access = protected)
        Required = ["coordinateFramework", "coordinates"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/CoordinatePoint"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'coordinateFramework', ["openminds.sands.atlas.CommonCoordinateFrameworkVersion", "openminds.sands.nonatlas.CustomCoordinateFramework"] ...
        )
        EMBEDDED_PROPERTIES = struct(...
            'coordinates', "openminds.core.miscellaneous.QuantitativeValue" ...
        )
    end

    methods
        function obj = CoordinatePoint(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.sands.miscellaneous.CoordinatePoint
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.createLabelForMissingLabelDefinition();
        end
    end
end
