function [newVersion, mltbxPath] = packageToolbox(releaseType, versionString, varargin)
    arguments
        releaseType {mustBeTextScalar,mustBeMember(releaseType,["build","major","minor","patch","specific"])} = "build"
        versionString {mustBeTextScalar} = "";
    end
    arguments (Repeating)
        varargin
    end

    ommtools.installMatBox("commit")

    projectRootDirectory = ommtools.projectdir();
    % Not sure if this is needed:
    run(fullfile(projectRootDirectory, 'code', 'startup.m'))

    % Specify toolbox path folders
    generatedLatest = fullfile(projectRootDirectory, "code", "generated", "resources", "latest");
    toolboxPathFolders = [...
        fullfile(projectRootDirectory, "code"), ...
        fullfile(projectRootDirectory, "code", "internal"), ...
        fullfile(projectRootDirectory, "code", "internal", "property_validation"), ...
        fullfile(projectRootDirectory, "code", "livescripts"), ...
        fullfile(generatedLatest, "types"), ...
        fullfile(generatedLatest, "mixedtypes"), ...
        fullfile(generatedLatest, "enumerations"), ...
        fullfile(generatedLatest, "base") ...
    ];

    [newVersion, mltbxPath] = matbox.tasks.packageToolbox(projectRootDirectory, releaseType, versionString, ...
        varargin{:}, ...
        "ToolboxShortName", "openMINDS_MATLAB", ...
        "PathFolders", toolboxPathFolders );
end
