function packageToolbox(releaseType, versionString, varargin)
    arguments
        releaseType {mustBeTextScalar,mustBeMember(releaseType,["build","major","minor","patch","specific"])} = "build"
        versionString {mustBeTextScalar} = "";
    end
    arguments (Repeating)
        varargin
    end

    ommtools.installMatBox("commit")

    projectRootDirectory = ommtools.projectdir();
    % Not sure if this is needed:
    run(fullfile(projectRootDirectory, 'code', 'startup.m'))

    % Specify toolbox path folders
    toolboxPathFolders = [...
        fullfile(projectRootDirectory, "code"), ...
        fullfile(projectRootDirectory, "code", "internal"), ...
        fullfile(projectRootDirectory, "code", "internal", "property_validation"), ...
        fullfile(projectRootDirectory, "code", "livescripts"), ...
        fullfile(projectRootDirectory, "code", "types", "latest"), ...
        fullfile(projectRootDirectory, "code", "mixedtypes", "latest"), ...
        fullfile(projectRootDirectory, "code", "enumerations", "latest") ...
    ];

    matbox.tasks.packageToolbox(projectRootDirectory, releaseType, versionString, ...
        varargin{:}, ...
        "ToolboxShortName", "openMINDS_MATLAB", ...
        "PathFolders", toolboxPathFolders )
end
