classdef GRIDID < openminds.abstract.Schema
%GRIDID - A GRID (Global Research Identifier Database) identifier.
%
%   PROPERTIES:
%
%   identifier : (1,1) string
%                Enter the resolvable identifier (IRI) of the Global Research Identifier Database.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter the resolvable identifier (IRI) of the Global Research Identifier Database.
        identifier (1,1) string ...
            {mustMatchPattern(identifier, '^https://grid.ac/institutes/grid.[0-9]{1,}.([a-f0-9]{1,2})$')}
    end

    properties (Access = protected)
        Required = []
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.ebrains.eu/core/GRIDID"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = GRIDID(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.core.miscellaneous.GRIDID
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = sprintf('%s', obj.identifier);
        end
    end
end
