function keywords = getJsonLDKeywords()
%GETJSONLDKEYWORDS Return list of reserved JSON-LD keywords
%
%   keywords = GETJSONLDKEYWORDS() returns a string array of the
%   reserved JSON-LD keywords defined in the JSON-LD 1.1 specification.

    keywords = [...
        "@base", ...
        "@container", ...
        "@context", ...
        "@direction", ...
        "@graph", ...
        "@id", ...
        "@import", ...
        "@included", ...
        "@index", ...
        "@json", ...
        "@language", ...
        "@list", ...
        "@nest", ...
        "@none", ...
        "@prefix", ...
        "@propagate", ...
        "@protected", ...
        "@reverse", ...
        "@set", ...
        "@type", ...
        "@value", ...
        "@version", ...
        "@vocab" ...
        ];
end
