classdef Affiliation < openminds.abstract.Schema
%Affiliation - Structured information about a relationship between two entities, such as a person and their employer.
%
%   PROPERTIES:
%
%   endDate   : (1,1) datetime
%               Enter the end date of this affiliation, formatted as 'YYYY-MM-DD'. Leave blank if this affiliation is still current.
%
%   memberOf  : (1,1) <a href="matlab:help openminds.core.actors.Consortium" style="font-weight:bold">Consortium</a>, <a href="matlab:help openminds.core.actors.Organization" style="font-weight:bold">Organization</a>
%               Add the organization or consortium another party was or still is a member of.
%
%   startDate : (1,1) datetime
%               Enter the start date of this affiliation, formatted as 'YYYY-MM-DD'.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter the end date of this affiliation, formatted as 'YYYY-MM-DD'. Leave blank if this affiliation is still current.
        endDate (1,:) datetime ...
            {mustBeSpecifiedLength(endDate, 0, 1), mustBeValidDate(endDate)}

        % Add the organization or consortium another party was or still is a member of.
        memberOf (1,:) openminds.internal.mixedtype.affiliation.MemberOf ...
            {mustBeSpecifiedLength(memberOf, 0, 1)}

        % Enter the start date of this affiliation, formatted as 'YYYY-MM-DD'.
        startDate (1,:) datetime ...
            {mustBeSpecifiedLength(startDate, 0, 1), mustBeValidDate(startDate)}
    end

    properties (Access = protected)
        Required = ["memberOf"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/Affiliation"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'memberOf', ["openminds.core.actors.Consortium", "openminds.core.actors.Organization"] ...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = Affiliation(structInstance, propValues)
            arguments
                structInstance (1,:) struct = struct.empty
                propValues.?openminds.core.actors.Affiliation
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = sprintf('%s', obj.memberOf);
        end
    end
end
