classdef Consortium < openminds.abstract.Schema
%Consortium - Structured information about an association of two or more persons or organizations, with the objective of participating in a common activity.
%
%   PROPERTIES:
%
%   contactInformation : (1,1) <a href="matlab:help openminds.core.actors.ContactInformation" style="font-weight:bold">ContactInformation</a>
%                        Add the contact information of this consortium.
%
%   fullName           : (1,1) string
%                        Enter the full name of this consortium.
%
%   homepage           : (1,1) string
%                        Enter the internationalized resource identifier (IRI) to the homepage of this consortium.
%
%   shortName          : (1,1) string
%                        Enter a short name (or alias) for this consortium that could be used as a shortened display title (e.g., for web services with too little space to display the full name).

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add the contact information of this consortium.
        contactInformation (1,:) openminds.core.actors.ContactInformation ...
            {mustBeSpecifiedLength(contactInformation, 0, 1)}

        % Enter the full name of this consortium.
        fullName (1,1) string

        % Enter the internationalized resource identifier (IRI) to the homepage of this consortium.
        homepage (1,1) string

        % Enter a short name (or alias) for this consortium that could be used as a shortened display title (e.g., for web services with too little space to display the full name).
        shortName (1,1) string
    end

    properties (Access = protected)
        Required = ["fullName"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/Consortium"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'contactInformation', "openminds.core.actors.ContactInformation" ...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = Consortium(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.core.actors.Consortium
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = sprintf('%s', obj.fullName);
        end
    end
end
