classdef Contribution < openminds.abstract.Schema
%Contribution - Structured information on the contribution made to a research product.
%
%   PROPERTIES:
%
%   contributor : (1,:) <a href="matlab:help openminds.core.actors.Consortium" style="font-weight:bold">Consortium</a>, <a href="matlab:help openminds.core.actors.Organization" style="font-weight:bold">Organization</a>, <a href="matlab:help openminds.core.actors.Person" style="font-weight:bold">Person</a>
%                 Add all contributors who made this contribution, in the desired display order.
%
%   type        : (1,1) <a href="matlab:help openminds.controlledterms.ContributionType" style="font-weight:bold">ContributionType</a>
%                 Add the type of contribution.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add all contributors who made this contribution, in the desired display order.
        contributor (1,:) openminds.internal.mixedtype.contribution.Contributor ...
            {mustBeMinLength(contributor, 1), mustBeListOfUniqueItems(contributor)}

        % Add the type of contribution.
        type (1,:) openminds.controlledterms.ContributionType ...
            {mustBeScalarOrEmpty(type)}
    end

    properties (Access = protected)
        Required = ["contributor", "type"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/Contribution"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'contributor', ["openminds.core.actors.Consortium", "openminds.core.actors.Organization", "openminds.core.actors.Person"], ...
            'type', "openminds.controlledterms.ContributionType" ...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = Contribution(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.core.actors.Contribution
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = sprintf('%s (%s)', obj.contributor, obj.type);
        end
    end
end
