classdef Organization < openminds.abstract.Schema
%Organization - An entity comprised of one or more natural persons with a particular purpose. [adapted from Wikipedia](https://en.wikipedia.org/wiki/Organization)
%
%   PROPERTIES:
%
%   acronym            : (1,1) string
%                        Enter the acronym of this organization.
%
%   alternateName      : (1,:) string
%                        Enter any other known name or acronym of this organization.
%
%   countryOfFormation : (1,1) <a href="matlab:help openminds.controlledterms.SovereignState" style="font-weight:bold">SovereignState</a>
%                        Add the country where the organization was formed.
%
%   digitalIdentifier  : (1,:) <a href="matlab:help openminds.core.digitalidentifier.GenericIdentifier" style="font-weight:bold">GenericIdentifier</a>, <a href="matlab:help openminds.core.digitalidentifier.ISNI" style="font-weight:bold">ISNI</a>, <a href="matlab:help openminds.core.digitalidentifier.LEI" style="font-weight:bold">LEI</a>, <a href="matlab:help openminds.core.digitalidentifier.RORID" style="font-weight:bold">RORID</a>, <a href="matlab:help openminds.core.digitalidentifier.RRID" style="font-weight:bold">RRID</a>
%                        Add all globally unique and persistent digital identifier of this organization.
%
%   hasParent          : (1,:) <a href="matlab:help openminds.core.actors.Organization" style="font-weight:bold">Organization</a>
%                        Add all parent organizations of this organization.
%
%   homepage           : (1,1) string
%                        Enter the internationalized resource identifier (IRI) to the homepage of this organization.
%
%   jurisdiction       : (1,1) <a href="matlab:help openminds.controlledterms.SovereignState" style="font-weight:bold">SovereignState</a>, <a href="matlab:help openminds.controlledterms.SupranationalBody" style="font-weight:bold">SupranationalBody</a>
%                        Add the jurisdiction under which the organization operates.
%
%   location           : (1,1) <a href="matlab:help openminds.core.miscellaneous.Location" style="font-weight:bold">Location</a>
%                        Add the headquarters location of this organization.
%
%   membership         : (1,:) <a href="matlab:help openminds.core.miscellaneous.Membership" style="font-weight:bold">Membership</a>
%                        Add all membership records (one per member) for this organization. Who is considered a qualified member is typically defined in the organization’s membership agreements.
%
%   name               : (1,1) string
%                        Enter the organization’s preferred name for use in international contexts.
%
%   type               : (1,1) <a href="matlab:help openminds.controlledterms.OrganizationType" style="font-weight:bold">OrganizationType</a>
%                        Add the type of this organization (legal entity or organizational unit).

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter the acronym of this organization.
        acronym (1,1) string

        % Enter any other known name or acronym of this organization.
        alternateName (1,:) string ...
            {mustBeMinLength(alternateName, 1), mustBeListOfUniqueItems(alternateName)}

        % Add the country where the organization was formed.
        countryOfFormation (1,:) openminds.controlledterms.SovereignState ...
            {mustBeScalarOrEmpty(countryOfFormation)}

        % Add all globally unique and persistent digital identifier of this organization.
        digitalIdentifier (1,:) openminds.internal.mixedtype.organization.DigitalIdentifier ...
            {mustBeMinLength(digitalIdentifier, 1), mustBeListOfUniqueItems(digitalIdentifier)}

        % Add all parent organizations of this organization.
        hasParent (1,:) openminds.core.actors.Organization ...
            {mustBeMinLength(hasParent, 1), mustBeListOfUniqueItems(hasParent)}

        % Enter the internationalized resource identifier (IRI) to the homepage of this organization.
        homepage (1,1) string

        % Add the jurisdiction under which the organization operates.
        jurisdiction (1,:) openminds.internal.mixedtype.organization.Jurisdiction ...
            {mustBeScalarOrEmpty(jurisdiction)}

        % Add the headquarters location of this organization.
        location (1,:) openminds.core.miscellaneous.Location ...
            {mustBeScalarOrEmpty(location)}

        % Add all membership records (one per member) for this organization. Who is considered a qualified member is typically defined in the organization’s membership agreements.
        membership (1,:) openminds.core.miscellaneous.Membership ...
            {mustBeMinLength(membership, 1), mustBeListOfUniqueItems(membership)}

        % Enter the organization’s preferred name for use in international contexts.
        name (1,1) string

        % Add the type of this organization (legal entity or organizational unit).
        type (1,:) openminds.controlledterms.OrganizationType ...
            {mustBeScalarOrEmpty(type)}
    end

    properties (Access = protected)
        Required = ["countryOfFormation", "name", "type"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/Organization"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'countryOfFormation', "openminds.controlledterms.SovereignState", ...
            'digitalIdentifier', ["openminds.core.digitalidentifier.GenericIdentifier", "openminds.core.digitalidentifier.ISNI", "openminds.core.digitalidentifier.LEI", "openminds.core.digitalidentifier.RORID", "openminds.core.digitalidentifier.RRID"], ...
            'hasParent', "openminds.core.actors.Organization", ...
            'jurisdiction', ["openminds.controlledterms.SovereignState", "openminds.controlledterms.SupranationalBody"], ...
            'type', "openminds.controlledterms.OrganizationType" ...
        )
        EMBEDDED_PROPERTIES = struct(...
            'location', "openminds.core.miscellaneous.Location", ...
            'membership', "openminds.core.miscellaneous.Membership" ...
        )
    end

    methods
        function obj = Organization(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.core.actors.Organization
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = sprintf('%s', obj.fullName);
        end
    end
end
