classdef Project < openminds.abstract.Schema
%Project - Structured information on a research project.
%
%   PROPERTIES:
%
%   contribution : (1,:) <a href="matlab:help openminds.core.actors.Contribution" style="font-weight:bold">Contribution</a>
%                  Add all individual, organisational, or consortial contributions to this project.
%
%   description  : (1,1) string
%                  Enter a description of this project.
%
%   fullName     : (1,1) string
%                  Enter a descriptive full name (or title) for this project.
%
%   hasPart      : (1,:) <a href="matlab:help openminds.computation.ValidationTest" style="font-weight:bold">ValidationTest</a>, <a href="matlab:help openminds.computation.ValidationTestVersion" style="font-weight:bold">ValidationTestVersion</a>, <a href="matlab:help openminds.computation.WorkflowRecipe" style="font-weight:bold">WorkflowRecipe</a>, <a href="matlab:help openminds.computation.WorkflowRecipeVersion" style="font-weight:bold">WorkflowRecipeVersion</a>, <a href="matlab:help openminds.core.products.Dataset" style="font-weight:bold">Dataset</a>, <a href="matlab:help openminds.core.products.DatasetVersion" style="font-weight:bold">DatasetVersion</a>, <a href="matlab:help openminds.core.products.Interface" style="font-weight:bold">Interface</a>, <a href="matlab:help openminds.core.products.InterfaceVersion" style="font-weight:bold">InterfaceVersion</a>, <a href="matlab:help openminds.core.products.MetaDataModel" style="font-weight:bold">MetaDataModel</a>, <a href="matlab:help openminds.core.products.MetaDataModelVersion" style="font-weight:bold">MetaDataModelVersion</a>, <a href="matlab:help openminds.core.products.Model" style="font-weight:bold">Model</a>, <a href="matlab:help openminds.core.products.ModelVersion" style="font-weight:bold">ModelVersion</a>, <a href="matlab:help openminds.core.products.Software" style="font-weight:bold">Software</a>, <a href="matlab:help openminds.core.products.SoftwareVersion" style="font-weight:bold">SoftwareVersion</a>, <a href="matlab:help openminds.publications.LivePaper" style="font-weight:bold">LivePaper</a>, <a href="matlab:help openminds.publications.LivePaperVersion" style="font-weight:bold">LivePaperVersion</a>, <a href="matlab:help openminds.sands.atlas.AnatomicalAtlas" style="font-weight:bold">AnatomicalAtlas</a>, <a href="matlab:help openminds.sands.atlas.AnatomicalAtlasVersion" style="font-weight:bold">AnatomicalAtlasVersion</a>, <a href="matlab:help openminds.sands.atlas.CommonCoordinateFramework" style="font-weight:bold">CommonCoordinateFramework</a>, <a href="matlab:help openminds.sands.atlas.CommonCoordinateFrameworkVersion" style="font-weight:bold">CommonCoordinateFrameworkVersion</a>
%                  Add all research product (versions) that are part of this project.
%
%   homepage     : (1,1) string
%                  Enter the internationalized resource identifier (IRI) to the homepage of this project.
%
%   shortName    : (1,1) string
%                  Enter a short name (or alias) for this project that could be used as a shortened display title (e.g., for web services with too little space to display the full name).
%
%   type         : (1,1) <a href="matlab:help openminds.controlledterms.ProjectType" style="font-weight:bold">ProjectType</a>
%                  Add the type of this project (e.g., research project, grant project).

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add all individual, organisational, or consortial contributions to this project.
        contribution (1,:) openminds.core.actors.Contribution ...
            {mustBeListOfUniqueItems(contribution)}

        % Enter a description of this project.
        description (1,1) string

        % Enter a descriptive full name (or title) for this project.
        fullName (1,1) string

        % Add all research product (versions) that are part of this project.
        hasPart (1,:) openminds.internal.mixedtype.project.HasPart ...
            {mustBeListOfUniqueItems(hasPart)}

        % Enter the internationalized resource identifier (IRI) to the homepage of this project.
        homepage (1,1) string

        % Enter a short name (or alias) for this project that could be used as a shortened display title (e.g., for web services with too little space to display the full name).
        shortName (1,1) string

        % Add the type of this project (e.g., research project, grant project).
        type (1,:) openminds.controlledterms.ProjectType ...
            {mustBeSpecifiedLength(type, 0, 1)}
    end

    properties (Access = protected)
        Required = ["description", "fullName", "hasPart", "shortName", "type"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/Project"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'hasPart', ["openminds.computation.ValidationTest", "openminds.computation.ValidationTestVersion", "openminds.computation.WorkflowRecipe", "openminds.computation.WorkflowRecipeVersion", "openminds.core.products.Dataset", "openminds.core.products.DatasetVersion", "openminds.core.products.Interface", "openminds.core.products.InterfaceVersion", "openminds.core.products.MetaDataModel", "openminds.core.products.MetaDataModelVersion", "openminds.core.products.Model", "openminds.core.products.ModelVersion", "openminds.core.products.Software", "openminds.core.products.SoftwareVersion", "openminds.publications.LivePaper", "openminds.publications.LivePaperVersion", "openminds.sands.atlas.AnatomicalAtlas", "openminds.sands.atlas.AnatomicalAtlasVersion", "openminds.sands.atlas.CommonCoordinateFramework", "openminds.sands.atlas.CommonCoordinateFrameworkVersion"], ...
            'type', "openminds.controlledterms.ProjectType" ...
        )
        EMBEDDED_PROPERTIES = struct(...
            'contribution', "openminds.core.actors.Contribution" ...
        )
    end

    methods
        function obj = Project(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.core.products.Project
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = sprintf('%s', obj.fullName);
        end
    end
end
