classdef CustomAnatomicalEntity < openminds.abstract.Schema
%CustomAnatomicalEntity - No description available.
%
%   PROPERTIES:
%
%   hasAnnotation              : (1,:) <a href="matlab:help openminds.sands.nonatlas.CustomAnnotation" style="font-weight:bold">CustomAnnotation</a>
%                                Add all custom annotations which define this custom anatomical entity.
%
%   name                       : (1,1) string
%                                Enter a descriptive name for this custom anatomical entity.
%
%   relatedInterspeciesAnatomy : (1,1) <a href="matlab:help openminds.controlledterms.AnatomicalCavity" style="font-weight:bold">AnatomicalCavity</a>, <a href="matlab:help openminds.controlledterms.ExternalBodyRegion" style="font-weight:bold">ExternalBodyRegion</a>, <a href="matlab:help openminds.controlledterms.MuscularStructure" style="font-weight:bold">MuscularStructure</a>, <a href="matlab:help openminds.controlledterms.NervousSystemStructure" style="font-weight:bold">NervousSystemStructure</a>, <a href="matlab:help openminds.controlledterms.Organ" style="font-weight:bold">Organ</a>, <a href="matlab:help openminds.controlledterms.OrganSystemStructure" style="font-weight:bold">OrganSystemStructure</a>, <a href="matlab:help openminds.controlledterms.OrganismSubstance" style="font-weight:bold">OrganismSubstance</a>, <a href="matlab:help openminds.controlledterms.OrganismSystem" style="font-weight:bold">OrganismSystem</a>, <a href="matlab:help openminds.controlledterms.SkeletalStructure" style="font-weight:bold">SkeletalStructure</a>, <a href="matlab:help openminds.controlledterms.TissueStructure" style="font-weight:bold">TissueStructure</a>, <a href="matlab:help openminds.controlledterms.VascularStructure" style="font-weight:bold">VascularStructure</a>
%                                Add the corresponding cross-species anatomical entity from the UBERON-derived terminologies that represents the generic anatomical concept underlying the custom anatomical entity.
%
%   relationAssessment         : (1,:) <a href="matlab:help openminds.sands.miscellaneous.QualitativeRelationAssessment" style="font-weight:bold">QualitativeRelationAssessment</a>, <a href="matlab:help openminds.sands.miscellaneous.QuantitativeRelationAssessment" style="font-weight:bold">QuantitativeRelationAssessment</a>
%                                Add all relations (qualitative or quantitative) of this custom anatomical entity to other anatomical entities.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add all custom annotations which define this custom anatomical entity.
        hasAnnotation (1,:) openminds.sands.nonatlas.CustomAnnotation ...
            {mustBeListOfUniqueItems(hasAnnotation)}

        % Enter a descriptive name for this custom anatomical entity.
        name (1,1) string

        % Add the corresponding cross-species anatomical entity from the UBERON-derived terminologies that represents the generic anatomical concept underlying the custom anatomical entity.
        relatedInterspeciesAnatomy (1,:) openminds.internal.mixedtype.customanatomicalentity.RelatedInterspeciesAnatomy ...
            {mustBeSpecifiedLength(relatedInterspeciesAnatomy, 0, 1)}

        % Add all relations (qualitative or quantitative) of this custom anatomical entity to other anatomical entities.
        relationAssessment (1,:) openminds.internal.mixedtype.customanatomicalentity.RelationAssessment ...
            {mustBeListOfUniqueItems(relationAssessment)}
    end

    properties (Access = protected)
        Required = ["name"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/CustomAnatomicalEntity"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'relatedInterspeciesAnatomy', ["openminds.controlledterms.AnatomicalCavity", "openminds.controlledterms.ExternalBodyRegion", "openminds.controlledterms.MuscularStructure", "openminds.controlledterms.NervousSystemStructure", "openminds.controlledterms.Organ", "openminds.controlledterms.OrganSystemStructure", "openminds.controlledterms.OrganismSubstance", "openminds.controlledterms.OrganismSystem", "openminds.controlledterms.SkeletalStructure", "openminds.controlledterms.TissueStructure", "openminds.controlledterms.VascularStructure"] ...
        )
        EMBEDDED_PROPERTIES = struct(...
            'hasAnnotation', "openminds.sands.nonatlas.CustomAnnotation", ...
            'relationAssessment', ["openminds.sands.miscellaneous.QualitativeRelationAssessment", "openminds.sands.miscellaneous.QuantitativeRelationAssessment"] ...
        )
    end

    methods
        function obj = CustomAnatomicalEntity(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.sands.nonatlas.CustomAnatomicalEntity
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.name;
        end
    end
end
