classdef TissueCulturePreparation < openminds.abstract.Schema
%TissueCulturePreparation - No description available.
%
%   PROPERTIES:
%
%   cultureMedium : (1,1) <a href="matlab:help openminds.chemicals.ChemicalMixture" style="font-weight:bold">ChemicalMixture</a>
%                   Add the culture medium used during this tissue culture preparation.
%
%   cultureType   : (1,1) <a href="matlab:help openminds.controlledterms.CellCultureType" style="font-weight:bold">CellCultureType</a>
%                   Add the cell culture type of the resulting tissue cell culture.
%
%   input         : (1,1) <a href="matlab:help openminds.core.SubjectGroupState" style="font-weight:bold">SubjectGroupState</a>, <a href="matlab:help openminds.core.SubjectState" style="font-weight:bold">SubjectState</a>, <a href="matlab:help openminds.core.TissueSampleCollectionState" style="font-weight:bold">TissueSampleCollectionState</a>, <a href="matlab:help openminds.core.TissueSampleState" style="font-weight:bold">TissueSampleState</a>
%                   Add the state of the specimen before it was prepared as culture in this activity.
%
%   output        : (1,1) <a href="matlab:help openminds.core.TissueSampleState" style="font-weight:bold">TissueSampleState</a>
%                   Add the state of the prepared tissue sample culture that resulted from this activity.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add the culture medium used during this tissue culture preparation.
        cultureMedium (1,:) openminds.chemicals.ChemicalMixture ...
            {mustBeSpecifiedLength(cultureMedium, 0, 1)}

        % Add the cell culture type of the resulting tissue cell culture.
        cultureType (1,:) openminds.controlledterms.CellCultureType ...
            {mustBeSpecifiedLength(cultureType, 0, 1)}

        % Add the state of the specimen before it was prepared as culture in this activity.
        input (1,:) openminds.internal.mixedtype.tissueculturepreparation.Input ...
            {mustBeSpecifiedLength(input, 0, 1)}

        % Add the state of the prepared tissue sample culture that resulted from this activity.
        output (1,:) openminds.core.TissueSampleState ...
            {mustBeSpecifiedLength(output, 0, 1)}
    end

    properties (Access = protected)
        Required = ["cultureMedium", "cultureType"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.ebrains.eu/specimenPrep/TissueCulturePreparation"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'cultureMedium', "openminds.chemicals.ChemicalMixture", ...
            'cultureType', "openminds.controlledterms.CellCultureType", ...
            'input', ["openminds.core.SubjectGroupState", "openminds.core.SubjectState", "openminds.core.TissueSampleCollectionState", "openminds.core.TissueSampleState"], ...
            'output', "openminds.core.TissueSampleState" ...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = TissueCulturePreparation(varargin)
            obj@openminds.abstract.Schema(varargin{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = '<missing name>';
        end
    end

end