classdef Input < openminds.internal.abstract.LinkedCategory
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.computation.LocalFile", ...
            "openminds.computation.ValidationTestVersion", ...
            "openminds.core.data.File", ...
            "openminds.core.data.FileBundle", ...
            "openminds.core.products.DatasetVersion", ...
            "openminds.core.products.ModelVersion", ...
            "openminds.core.products.SoftwareVersion" ...
        ]
        IS_SCALAR = false
    end
end