classdef AnatomicalLocation < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.controlledterms.AnatomicalCavity", ...
            "openminds.controlledterms.CellType", ...
            "openminds.controlledterms.ExternalBodyRegion", ...
            "openminds.controlledterms.MuscularStructure", ...
            "openminds.controlledterms.NervousSystemStructure", ...
            "openminds.controlledterms.Organ", ...
            "openminds.controlledterms.OrganSystemStructure", ...
            "openminds.controlledterms.OrganismSubstance", ...
            "openminds.controlledterms.OrganismSystem", ...
            "openminds.controlledterms.SkeletalStructure", ...
            "openminds.controlledterms.SubcellularEntity", ...
            "openminds.controlledterms.TissueStructure", ...
            "openminds.controlledterms.VascularStructure", ...
            "openminds.sands.atlas.ParcellationEntity", ...
            "openminds.sands.atlas.ParcellationEntityVersion", ...
            "openminds.sands.nonatlas.CustomAnatomicalEntity" ...
        ]
        IS_SCALAR = false
    end
end
