classdef IsPartOf < openminds.base.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.core.data.FileBundle", ...
            "openminds.core.data.FileRepository" ...
        ]
        IS_SCALAR = true
    end
end
