classdef StudyTarget < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.controlledterms.AnatomicalCavity", ...
            "openminds.controlledterms.AuditoryStimulusType", ...
            "openminds.controlledterms.BiologicalOrder", ...
            "openminds.controlledterms.BiologicalSex", ...
            "openminds.controlledterms.BreedingType", ...
            "openminds.controlledterms.CellCultureType", ...
            "openminds.controlledterms.CellType", ...
            "openminds.controlledterms.DeviceType", ...
            "openminds.controlledterms.Disease", ...
            "openminds.controlledterms.DiseaseModel", ...
            "openminds.controlledterms.ElectricalStimulusType", ...
            "openminds.controlledterms.ExternalBodyRegion", ...
            "openminds.controlledterms.GeneticStrainType", ...
            "openminds.controlledterms.GustatoryStimulusType", ...
            "openminds.controlledterms.Handedness", ...
            "openminds.controlledterms.MolecularEntity", ...
            "openminds.controlledterms.MuscularStructure", ...
            "openminds.controlledterms.NervousSystemStructure", ...
            "openminds.controlledterms.OlfactoryStimulusType", ...
            "openminds.controlledterms.OpticalStimulusType", ...
            "openminds.controlledterms.Organ", ...
            "openminds.controlledterms.OrganSystemStructure", ...
            "openminds.controlledterms.OrganismSubstance", ...
            "openminds.controlledterms.OrganismSystem", ...
            "openminds.controlledterms.SkeletalStructure", ...
            "openminds.controlledterms.Species", ...
            "openminds.controlledterms.SubcellularEntity", ...
            "openminds.controlledterms.TactileStimulusType", ...
            "openminds.controlledterms.TermSuggestion", ...
            "openminds.controlledterms.TissueSampleType", ...
            "openminds.controlledterms.TissueStructure", ...
            "openminds.controlledterms.VascularStructure", ...
            "openminds.controlledterms.VisualStimulusType", ...
            "openminds.sands.atlas.ParcellationEntity", ...
            "openminds.sands.atlas.ParcellationEntityVersion", ...
            "openminds.sands.nonatlas.CustomAnatomicalEntity" ...
        ]
        IS_SCALAR = false
    end
end
