function [person, affiliation] = personWithOneAffiliation()
% personWithOneAffiliation - Create a v4 Person with one Affiliation.

    ror = openminds.core.RORID("identifier", "https://ror.org/02jx3x895");
    org = openminds.core.Organization( ...
        "digitalIdentifier", ror, ...
        "fullName", "University College London");

    affiliation = openminds.core.Affiliation("memberOf", org);

    orcid = openminds.core.ORCID( ...
        "identifier", "https://orcid.org/0000-0000-0000-0000");

    contact = openminds.core.ContactInformation( ...
        "email", "johndsmith@somewhere.org");

    person = openminds.core.Person( ...
        "familyName", "Smith", ...
        "givenName", "John D.", ...
        "alternateName", "js", ...
        "affiliation", affiliation, ...
        "digitalIdentifier", orcid, ...
        "contactInformation", contact);
end
