function [person, affiliations] = personWithTwoAffiliations()
% personWithTwoAffiliations - Create a v4 Person with two Affiliations.

    ror = openminds.core.RORID("identifier", "https://ror.org/02jx3x895");
    orgA = openminds.core.Organization( ...
        "digitalIdentifier", ror, ...
        "fullName", "University College London");

    ror = openminds.core.RORID("identifier", "https://ror.org/01xtthb56");
    orgB = openminds.core.Organization( ...
        "digitalIdentifier", ror, ...
        "fullName", "University of Oslo", ...
        "shortName", "UiO");

    affiliations = openminds.core.Affiliation("memberOf", orgA);
    affiliations(2) = openminds.core.Affiliation("memberOf", orgB);

    orcid = openminds.core.ORCID( ...
        "identifier", "https://orcid.org/0000-0000-0000-0000");

    contact = openminds.core.ContactInformation( ...
        "email", "johndsmith@somewhere.org");

    person = openminds.core.Person( ...
        "familyName", "Smith", ...
        "givenName", "John D.", ...
        "affiliation", affiliations, ...
        "digitalIdentifier", orcid, ...
        "contactInformation", contact);
end
