classdef CoordinateFramework < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.sands.atlas.CommonCoordinateFrameworkVersion", ...
            "openminds.sands.nonatlas.CustomCoordinateFramework" ...
        ]
        IS_SCALAR = true
    end
end
