classdef GroupedBy < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.controlledterms.AnalysisTechnique", ...
            "openminds.controlledterms.AnatomicalCavity", ...
            "openminds.controlledterms.AuditoryStimulusType", ...
            "openminds.controlledterms.BiologicalOrder", ...
            "openminds.controlledterms.BiologicalSex", ...
            "openminds.controlledterms.BreedingType", ...
            "openminds.controlledterms.CellCultureType", ...
            "openminds.controlledterms.CellType", ...
            "openminds.controlledterms.DeviceType", ...
            "openminds.controlledterms.Disease", ...
            "openminds.controlledterms.DiseaseModel", ...
            "openminds.controlledterms.ElectricalStimulusType", ...
            "openminds.controlledterms.ExternalBodyRegion", ...
            "openminds.controlledterms.GeneticStrainType", ...
            "openminds.controlledterms.GustatoryStimulusType", ...
            "openminds.controlledterms.Handedness", ...
            "openminds.controlledterms.MRIPulseSequence", ...
            "openminds.controlledterms.MRIWeighting", ...
            "openminds.controlledterms.MolecularEntity", ...
            "openminds.controlledterms.MuscularStructure", ...
            "openminds.controlledterms.NervousSystemStructure", ...
            "openminds.controlledterms.OlfactoryStimulusType", ...
            "openminds.controlledterms.OpticalStimulusType", ...
            "openminds.controlledterms.Organ", ...
            "openminds.controlledterms.OrganSystemStructure", ...
            "openminds.controlledterms.OrganismSubstance", ...
            "openminds.controlledterms.OrganismSystem", ...
            "openminds.controlledterms.SkeletalStructure", ...
            "openminds.controlledterms.Species", ...
            "openminds.controlledterms.StimulationApproach", ...
            "openminds.controlledterms.StimulationTechnique", ...
            "openminds.controlledterms.SubcellularEntity", ...
            "openminds.controlledterms.TactileStimulusType", ...
            "openminds.controlledterms.Technique", ...
            "openminds.controlledterms.TermSuggestion", ...
            "openminds.controlledterms.TissueSampleType", ...
            "openminds.controlledterms.TissueStructure", ...
            "openminds.controlledterms.VascularStructure", ...
            "openminds.controlledterms.VisualStimulusType", ...
            "openminds.core.data.File", ...
            "openminds.core.data.FileBundle", ...
            "openminds.core.data.LocalFile", ...
            "openminds.core.research.BehavioralProtocol", ...
            "openminds.core.research.Subject", ...
            "openminds.core.research.SubjectGroup", ...
            "openminds.core.research.SubjectGroupState", ...
            "openminds.core.research.SubjectState", ...
            "openminds.core.research.TissueSample", ...
            "openminds.core.research.TissueSampleCollection", ...
            "openminds.core.research.TissueSampleCollectionState", ...
            "openminds.core.research.TissueSampleState", ...
            "openminds.sands.atlas.CommonCoordinateFramework", ...
            "openminds.sands.atlas.CommonCoordinateFrameworkVersion", ...
            "openminds.sands.atlas.ParcellationEntity", ...
            "openminds.sands.atlas.ParcellationEntityVersion", ...
            "openminds.sands.nonatlas.CustomAnatomicalEntity", ...
            "openminds.sands.nonatlas.CustomCoordinateFramework" ...
        ]
        IS_SCALAR = false
    end
end
