classdef AnatomicalLocationOfArray < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.controlledterms.CellType", ...
            "openminds.controlledterms.Organ", ...
            "openminds.controlledterms.OrganismSubstance", ...
            "openminds.controlledterms.SubcellularEntity", ...
            "openminds.controlledterms.UBERONParcellation", ...
            "openminds.sands.atlas.ParcellationEntity", ...
            "openminds.sands.atlas.ParcellationEntityVersion", ...
            "openminds.sands.nonatlas.CustomAnatomicalEntity" ...
        ]
        IS_SCALAR = false
    end
end