classdef Annotation < openminds.abstract.Schema
%Annotation - Structured information on an image annotation.
%
%   PROPERTIES:
%
%   bestViewPoint       : (1,1) <a href="matlab:help openminds.sands.CoordinatePoint" style="font-weight:bold">CoordinatePoint</a>
%                         Add the coordinate point identifying the best view of this annotation in space.
%
%   criteria            : (1,1) <a href="matlab:help openminds.core.research.ProtocolExecution" style="font-weight:bold">ProtocolExecution</a>
%                         Add the protocol execution defining the criteria that were applied to produce this annotation.
%
%   criteriaQualityType : (1,1) <a href="matlab:help openminds.controlledterms.CriteriaQualityType" style="font-weight:bold">CriteriaQualityType</a>
%                         Add the quality type of the stated criteria used to define this annotation.
%
%   displayColor        : (1,:) int64
%                         Enter the preferred display color (RGB) for this annotation.
%
%   inspiredBy          : (1,:) <a href="matlab:help openminds.sands.Image" style="font-weight:bold">Image</a>
%                         Add one or several (source) images that inspired the definition of this annotation.
%
%   internalIdentifier  : (1,1) string
%                         Enter the identifier used for this annotation within the file it is stored in.
%
%   laterality          : (1,:) <a href="matlab:help openminds.controlledterms.Laterality" style="font-weight:bold">Laterality</a>
%                         Add one or both sides of the body or bilateral organ that this annotation is defined in.
%
%   namingTerm          : (1,:) <a href="matlab:help openminds.sands.AnatomicalEntity" style="font-weight:bold">AnatomicalEntity</a>
%                         Add one or several anatomical entities that name this annotation.
%
%   relatedAtlasTerm    : (1,:) <a href="matlab:help openminds.sands.AnatomicalEntity" style="font-weight:bold">AnatomicalEntity</a>
%                         Add one or several anatomical entities of registered brain atlas annotations to which this annotation is related to.
%
%   visualizedIn        : (1,1) <a href="matlab:help openminds.sands.Image" style="font-weight:bold">Image</a>
%                         Add the image in which this annotation is visualized in.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add the coordinate point identifying the best view of this annotation in space.
        bestViewPoint (1,:) openminds.sands.CoordinatePoint ...
            {mustBeSpecifiedLength(bestViewPoint, 0, 1)}

        % Add the protocol execution defining the criteria that were applied to produce this annotation.
        criteria (1,:) openminds.core.research.ProtocolExecution ...
            {mustBeSpecifiedLength(criteria, 0, 1)}

        % Add the quality type of the stated criteria used to define this annotation.
        criteriaQualityType (1,:) openminds.controlledterms.CriteriaQualityType ...
            {mustBeSpecifiedLength(criteriaQualityType, 0, 1)}

        % Enter the preferred display color (RGB) for this annotation.
        displayColor (1,:) int64 ...
            {mustBeSpecifiedLength(displayColor, 3, 3)}

        % Add one or several (source) images that inspired the definition of this annotation.
        inspiredBy (1,:) openminds.sands.Image ...
            {mustBeListOfUniqueItems(inspiredBy)}

        % Enter the identifier used for this annotation within the file it is stored in.
        internalIdentifier (1,1) string

        % Add one or both sides of the body or bilateral organ that this annotation is defined in.
        laterality (1,:) openminds.controlledterms.Laterality ...
            {mustBeSpecifiedLength(laterality, 1, 2)}

        % Add one or several anatomical entities that name this annotation.
        namingTerm (1,:) openminds.sands.AnatomicalEntity ...
            {mustBeListOfUniqueItems(namingTerm)}

        % Add one or several anatomical entities of registered brain atlas annotations to which this annotation is related to.
        relatedAtlasTerm (1,:) openminds.sands.AnatomicalEntity

        % Add the image in which this annotation is visualized in.
        visualizedIn (1,:) openminds.sands.Image ...
            {mustBeSpecifiedLength(visualizedIn, 0, 1)}
    end

    properties (Access = protected)
        Required = ["criteriaQualityType", "internalIdentifier", "laterality", "namingTerm"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.ebrains.eu/sands/Annotation"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'bestViewPoint', "openminds.sands.CoordinatePoint", ...
            'criteria', "openminds.core.research.ProtocolExecution", ...
            'criteriaQualityType', "openminds.controlledterms.CriteriaQualityType", ...
            'inspiredBy', "openminds.sands.Image", ...
            'laterality', "openminds.controlledterms.Laterality", ...
            'namingTerm', "openminds.sands.AnatomicalEntity", ...
            'relatedAtlasTerm', "openminds.sands.AnatomicalEntity", ...
            'visualizedIn', "openminds.sands.Image" ...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = Annotation(varargin)
            obj@openminds.abstract.Schema(varargin{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.createLabelForMissingLabelDefinition();
        end
    end
end
