classdef BrainAtlasVersion < openminds.abstract.Schema & openminds.internal.mixin.HasControlledInstance
%BrainAtlasVersion - No description available.
%
%   PROPERTIES:
%
%   annotationSet         : (1,:) <a href="matlab:help openminds.sands.Annotation" style="font-weight:bold">Annotation</a>
%                           Add all annotations that belong to this brain atlas version.
%
%   coordinateSpace       : (1,1) <a href="matlab:help openminds.sands.CoordinateSpace" style="font-weight:bold">CoordinateSpace</a>
%                           Add the coordinate space in which this brain atlas version exists in.
%
%   digitalIdentifier     : (1,1) <a href="matlab:help openminds.core.miscellaneous.DigitalIdentifier" style="font-weight:bold">DigitalIdentifier</a>
%                           Add the globally unique and persistent digital identifier of this brain atlas version.
%
%   fullName              : (1,1) string
%                           Enter a descriptive full name for this brain atlas version.
%
%   hasAlternativeVersion : (1,:) <a href="matlab:help openminds.sands.BrainAtlasVersion" style="font-weight:bold">BrainAtlasVersion</a>
%                           Add one or several alternative versions to this brain atlas version.
%
%   homepage              : (1,1) string
%                           Enter the internationalized resource identifier (IRI) to the homepage of this brain atlas.
%
%   isNewVersionOf        : (1,1) <a href="matlab:help openminds.sands.BrainAtlasVersion" style="font-weight:bold">BrainAtlasVersion</a>
%                           Add the earlier version of this brain atlas version.
%
%   ontologyIdentifier    : (1,1) string
%                           Enter the identifier (IRI) of the related ontological term matching this brain atlas version.
%
%   releaseDate           : (1,1) string
%                           Enter the date of first publication of this brain atlas version.
%
%   shortName             : (1,1) string
%                           Enter a descriptive short name for this brain atlas version.
%
%   terminology           : (1,1) <a href="matlab:help openminds.sands.AtlasTerminology" style="font-weight:bold">AtlasTerminology</a>
%                           Add the terminology used for this brain atlas version.
%
%   versionIdentifier     : (1,1) string
%                           Enter the version identifier of this brain atlas version.
%
%   versionInnovation     : (1,1) string
%                           Enter a short description of the novelties/peculiarities of this brain atlas version.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add all annotations that belong to this brain atlas version.
        annotationSet (1,:) openminds.sands.Annotation ...
            {mustBeListOfUniqueItems(annotationSet)}

        % Add the coordinate space in which this brain atlas version exists in.
        coordinateSpace (1,:) openminds.sands.CoordinateSpace ...
            {mustBeSpecifiedLength(coordinateSpace, 0, 1)}

        % Add the globally unique and persistent digital identifier of this brain atlas version.
        digitalIdentifier (1,:) openminds.core.miscellaneous.DigitalIdentifier ...
            {mustBeSpecifiedLength(digitalIdentifier, 0, 1)}

        % Enter a descriptive full name for this brain atlas version.
        fullName (1,1) string

        % Add one or several alternative versions to this brain atlas version.
        hasAlternativeVersion (1,:) openminds.sands.BrainAtlasVersion ...
            {mustBeListOfUniqueItems(hasAlternativeVersion)}

        % Enter the internationalized resource identifier (IRI) to the homepage of this brain atlas.
        homepage (1,1) string

        % Add the earlier version of this brain atlas version.
        isNewVersionOf (1,:) openminds.sands.BrainAtlasVersion ...
            {mustBeSpecifiedLength(isNewVersionOf, 0, 1)}

        % Enter the identifier (IRI) of the related ontological term matching this brain atlas version.
        ontologyIdentifier (1,1) string

        % Enter the date of first publication of this brain atlas version.
        releaseDate (1,1) string

        % Enter a descriptive short name for this brain atlas version.
        shortName (1,1) string

        % Add the terminology used for this brain atlas version.
        terminology (1,:) openminds.sands.AtlasTerminology ...
            {mustBeSpecifiedLength(terminology, 0, 1)}

        % Enter the version identifier of this brain atlas version.
        versionIdentifier (1,1) string

        % Enter a short description of the novelties/peculiarities of this brain atlas version.
        versionInnovation (1,1) string
    end

    properties (Access = protected)
        Required = ["annotationSet", "coordinateSpace", "fullName", "releaseDate", "shortName", "terminology", "versionIdentifier", "versionInnovation"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.ebrains.eu/sands/BrainAtlasVersion"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'annotationSet', "openminds.sands.Annotation", ...
            'coordinateSpace', "openminds.sands.CoordinateSpace", ...
            'digitalIdentifier', "openminds.core.miscellaneous.DigitalIdentifier", ...
            'hasAlternativeVersion', "openminds.sands.BrainAtlasVersion", ...
            'isNewVersionOf', "openminds.sands.BrainAtlasVersion", ...
            'terminology', "openminds.sands.AtlasTerminology" ...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = BrainAtlasVersion(varargin)
            obj@openminds.abstract.Schema(varargin{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.fullName;
        end
    end

    methods (Static)
        function instance = fromName(name)
            typeName = mfilename('classname');
            instance = openminds.internal.mixin.HasControlledInstance.fromName(name, typeName);
        end
        function instanceNames = listInstances()
            typeName = mfilename('classname');
            instanceNames = openminds.internal.mixin.HasControlledInstance.listInstances(typeName);
        end
    end
end
