classdef BehavioralTask < openminds.abstract.Schema
%BehavioralTask - Structured information on the behavioral task that had to be performed by a subject.
%
%   PROPERTIES:
%
%   description : (1,1) string
%                 Enter a description of this behavioral task.
%
%   fullName    : (1,1) string
%                 Enter a descriptive full name for this behavioral task.
%
%   shortName   : (1,1) string
%                 Enter a short name (alias) for this behavioral task.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter a description of this behavioral task.
        description (1,1) string

        % Enter a descriptive full name for this behavioral task.
        fullName (1,1) string

        % Enter a short name (alias) for this behavioral task.
        shortName (1,1) string
    end

    properties (Access = protected)
        Required = ["description", "fullName"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.ebrains.eu/core/BehavioralTask"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = BehavioralTask(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.core.research.BehavioralTask
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.fullName;
        end
    end
end
