classdef SubjectGroup < openminds.abstract.Schema
%SubjectGroup - No description available.
%
%   PROPERTIES:
%
%   additionalRemarks  : (1,1) string
%                        Enter additional remarks about the specimen set.
%
%   biologicalSex      : (1,:) <a href="matlab:help openminds.controlledterms.BiologicalSex" style="font-weight:bold">BiologicalSex</a>
%                        Add the biological sex of all specimen in this set.
%
%   internalIdentifier : (1,1) string
%                        Enter the identifier of this specimen set that is used within the corresponding data.
%
%   lookupLabel        : (1,1) string
%                        Enter a lookup label for this specimen set that may help you to more easily find it again.
%
%   phenotype          : (1,:) <a href="matlab:help openminds.controlledterms.Phenotype" style="font-weight:bold">Phenotype</a>
%                        Add the phenotype of all specimen in this set.
%
%   quantity           : (1,1) int64
%                        Enter the number of specimen that belong to this set.
%
%   species            : (1,:) <a href="matlab:help openminds.controlledterms.Species" style="font-weight:bold">Species</a>
%                        Add the species of all specimen in this set.
%
%   strain             : (1,:) <a href="matlab:help openminds.controlledterms.Strain" style="font-weight:bold">Strain</a>
%                        Add the strain of all specimen in this set.
%
%   studiedState       : (1,:) <a href="matlab:help openminds.core.research.SubjectGroupState" style="font-weight:bold">SubjectGroupState</a>
%                        Add all states in which this subject group was studied.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter additional remarks about the specimen set.
        additionalRemarks (1,1) string

        % Add the biological sex of all specimen in this set.
        biologicalSex (1,:) openminds.controlledterms.BiologicalSex ...
            {mustBeListOfUniqueItems(biologicalSex)}

        % Enter the identifier of this specimen set that is used within the corresponding data.
        internalIdentifier (1,1) string

        % Enter a lookup label for this specimen set that may help you to more easily find it again.
        lookupLabel (1,1) string

        % Add the phenotype of all specimen in this set.
        phenotype (1,:) openminds.controlledterms.Phenotype ...
            {mustBeListOfUniqueItems(phenotype)}

        % Enter the number of specimen that belong to this set.
        quantity (1,:) int64 ...
            {mustBeSpecifiedLength(quantity, 0, 1)}

        % Add the species of all specimen in this set.
        species (1,:) openminds.controlledterms.Species ...
            {mustBeListOfUniqueItems(species)}

        % Add the strain of all specimen in this set.
        strain (1,:) openminds.controlledterms.Strain ...
            {mustBeListOfUniqueItems(strain)}

        % Add all states in which this subject group was studied.
        studiedState (1,:) openminds.core.research.SubjectGroupState ...
            {mustBeListOfUniqueItems(studiedState)}
    end

    properties (Access = protected)
        Required = ["biologicalSex", "species", "studiedState"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.ebrains.eu/core/SubjectGroup"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'biologicalSex', "openminds.controlledterms.BiologicalSex", ...
            'phenotype', "openminds.controlledterms.Phenotype", ...
            'species', "openminds.controlledterms.Species", ...
            'strain', "openminds.controlledterms.Strain", ...
            'studiedState', "openminds.core.research.SubjectGroupState" ...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = SubjectGroup(structInstance, propValues)
            arguments
                structInstance (1,:) struct = struct.empty
                propValues.?openminds.core.research.SubjectGroup
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = sprintf('%s', obj.lookupLabel);
        end
    end
end
