classdef ServiceDeployment < openminds.abstract.Schema
%ServiceDeployment - No description available.
%
%   PROPERTIES:
%
%   dependsOn      : (1,:) <a href="matlab:help openminds.computation.WorkflowRecipeVersion" style="font-weight:bold">WorkflowRecipeVersion</a>, <a href="matlab:help openminds.core.products.DatasetVersion" style="font-weight:bold">DatasetVersion</a>, <a href="matlab:help openminds.core.products.MetaDataModelVersion" style="font-weight:bold">MetaDataModelVersion</a>, <a href="matlab:help openminds.core.products.ModelVersion" style="font-weight:bold">ModelVersion</a>, <a href="matlab:help openminds.core.products.SoftwareVersion" style="font-weight:bold">SoftwareVersion</a>, <a href="matlab:help openminds.sands.atlas.AnatomicalAtlasVersion" style="font-weight:bold">AnatomicalAtlasVersion</a>, <a href="matlab:help openminds.sands.atlas.CommonCoordinateFrameworkVersion" style="font-weight:bold">CommonCoordinateFrameworkVersion</a>
%                    Add the software version and any other relevant research product version that was deployed.
%
%   deploymentType : (1,1) <a href="matlab:help openminds.controlledterms.DeploymentEnvironmentType" style="font-weight:bold">DeploymentEnvironmentType</a>
%                    Enter the type of deployment environment, for example, 'production' or 'integration'.
%
%   endTime        : (1,1) datetime
%                    Enter the date and time at which this deployment ended, formatted according to ISO-8601.
%
%   name           : (1,1) string
%                    Enter a label for this service deployment.
%
%   provides       : (1,:) <a href="matlab:help openminds.computation.DeployedInterface" style="font-weight:bold">DeployedInterface</a>
%                    Add the interfaces that have been deployed.
%
%   service        : (1,1) <a href="matlab:help openminds.core.products.Service" style="font-weight:bold">Service</a>
%                    Add the service that has been deployed.
%
%   startTime      : (1,1) datetime
%                    Enter the date and time at which this deployment was started, formatted according to ISO-8601.
%
%   uses           : (1,:) <a href="matlab:help openminds.computation.WorkflowRecipeVersion" style="font-weight:bold">WorkflowRecipeVersion</a>, <a href="matlab:help openminds.core.miscellaneous.WebResource" style="font-weight:bold">WebResource</a>, <a href="matlab:help openminds.core.products.DatasetVersion" style="font-weight:bold">DatasetVersion</a>, <a href="matlab:help openminds.core.products.MetaDataModelVersion" style="font-weight:bold">MetaDataModelVersion</a>, <a href="matlab:help openminds.core.products.ModelVersion" style="font-weight:bold">ModelVersion</a>, <a href="matlab:help openminds.sands.atlas.AnatomicalAtlasVersion" style="font-weight:bold">AnatomicalAtlasVersion</a>, <a href="matlab:help openminds.sands.atlas.CommonCoordinateFrameworkVersion" style="font-weight:bold">CommonCoordinateFrameworkVersion</a>
%                    Add the deployed interfaces and any other relevant research product versions that are used by this deployment.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add the software version and any other relevant research product version that was deployed.
        dependsOn (1,:) openminds.internal.mixedtype.servicedeployment.DependsOn ...
            {mustBeListOfUniqueItems(dependsOn)}

        % Enter the type of deployment environment, for example, 'production' or 'integration'.
        deploymentType (1,:) openminds.controlledterms.DeploymentEnvironmentType ...
            {mustBeSpecifiedLength(deploymentType, 0, 1)}

        % Enter the date and time at which this deployment ended, formatted according to ISO-8601.
        endTime (1,:) datetime ...
            {mustBeSpecifiedLength(endTime, 0, 1)}

        % Enter a label for this service deployment.
        name (1,1) string

        % Add the interfaces that have been deployed.
        provides (1,:) openminds.computation.DeployedInterface ...
            {mustBeListOfUniqueItems(provides)}

        % Add the service that has been deployed.
        service (1,:) openminds.core.products.Service ...
            {mustBeSpecifiedLength(service, 0, 1)}

        % Enter the date and time at which this deployment was started, formatted according to ISO-8601.
        startTime (1,:) datetime ...
            {mustBeSpecifiedLength(startTime, 0, 1)}

        % Add the deployed interfaces and any other relevant research product versions that are used by this deployment.
        uses (1,:) openminds.internal.mixedtype.servicedeployment.Uses ...
            {mustBeListOfUniqueItems(uses)}
    end

    properties (Access = protected)
        Required = ["name", "provides", "service", "startTime"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/ServiceDeployment"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'dependsOn', ["openminds.computation.WorkflowRecipeVersion", "openminds.core.products.DatasetVersion", "openminds.core.products.MetaDataModelVersion", "openminds.core.products.ModelVersion", "openminds.core.products.SoftwareVersion", "openminds.sands.atlas.AnatomicalAtlasVersion", "openminds.sands.atlas.CommonCoordinateFrameworkVersion"], ...
            'deploymentType', "openminds.controlledterms.DeploymentEnvironmentType", ...
            'service', "openminds.core.products.Service", ...
            'uses', ["openminds.computation.WorkflowRecipeVersion", "openminds.core.miscellaneous.WebResource", "openminds.core.products.DatasetVersion", "openminds.core.products.MetaDataModelVersion", "openminds.core.products.ModelVersion", "openminds.sands.atlas.AnatomicalAtlasVersion", "openminds.sands.atlas.CommonCoordinateFrameworkVersion"] ...
        )
        EMBEDDED_PROPERTIES = struct(...
            'provides', "openminds.computation.DeployedInterface" ...
        )
    end

    methods
        function obj = ServiceDeployment(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.computation.ServiceDeployment
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.name;
        end
    end
end
