classdef DependsOn < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.computation.WorkflowRecipeVersion", ...
            "openminds.core.products.DatasetVersion", ...
            "openminds.core.products.MetaDataModelVersion", ...
            "openminds.core.products.ModelVersion", ...
            "openminds.core.products.SoftwareVersion", ...
            "openminds.sands.atlas.AnatomicalAtlasVersion", ...
            "openminds.sands.atlas.CommonCoordinateFrameworkVersion" ...
        ]
        IS_SCALAR = false
    end
end
