classdef HasPart < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.computation.WorkflowRecipeVersion", ...
            "openminds.core.data.File", ...
            "openminds.core.data.FileBundle", ...
            "openminds.core.products.SoftwareVersion" ...
        ]
        IS_SCALAR = false
    end
end