classdef Strain < openminds.abstract.Schema
%Strain - No description available.
%
%   PROPERTIES:
%
%   alternateIdentifier : (1,:) string
%                         Enter all identifiers for this strain, excluding its ontological identifiers or RRID (e.g., identifiers from the Mouse Genome Informatics (MGI) database or Rat Genome Database (RGD)).
%
%   backgroundStrain    : (1,:) <a href="matlab:help openminds.core.research.Strain" style="font-weight:bold">Strain</a>
%                         Add the background strain that explains the majority of the genetic background and/or causes the majority of the prominent traits. If two strains contributed equally, state both.
%
%   breedingType        : (1,1) <a href="matlab:help openminds.controlledterms.BreedingType" style="font-weight:bold">BreedingType</a>
%                         Add the breeding type for this strain.
%
%   description         : (1,1) string
%                         Enter a short text describing this strain.
%
%   digitalIdentifier   : (1,1) <a href="matlab:help openminds.core.digitalidentifier.RRID" style="font-weight:bold">RRID</a>
%                         Add the 'Research Resource Identifier' (RRID) of this strain.
%
%   diseaseModel        : (1,:) <a href="matlab:help openminds.controlledterms.Disease" style="font-weight:bold">Disease</a>, <a href="matlab:help openminds.controlledterms.DiseaseModel" style="font-weight:bold">DiseaseModel</a>
%                         Add all (human) diseases and/or conditions that this strain is a model for.
%
%   geneticStrainType   : (1,1) <a href="matlab:help openminds.controlledterms.GeneticStrainType" style="font-weight:bold">GeneticStrainType</a>
%                         Add the genetic background type of this strain.
%
%   laboratoryCode      : (1,1) string
%                         Enter the laboratory code assigned by the Institute of Laboratory Animal Research (ILAR) for the investigator or organization that has created this strain following the defined pattern (e.g., Aaa).
%
%   name                : (1,1) string
%                         Enter the name of this strain.
%
%   ontologyIdentifier  : (1,:) string
%                         Enter the internationalized resource identifiers (IRIs) to the related ontological terms matching this strain.
%
%   phenotype           : (1,1) string
%                         Enter a short description for the phenotype of this strain.
%
%   species             : (1,1) <a href="matlab:help openminds.controlledterms.Species" style="font-weight:bold">Species</a>
%                         Add the species of this strain.
%
%   stockNumber         : (1,1) <a href="matlab:help openminds.core.digitalidentifier.StockNumber" style="font-weight:bold">StockNumber</a>
%                         Add the stock number from the vendor the strain was supplied from/is in stock at.
%
%   synonym             : (1,:) string
%                         Enter any synonyms (including abbreviations) of this strain.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter all identifiers for this strain, excluding its ontological identifiers or RRID (e.g., identifiers from the Mouse Genome Informatics (MGI) database or Rat Genome Database (RGD)).
        alternateIdentifier (1,:) string ...
            {mustBeMinLength(alternateIdentifier, 1), mustBeListOfUniqueItems(alternateIdentifier)}

        % Add the background strain that explains the majority of the genetic background and/or causes the majority of the prominent traits. If two strains contributed equally, state both.
        backgroundStrain (1,:) openminds.core.research.Strain ...
            {mustBeMinLength(backgroundStrain, 1), mustBeMaxLength(backgroundStrain, 2), mustBeListOfUniqueItems(backgroundStrain)}

        % Add the breeding type for this strain.
        breedingType (1,:) openminds.controlledterms.BreedingType ...
            {mustBeScalarOrEmpty(breedingType)}

        % Enter a short text describing this strain.
        description (1,1) string

        % Add the 'Research Resource Identifier' (RRID) of this strain.
        digitalIdentifier (1,:) openminds.core.digitalidentifier.RRID ...
            {mustBeScalarOrEmpty(digitalIdentifier)}

        % Add all (human) diseases and/or conditions that this strain is a model for.
        diseaseModel (1,:) openminds.internal.mixedtype.strain.DiseaseModel ...
            {mustBeMinLength(diseaseModel, 1), mustBeListOfUniqueItems(diseaseModel)}

        % Add the genetic background type of this strain.
        geneticStrainType (1,:) openminds.controlledterms.GeneticStrainType ...
            {mustBeScalarOrEmpty(geneticStrainType)}

        % Enter the laboratory code assigned by the Institute of Laboratory Animal Research (ILAR) for the investigator or organization that has created this strain following the defined pattern (e.g., Aaa).
        laboratoryCode (1,1) string ...
            {mustMatchPattern(laboratoryCode, '^[A-Z]([a-z]?)+$')}

        % Enter the name of this strain.
        name (1,1) string

        % Enter the internationalized resource identifiers (IRIs) to the related ontological terms matching this strain.
        ontologyIdentifier (1,:) string ...
            {mustBeMinLength(ontologyIdentifier, 1), mustBeListOfUniqueItems(ontologyIdentifier)}

        % Enter a short description for the phenotype of this strain.
        phenotype (1,1) string

        % Add the species of this strain.
        species (1,:) openminds.controlledterms.Species ...
            {mustBeScalarOrEmpty(species)}

        % Add the stock number from the vendor the strain was supplied from/is in stock at.
        stockNumber (1,:) openminds.core.digitalidentifier.StockNumber ...
            {mustBeScalarOrEmpty(stockNumber)}

        % Enter any synonyms (including abbreviations) of this strain.
        synonym (1,:) string ...
            {mustBeMinLength(synonym, 1), mustBeListOfUniqueItems(synonym)}
    end

    properties (Access = protected)
        Required = ["geneticStrainType", "name", "species"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.ebrains.eu/core/Strain"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'backgroundStrain', "openminds.core.research.Strain", ...
            'breedingType', "openminds.controlledterms.BreedingType", ...
            'digitalIdentifier', "openminds.core.digitalidentifier.RRID", ...
            'diseaseModel', ["openminds.controlledterms.Disease", "openminds.controlledterms.DiseaseModel"], ...
            'geneticStrainType', "openminds.controlledterms.GeneticStrainType", ...
            'species', "openminds.controlledterms.Species" ...
        )
        EMBEDDED_PROPERTIES = struct(...
            'stockNumber', "openminds.core.digitalidentifier.StockNumber" ...
        )
    end

    methods
        function obj = Strain(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.core.research.Strain
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = sprintf('%s', obj.name);
        end
    end
end
