classdef Parallelogram < openminds.abstract.Schema
%Parallelogram - No description available.
%
%   PROPERTIES:
%
%   baseDistance  : (1,1) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                   Enter the perpendicular distance between the parallel lines of the base of this parallelogram.
%
%   baseLength    : (1,1) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                   Enter the uniform length of the bottom and top sides (the base) of this parallelogram.
%
%   interiorAngle : (1,1) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                   Enter an interior angle between the base and an adjacent side of this parallelogram.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter the perpendicular distance between the parallel lines of the base of this parallelogram.
        baseDistance (1,:) openminds.core.miscellaneous.QuantitativeValue ...
            {mustBeSpecifiedLength(baseDistance, 0, 1)}

        % Enter the uniform length of the bottom and top sides (the base) of this parallelogram.
        baseLength (1,:) openminds.core.miscellaneous.QuantitativeValue ...
            {mustBeSpecifiedLength(baseLength, 0, 1)}

        % Enter an interior angle between the base and an adjacent side of this parallelogram.
        interiorAngle (1,:) openminds.core.miscellaneous.QuantitativeValue ...
            {mustBeSpecifiedLength(interiorAngle, 0, 1)}
    end

    properties (Access = protected)
        Required = ["baseDistance", "baseLength", "interiorAngle"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/Parallelogram"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
        )
        EMBEDDED_PROPERTIES = struct(...
            'baseDistance', "openminds.core.miscellaneous.QuantitativeValue", ...
            'baseLength', "openminds.core.miscellaneous.QuantitativeValue", ...
            'interiorAngle', "openminds.core.miscellaneous.QuantitativeValue" ...
        )
    end

    methods
        function obj = Parallelogram(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.sands.mathematicalshape.Parallelogram
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.createLabelForMissingLabelDefinition();
        end
    end
end
