classdef RightPrism < openminds.abstract.Schema
%RightPrism - No description available.
%
%   PROPERTIES:
%
%   baseDistance : (1,1) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                  Enter the perpendicular distance between the two base planes of this right prism.
%
%   baseShape    : (1,1) <a href="matlab:help openminds.sands.mathematicalshape.EquilateralTriangle" style="font-weight:bold">EquilateralTriangle</a>, <a href="matlab:help openminds.sands.mathematicalshape.IsoscelesTriangle" style="font-weight:bold">IsoscelesTriangle</a>, <a href="matlab:help openminds.sands.mathematicalshape.Kite" style="font-weight:bold">Kite</a>, <a href="matlab:help openminds.sands.mathematicalshape.Parallelogram" style="font-weight:bold">Parallelogram</a>, <a href="matlab:help openminds.sands.mathematicalshape.Rectangle" style="font-weight:bold">Rectangle</a>, <a href="matlab:help openminds.sands.mathematicalshape.RegularPolygon" style="font-weight:bold">RegularPolygon</a>, <a href="matlab:help openminds.sands.mathematicalshape.Rhombus" style="font-weight:bold">Rhombus</a>, <a href="matlab:help openminds.sands.mathematicalshape.RightTriangle" style="font-weight:bold">RightTriangle</a>, <a href="matlab:help openminds.sands.mathematicalshape.Square" style="font-weight:bold">Square</a>, <a href="matlab:help openminds.sands.mathematicalshape.Trapezoid" style="font-weight:bold">Trapezoid</a>, <a href="matlab:help openminds.sands.mathematicalshape.Triangle" style="font-weight:bold">Triangle</a>
%                  Enter the two-dimensional base shape of the two planes of this right prism.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter the perpendicular distance between the two base planes of this right prism.
        baseDistance (1,:) openminds.core.miscellaneous.QuantitativeValue ...
            {mustBeScalarOrEmpty(baseDistance)}

        % Enter the two-dimensional base shape of the two planes of this right prism.
        baseShape (1,:) openminds.internal.mixedtype.rightprism.BaseShape ...
            {mustBeScalarOrEmpty(baseShape)}
    end

    properties (Access = protected)
        Required = ["baseDistance", "baseShape"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/RightPrism"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
        )
        EMBEDDED_PROPERTIES = struct(...
            'baseDistance', "openminds.core.miscellaneous.QuantitativeValue", ...
            'baseShape', ["openminds.sands.mathematicalshape.EquilateralTriangle", "openminds.sands.mathematicalshape.IsoscelesTriangle", "openminds.sands.mathematicalshape.Kite", "openminds.sands.mathematicalshape.Parallelogram", "openminds.sands.mathematicalshape.Rectangle", "openminds.sands.mathematicalshape.RegularPolygon", "openminds.sands.mathematicalshape.Rhombus", "openminds.sands.mathematicalshape.RightTriangle", "openminds.sands.mathematicalshape.Square", "openminds.sands.mathematicalshape.Trapezoid", "openminds.sands.mathematicalshape.Triangle"] ...
        )
    end

    methods
        function obj = RightPrism(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.sands.mathematicalshape.RightPrism
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.createLabelForMissingLabelDefinition();
        end
    end
end
