classdef Spheroid < openminds.abstract.Schema
%Spheroid - No description available.
%
%   PROPERTIES:
%
%   equatorialDiameter : (1,1) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                        Enter the equatorial diameters of this spheroid.
%
%   polarDiameter      : (1,1) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                        Enter the polar diameter of this spheroid.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter the equatorial diameters of this spheroid.
        equatorialDiameter (1,:) openminds.core.miscellaneous.QuantitativeValue ...
            {mustBeSpecifiedLength(equatorialDiameter, 0, 1)}

        % Enter the polar diameter of this spheroid.
        polarDiameter (1,:) openminds.core.miscellaneous.QuantitativeValue ...
            {mustBeSpecifiedLength(polarDiameter, 0, 1)}
    end

    properties (Access = protected)
        Required = ["equatorialDiameter", "polarDiameter"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/Spheroid"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
        )
        EMBEDDED_PROPERTIES = struct(...
            'equatorialDiameter', "openminds.core.miscellaneous.QuantitativeValue", ...
            'polarDiameter', "openminds.core.miscellaneous.QuantitativeValue" ...
        )
    end

    methods
        function obj = Spheroid(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.sands.mathematicalshape.Spheroid
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.createLabelForMissingLabelDefinition();
        end
    end
end
