classdef ConductorMaterial < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.chemicals.ChemicalMixture", ...
            "openminds.chemicals.ChemicalSubstance", ...
            "openminds.controlledterms.MolecularEntity" ...
        ]
        IS_SCALAR = true
    end
end