classdef SlicingDeviceUsage < openminds.abstract.Schema
%SlicingDeviceUsage - No description available.
%
%   PROPERTIES:
%
%   device               : (1,1) <a href="matlab:help openminds.specimenprep.SlicingDevice" style="font-weight:bold">SlicingDevice</a>
%                          Add the slicing device used.
%
%   lookupLabel          : (1,1) string
%                          Enter a lookup label for this device usage that may help you to find this instance more easily.
%
%   metadataLocation     : (1,:) <a href="matlab:help openminds.core.File" style="font-weight:bold">File</a>, <a href="matlab:help openminds.core.FileBundle" style="font-weight:bold">FileBundle</a>
%                          Add all files or file bundles containing additional information about the usage of this device.
%
%   oscillationAmplitude : (1,1) <a href="matlab:help openminds.core.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                          Enter the oscillation amplitude of the blade from the slicing device during its use.
%
%   sliceThickness       : (1,1) <a href="matlab:help openminds.core.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>, <a href="matlab:help openminds.core.QuantitativeValueRange" style="font-weight:bold">QuantitativeValueRange</a>
%                          Enter the defined slice thickness during the use of this slicing device.
%
%   slicingAngle         : (1,:) <a href="matlab:help openminds.core.NumericalProperty" style="font-weight:bold">NumericalProperty</a>, <a href="matlab:help openminds.core.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                          Enter all slicing angles (intentional or unintentional) in relation to the slicing plane used during this activity.
%
%   slicingPlane         : (1,1) <a href="matlab:help openminds.controlledterms.AnatomicalPlane" style="font-weight:bold">AnatomicalPlane</a>
%                          Add the anatomical plane that best describes the slicing direction of the tissue sample(s) during the use of this slicing device.
%
%   slicingSpeed         : (1,1) <a href="matlab:help openminds.core.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                          Enter the defined slicing speed during the use of this slicing device.
%
%   usedSpecimen         : (1,1) <a href="matlab:help openminds.core.SubjectState" style="font-weight:bold">SubjectState</a>, <a href="matlab:help openminds.core.TissueSampleState" style="font-weight:bold">TissueSampleState</a>
%                          Add the state of the tissue sample or subject that this device was used on.
%
%   vibrationFrequency   : (1,1) <a href="matlab:help openminds.core.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                          Enter the defined vibration frequency during the use of this slicing device.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add the slicing device used.
        device (1,:) openminds.specimenprep.SlicingDevice ...
            {mustBeSpecifiedLength(device, 0, 1)}

        % Enter a lookup label for this device usage that may help you to find this instance more easily.
        lookupLabel (1,1) string

        % Add all files or file bundles containing additional information about the usage of this device.
        metadataLocation (1,:) openminds.internal.mixedtype.slicingdeviceusage.MetadataLocation ...
            {mustBeListOfUniqueItems(metadataLocation)}

        % Enter the oscillation amplitude of the blade from the slicing device during its use.
        oscillationAmplitude (1,:) openminds.core.QuantitativeValue ...
            {mustBeSpecifiedLength(oscillationAmplitude, 0, 1)}

        % Enter the defined slice thickness during the use of this slicing device.
        sliceThickness (1,:) openminds.internal.mixedtype.slicingdeviceusage.SliceThickness ...
            {mustBeSpecifiedLength(sliceThickness, 0, 1)}

        % Enter all slicing angles (intentional or unintentional) in relation to the slicing plane used during this activity.
        slicingAngle (1,:) openminds.internal.mixedtype.slicingdeviceusage.SlicingAngle ...
            {mustBeSpecifiedLength(slicingAngle, 1, 2)}

        % Add the anatomical plane that best describes the slicing direction of the tissue sample(s) during the use of this slicing device.
        slicingPlane (1,:) openminds.controlledterms.AnatomicalPlane ...
            {mustBeSpecifiedLength(slicingPlane, 0, 1)}

        % Enter the defined slicing speed during the use of this slicing device.
        slicingSpeed (1,:) openminds.core.QuantitativeValue ...
            {mustBeSpecifiedLength(slicingSpeed, 0, 1)}

        % Add the state of the tissue sample or subject that this device was used on.
        usedSpecimen (1,:) openminds.internal.mixedtype.slicingdeviceusage.UsedSpecimen ...
            {mustBeSpecifiedLength(usedSpecimen, 0, 1)}

        % Enter the defined vibration frequency during the use of this slicing device.
        vibrationFrequency (1,:) openminds.core.QuantitativeValue ...
            {mustBeSpecifiedLength(vibrationFrequency, 0, 1)}
    end

    properties (Access = protected)
        Required = ["device", "sliceThickness", "slicingPlane"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.ebrains.eu/specimenPrep/SlicingDeviceUsage"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'device', "openminds.specimenprep.SlicingDevice", ...
            'metadataLocation', ["openminds.core.File", "openminds.core.FileBundle"], ...
            'slicingPlane', "openminds.controlledterms.AnatomicalPlane", ...
            'usedSpecimen', ["openminds.core.SubjectState", "openminds.core.TissueSampleState"] ...
        )
        EMBEDDED_PROPERTIES = struct(...
            'oscillationAmplitude', "openminds.core.QuantitativeValue", ...
            'sliceThickness', ["openminds.core.QuantitativeValue", "openminds.core.QuantitativeValueRange"], ...
            'slicingAngle', ["openminds.core.NumericalProperty", "openminds.core.QuantitativeValue"], ...
            'slicingSpeed', "openminds.core.QuantitativeValue", ...
            'vibrationFrequency', "openminds.core.QuantitativeValue" ...
        )
    end

    methods
        function obj = SlicingDeviceUsage(varargin)
            obj.assignPVPairs(varargin{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)

        end
    end

end