classdef ContributionType < openminds.abstract.ControlledTerm
%ContributionType - Structured information on the type of contribution a person or organization performed.
%
%   PROPERTIES:
%
%   definition         : (1,1) string
%                        Enter one sentence for defining this term.
%
%   description        : (1,1) string
%                        Enter a short text describing this term.
%
%   name               : (1,1) string
%                        Controlled term originating from a defined terminology.
%
%   ontologyIdentifier : (1,1) string
%                        Enter the internationalized resource identifier (IRI) pointing to the related ontological term.

%   This class was auto-generated by the openMINDS pipeline

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.ebrains.eu/controlledTerms/ContributionType"
    end

    properties (Constant, Hidden)
        CONTROLLED_INSTANCES = [ ...
        ]
    end

    methods
        function obj = ContributionType(instanceSpec, propValues)
            arguments
                instanceSpec = []
                propValues.?openminds.abstract.ControlledTerm
                propValues.id (1,1) string
            end

            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.ControlledTerm(instanceSpec, propValues{:})
        end
    end

    methods (Static)
        function instances = listInstances()
            instances = openminds.controlledterms.ContributionType.CONTROLLED_INSTANCES';
        end
    end
end
