classdef Origin < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.controlledterms.CellType", ...
            "openminds.controlledterms.Organ" ...
        ]
        IS_SCALAR = false
    end
end