classdef HostedBy < openminds.internal.abstract.LinkedCategory
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.controlledterms.Service", ...
            "openminds.core.actors.Organization", ...
            "openminds.core.products.WebService" ...
        ]
        IS_SCALAR = true
    end
end