function [person, affiliation] = personWithOneAffiliation()
% personWithOneAffiliation - Create a v5 Person and matching Affiliation.

    ror = openminds.core.RORID("identifier", "https://ror.org/02jx3x895");
    org = openminds.core.Organization( ...
        "digitalIdentifier", ror, ...
        "name", "University College London");

    orcid = openminds.core.ORCID( ...
        "identifier", "https://orcid.org/0000-0000-0000-0000");

    contact = openminds.core.ContactInformation( ...
        "email", "johndsmith@somewhere.org");

    person = openminds.core.Person( ...
        "familyName", "Smith", ...
        "givenName", "John D.", ...
        "preferredName", "John D. Smith", ...
        "alternateName", "js", ...
        "digitalIdentifier", orcid, ...
        "contactInformation", contact);

    affiliation = openminds.core.Affiliation( ...
        "person", person, ...
        "organization", org);
end
