function [person, affiliations] = personWithTwoAffiliations()
% personWithTwoAffiliations - Create a v5 Person and two Affiliation records.

    ror = openminds.core.RORID("identifier", "https://ror.org/02jx3x895");
    orgA = openminds.core.Organization( ...
        "digitalIdentifier", ror, ...
        "name", "University College London");

    ror = openminds.core.RORID("identifier", "https://ror.org/01xtthb56");
    orgB = openminds.core.Organization( ...
        "digitalIdentifier", ror, ...
        "name", "University of Oslo", ...
        "acronym", "UiO");

    orcid = openminds.core.ORCID( ...
        "identifier", "https://orcid.org/0000-0000-0000-0000");

    contact = openminds.core.ContactInformation( ...
        "email", "johndsmith@somewhere.org");

    person = openminds.core.Person( ...
        "familyName", "Smith", ...
        "givenName", "John D.", ...
        "preferredName", "John D. Smith", ...
        "digitalIdentifier", orcid, ...
        "contactInformation", contact);

    affiliations = openminds.core.Affiliation( ...
        "person", person, ...
        "organization", orgA);
    affiliations(2) = openminds.core.Affiliation( ...
        "person", person, ...
        "organization", orgB);
end
