classdef Pipette < openminds.abstract.Schema
%Pipette - No description available.
%
%   PROPERTIES:
%
%   description        : (1,1) string
%                        Enter a short text describing this device.
%
%   deviceType         : (1,1) <a href="matlab:help openminds.controlledterms.DeviceType" style="font-weight:bold">DeviceType</a>
%                        Add the type of this device.
%
%   digitalIdentifier  : (1,1) <a href="matlab:help openminds.core.digitalidentifier.DOI" style="font-weight:bold">DOI</a>, <a href="matlab:help openminds.core.digitalidentifier.RRID" style="font-weight:bold">RRID</a>
%                        Add the globally unique and persistent digital identifier of this device.
%
%   externalDiameter   : (1,1) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                        Enter the external diameter of the pipette.
%
%   internalDiameter   : (1,1) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%                        Enter the internal diameter of the pipette.
%
%   internalIdentifier : (1,1) string
%                        Enter the identifier (or label) of this pipette that is used within the corresponding data files to identify this pipette.
%
%   lookupLabel        : (1,1) string
%                        Enter a lookup label for this device that may help you to find this instance more easily.
%
%   manufacturer       : (1,:) <a href="matlab:help openminds.core.actors.Consortium" style="font-weight:bold">Consortium</a>, <a href="matlab:help openminds.core.actors.Organization" style="font-weight:bold">Organization</a>, <a href="matlab:help openminds.core.actors.Person" style="font-weight:bold">Person</a>
%                        Add the manufacturer (private or industrial) that constructed this device.
%
%   material           : (1,1) <a href="matlab:help openminds.chemicals.ChemicalMixture" style="font-weight:bold">ChemicalMixture</a>, <a href="matlab:help openminds.chemicals.ChemicalSubstance" style="font-weight:bold">ChemicalSubstance</a>, <a href="matlab:help openminds.controlledterms.MolecularEntity" style="font-weight:bold">MolecularEntity</a>
%                        Add the material that the pipette is made of.
%
%   name               : (1,1) string
%                        Enter a descriptive name for this device, preferably including the model name as defined by the manufacturer.
%
%   owner              : (1,:) <a href="matlab:help openminds.core.actors.Consortium" style="font-weight:bold">Consortium</a>, <a href="matlab:help openminds.core.actors.Organization" style="font-weight:bold">Organization</a>, <a href="matlab:help openminds.core.actors.Person" style="font-weight:bold">Person</a>
%                        Add all parties that legally own this device.
%
%   serialNumber       : (1,1) string
%                        Enter the serial number of this device.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter a short text describing this device.
        description (1,1) string

        % Add the type of this device.
        deviceType (1,:) openminds.controlledterms.DeviceType ...
            {mustBeSpecifiedLength(deviceType, 0, 1)}

        % Add the globally unique and persistent digital identifier of this device.
        digitalIdentifier (1,:) openminds.internal.mixedtype.pipette.DigitalIdentifier ...
            {mustBeSpecifiedLength(digitalIdentifier, 0, 1)}

        % Enter the external diameter of the pipette.
        externalDiameter (1,:) openminds.core.miscellaneous.QuantitativeValue ...
            {mustBeSpecifiedLength(externalDiameter, 0, 1)}

        % Enter the internal diameter of the pipette.
        internalDiameter (1,:) openminds.core.miscellaneous.QuantitativeValue ...
            {mustBeSpecifiedLength(internalDiameter, 0, 1)}

        % Enter the identifier (or label) of this pipette that is used within the corresponding data files to identify this pipette.
        internalIdentifier (1,1) string

        % Enter a lookup label for this device that may help you to find this instance more easily.
        lookupLabel (1,1) string

        % Add the manufacturer (private or industrial) that constructed this device.
        manufacturer (1,:) openminds.internal.mixedtype.pipette.Manufacturer ...
            {mustBeListOfUniqueItems(manufacturer)}

        % Add the material that the pipette is made of.
        material (1,:) openminds.internal.mixedtype.pipette.Material ...
            {mustBeSpecifiedLength(material, 0, 1)}

        % Enter a descriptive name for this device, preferably including the model name as defined by the manufacturer.
        name (1,1) string

        % Add all parties that legally own this device.
        owner (1,:) openminds.internal.mixedtype.pipette.Owner ...
            {mustBeListOfUniqueItems(owner)}

        % Enter the serial number of this device.
        serialNumber (1,1) string
    end

    properties (Access = protected)
        Required = ["deviceType", "name"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.ebrains.eu/ephys/Pipette"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'deviceType', "openminds.controlledterms.DeviceType", ...
            'digitalIdentifier', ["openminds.core.digitalidentifier.DOI", "openminds.core.digitalidentifier.RRID"], ...
            'manufacturer', ["openminds.core.actors.Consortium", "openminds.core.actors.Organization", "openminds.core.actors.Person"], ...
            'material', ["openminds.chemicals.ChemicalMixture", "openminds.chemicals.ChemicalSubstance", "openminds.controlledterms.MolecularEntity"], ...
            'owner', ["openminds.core.actors.Consortium", "openminds.core.actors.Organization", "openminds.core.actors.Person"] ...
        )
        EMBEDDED_PROPERTIES = struct(...
            'externalDiameter', "openminds.core.miscellaneous.QuantitativeValue", ...
            'internalDiameter', "openminds.core.miscellaneous.QuantitativeValue" ...
        )
    end

    methods
        function obj = Pipette(structInstance, propValues)
            arguments
                structInstance (1,:) struct = struct.empty
                propValues.?openminds.ephys.device.Pipette
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.lookupLabel;
        end
    end
end
