classdef InputData < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.core.data.File", ...
            "openminds.core.data.FileBundle", ...
            "openminds.core.digitalidentifier.DOI", ...
            "openminds.core.miscellaneous.WebResource", ...
            "openminds.sands.atlas.AnatomicalAtlas", ...
            "openminds.sands.atlas.AnatomicalAtlasVersion", ...
            "openminds.sands.atlas.CommonCoordinateFramework", ...
            "openminds.sands.atlas.CommonCoordinateFrameworkVersion" ...
        ]
        IS_SCALAR = false
    end
end
