classdef StudiedSpecimen < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.core.research.Subject", ...
            "openminds.core.research.SubjectGroup", ...
            "openminds.core.research.SubjectGroupState", ...
            "openminds.core.research.SubjectState", ...
            "openminds.core.research.TissueSample", ...
            "openminds.core.research.TissueSampleCollection", ...
            "openminds.core.research.TissueSampleCollectionState", ...
            "openminds.core.research.TissueSampleState" ...
        ]
        IS_SCALAR = false
    end
end
