classdef Service < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.core.miscellaneous.WebResource", ...
            "openminds.core.products.Interface", ...
            "openminds.core.products.InterfaceVersion" ...
        ]
        IS_SCALAR = false
    end
end
