classdef RelatedInterspeciesAnatomy < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.controlledterms.AnatomicalCavity", ...
            "openminds.controlledterms.ExternalBodyRegion", ...
            "openminds.controlledterms.MuscularStructure", ...
            "openminds.controlledterms.NervousSystemStructure", ...
            "openminds.controlledterms.Organ", ...
            "openminds.controlledterms.OrganSystemStructure", ...
            "openminds.controlledterms.OrganismSubstance", ...
            "openminds.controlledterms.OrganismSystem", ...
            "openminds.controlledterms.SkeletalStructure", ...
            "openminds.controlledterms.TissueStructure", ...
            "openminds.controlledterms.VascularStructure" ...
        ]
        IS_SCALAR = true
    end
end
