classdef Circle < openminds.abstract.Schema
%Circle - No description available.
%
%   PROPERTIES:
%
%   radius : (1,1) <a href="matlab:help openminds.core.miscellaneous.QuantitativeValue" style="font-weight:bold">QuantitativeValue</a>
%            Enter the radius of this circle.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter the radius of this circle.
        radius (1,:) openminds.core.miscellaneous.QuantitativeValue ...
            {mustBeSpecifiedLength(radius, 0, 1)}
    end

    properties (Access = protected)
        Required = ["radius"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.ebrains.eu/sands/Circle"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
        )
        EMBEDDED_PROPERTIES = struct(...
            'radius', "openminds.core.miscellaneous.QuantitativeValue" ...
        )
    end

    methods
        function obj = Circle(varargin)
            obj@openminds.abstract.Schema(varargin{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = sprintf('circle(r=%s)', obj.radius);
        end
    end
end