classdef HasPart < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.core.products.Setup", ...
            "openminds.core.products.SoftwareVersion", ...
            "openminds.ephys.device.Electrode", ...
            "openminds.ephys.device.ElectrodeArray", ...
            "openminds.ephys.device.Pipette", ...
            "openminds.specimenprep.device.SlicingDevice" ...
        ]
        IS_SCALAR = false
    end
end