classdef InputData < openminds.internal.abstract.LinkedCategory
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.core.data.File", ...
            "openminds.core.data.FileBundle", ...
            "openminds.core.digitalidentifier.DOI", ...
            "openminds.core.miscellaneous.WebResource", ...
            "openminds.sands.atlas.BrainAtlas", ...
            "openminds.sands.atlas.BrainAtlasVersion", ...
            "openminds.sands.atlas.CommonCoordinateSpace", ...
            "openminds.sands.atlas.CommonCoordinateSpaceVersion" ...
        ]
        IS_SCALAR = false
    end
end