classdef PublicationVolume < openminds.abstract.Schema
%PublicationVolume - No description available.
%
%   PROPERTIES:
%
%   isPartOf     : (1,1) <a href="matlab:help openminds.publications.Periodical" style="font-weight:bold">Periodical</a>
%                  Add the periodical this publication volume is part of.
%
%   volumeNumber : (1,1) string
%                  Enter the volume number of this publication volume.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add the periodical this publication volume is part of.
        isPartOf (1,:) openminds.publications.Periodical ...
            {mustBeSpecifiedLength(isPartOf, 0, 1)}

        % Enter the volume number of this publication volume.
        volumeNumber (1,1) string
    end

    properties (Access = protected)
        Required = ["isPartOf", "volumeNumber"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.ebrains.eu/publications/PublicationVolume"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'isPartOf', "openminds.publications.Periodical" ...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = PublicationVolume(varargin)
            obj.assignPVPairs(varargin{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)

        end
    end

end