classdef ParcellationEntity < openminds.abstract.Schema & openminds.internal.mixin.HasControlledInstance
%ParcellationEntity - No description available.
%
%   PROPERTIES:
%
%   abbreviation               : (1,1) string
%                                Enter the official abbreviation of this parcellation entity.
%
%   alternateName              : (1,:) string
%                                Enter any alternate names, including any alternative abbreviations, for this parcellation entity.
%
%   definition                 : (1,1) string
%                                Enter the definition for this parcellation entity.
%
%   hasParent                  : (1,:) <a href="matlab:help openminds.sands.atlas.ParcellationEntity" style="font-weight:bold">ParcellationEntity</a>
%                                Add all anatomical parent structures for this parcellation entity as defined within the corresponding brain atlas.
%
%   lookupLabel                : (1,1) string
%                                Enter a lookup label for this parcellation entity that may help you to find this instance more easily.
%
%   name                       : (1,1) string
%                                Enter the name of this parcellation entity.
%
%   ontologyIdentifier         : (1,:) string
%                                Enter the internationalized resource identifiers (IRIs) to the related ontological terms matching this parcellation entity.
%
%   relatedInterspeciesAnatomy : (1,1) <a href="matlab:help openminds.controlledterms.AnatomicalCavity" style="font-weight:bold">AnatomicalCavity</a>, <a href="matlab:help openminds.controlledterms.ExternalBodyRegion" style="font-weight:bold">ExternalBodyRegion</a>, <a href="matlab:help openminds.controlledterms.MuscularStructure" style="font-weight:bold">MuscularStructure</a>, <a href="matlab:help openminds.controlledterms.NervousSystemStructure" style="font-weight:bold">NervousSystemStructure</a>, <a href="matlab:help openminds.controlledterms.Organ" style="font-weight:bold">Organ</a>, <a href="matlab:help openminds.controlledterms.OrganSystemStructure" style="font-weight:bold">OrganSystemStructure</a>, <a href="matlab:help openminds.controlledterms.OrganismSubstance" style="font-weight:bold">OrganismSubstance</a>, <a href="matlab:help openminds.controlledterms.OrganismSystem" style="font-weight:bold">OrganismSystem</a>, <a href="matlab:help openminds.controlledterms.SkeletalStructure" style="font-weight:bold">SkeletalStructure</a>, <a href="matlab:help openminds.controlledterms.TissueStructure" style="font-weight:bold">TissueStructure</a>, <a href="matlab:help openminds.controlledterms.VascularStructure" style="font-weight:bold">VascularStructure</a>
%                                Add the corresponding cross-species anatomical entity from the UBERON-derived terminologies that represents the generic anatomical concept underlying the atlas parcellation entity.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter the official abbreviation of this parcellation entity.
        abbreviation (1,1) string

        % Enter any alternate names, including any alternative abbreviations, for this parcellation entity.
        alternateName (1,:) string ...
            {mustBeListOfUniqueItems(alternateName)}

        % Enter the definition for this parcellation entity.
        definition (1,1) string

        % Add all anatomical parent structures for this parcellation entity as defined within the corresponding brain atlas.
        hasParent (1,:) openminds.sands.atlas.ParcellationEntity ...
            {mustBeListOfUniqueItems(hasParent)}

        % Enter a lookup label for this parcellation entity that may help you to find this instance more easily.
        lookupLabel (1,1) string

        % Enter the name of this parcellation entity.
        name (1,1) string

        % Enter the internationalized resource identifiers (IRIs) to the related ontological terms matching this parcellation entity.
        ontologyIdentifier (1,:) string ...
            {mustBeListOfUniqueItems(ontologyIdentifier)}

        % Add the corresponding cross-species anatomical entity from the UBERON-derived terminologies that represents the generic anatomical concept underlying the atlas parcellation entity.
        relatedInterspeciesAnatomy (1,:) openminds.internal.mixedtype.parcellationentity.RelatedInterspeciesAnatomy ...
            {mustBeSpecifiedLength(relatedInterspeciesAnatomy, 0, 1)}
    end

    properties (Access = protected)
        Required = ["lookupLabel", "name"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/ParcellationEntity"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'hasParent', "openminds.sands.atlas.ParcellationEntity", ...
            'relatedInterspeciesAnatomy', ["openminds.controlledterms.AnatomicalCavity", "openminds.controlledterms.ExternalBodyRegion", "openminds.controlledterms.MuscularStructure", "openminds.controlledterms.NervousSystemStructure", "openminds.controlledterms.Organ", "openminds.controlledterms.OrganSystemStructure", "openminds.controlledterms.OrganismSubstance", "openminds.controlledterms.OrganismSystem", "openminds.controlledterms.SkeletalStructure", "openminds.controlledterms.TissueStructure", "openminds.controlledterms.VascularStructure"] ...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = ParcellationEntity(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.sands.atlas.ParcellationEntity
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.lookupLabel;
        end
    end

    methods (Static)
        function instance = fromName(name)
            typeName = mfilename('classname');
            instance = openminds.internal.mixin.HasControlledInstance.fromName(name, typeName);
        end
        function instanceNames = listInstances()
            typeName = mfilename('classname');
            instanceNames = openminds.internal.mixin.HasControlledInstance.listInstances(typeName);
        end
    end
end
