classdef AccountInformation < openminds.abstract.Schema
%AccountInformation - Structured information about a user account for a web service.
%
%   PROPERTIES:
%
%   service  : (1,1) <a href="matlab:help openminds.core.products.WebService" style="font-weight:bold">WebService</a>
%              Add the web service of this account.
%
%   userName : (1,1) string
%              Enter the user name for this account.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add the web service of this account.
        service (1,:) openminds.core.products.WebService ...
            {mustBeSpecifiedLength(service, 0, 1)}

        % Enter the user name for this account.
        userName (1,1) string
    end

    properties (Access = protected)
        Required = ["service", "userName"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/AccountInformation"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'service', "openminds.core.products.WebService" ...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = AccountInformation(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.core.actors.AccountInformation
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = sprintf('%s', obj.service);
        end
    end
end
