classdef ContactInformation < openminds.abstract.Schema
%ContactInformation - Structured information about how to contact a given person or consortium.
%
%   PROPERTIES:
%
%   email : (1,1) string
%           Enter the email address of the party (e.g., of the person).

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Enter the email address of the party (e.g., of the person).
        email (1,1) string
    end

    properties (Access = protected)
        Required = ["email"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/ContactInformation"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = ContactInformation(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.core.actors.ContactInformation
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = sprintf('%s', obj.email);
        end
    end
end
