classdef OutputData < openminds.internal.abstract.LinkedCategory
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.core.data.File", ...
            "openminds.core.data.FileBundle", ...
            "openminds.core.digitalidentifier.DOI", ...
            "openminds.core.miscellaneous.WebResource" ...
        ]
        IS_SCALAR = false
    end
end