classdef DigitalIdentifier < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.core.digitalidentifier.GenericIdentifier", ...
            "openminds.core.digitalidentifier.ORCID" ...
        ]
        IS_SCALAR = false
    end
end
