classdef SlicingDevice < openminds.abstract.Schema
%SlicingDevice - No description available.
%
%   PROPERTIES:
%
%   contribution       : (1,:) <a href="matlab:help openminds.core.actors.Organization" style="font-weight:bold">Organization</a>, <a href="matlab:help openminds.core.actors.Person" style="font-weight:bold">Person</a>
%                        Add all relevant contributions (e.g., ownership, maintenance) for this device.
%
%   description        : (1,1) string
%                        Enter a short description of the device. Describe the device itself for a custom-built device or note device-specific peculiarities or deviations from the standard product for a manufacturer-defined device.
%
%   internalIdentifier : (1,1) string
%                        Enter the identifier (or label) of this device that is used by the owner to identify or reference this device.
%
%   name               : (1,1) string
%                        Enter a descriptive name for this device, preferably defined by the owner.
%
%   serialNumber       : (1,1) string
%                        Enter the serial number of this device.
%
%   type               : (1,1) <a href="matlab:help openminds.controlledterms.DeviceType" style="font-weight:bold">DeviceType</a>, <a href="matlab:help openminds.core.products.HardwareProduct" style="font-weight:bold">HardwareProduct</a>
%                        Add the device classification reference. Identify a device type for a custom-built device, or a hardware product for a device corresponding to a manufacturer-defined product model.

%   This class was auto-generated by the openMINDS pipeline

    properties
        % Add all relevant contributions (e.g., ownership, maintenance) for this device.
        contribution (1,:) openminds.internal.mixedtype.slicingdevice.Contribution ...
            {mustBeMinLength(contribution, 1), mustBeListOfUniqueItems(contribution)}

        % Enter a short description of the device. Describe the device itself for a custom-built device or note device-specific peculiarities or deviations from the standard product for a manufacturer-defined device.
        description (1,1) string

        % Enter the identifier (or label) of this device that is used by the owner to identify or reference this device.
        internalIdentifier (1,1) string

        % Enter a descriptive name for this device, preferably defined by the owner.
        name (1,1) string

        % Enter the serial number of this device.
        serialNumber (1,1) string

        % Add the device classification reference. Identify a device type for a custom-built device, or a hardware product for a device corresponding to a manufacturer-defined product model.
        type (1,:) openminds.internal.mixedtype.slicingdevice.Type ...
            {mustBeScalarOrEmpty(type)}
    end

    properties (Access = protected)
        Required = ["contribution", "name", "type"]
    end

    properties (Constant, Hidden)
        X_TYPE = "https://openminds.om-i.org/types/SlicingDevice"
    end

    properties (Constant, Hidden)
        LINKED_PROPERTIES = struct(...
            'contribution', ["openminds.core.actors.Organization", "openminds.core.actors.Person"], ...
            'type', ["openminds.controlledterms.DeviceType", "openminds.core.products.HardwareProduct"] ...
        )
        EMBEDDED_PROPERTIES = struct(...
        )
    end

    methods
        function obj = SlicingDevice(structInstance, propValues)
            arguments
                structInstance (1,:) {mustBeA(structInstance, 'struct')} = struct.empty
                propValues.?openminds.specimenprep.device.SlicingDevice
                propValues.id (1,1) string
            end
            propValues = namedargs2cell(propValues);
            obj@openminds.abstract.Schema(structInstance, propValues{:})
        end
    end

    methods (Access = protected)
        function str = getDisplayLabel(obj)
            str = obj.name;
        end
    end
end
