classdef Specification < openminds.internal.abstract.MixedTypeSet
    properties (Constant, Hidden)
        ALLOWED_TYPES = [ ...
            "openminds.core.data.File", ...
            "openminds.core.data.FileBundle", ...
            "openminds.core.research.Configuration", ...
            "openminds.core.research.PropertyValueList" ...
        ]
        IS_SCALAR = false
    end
end